#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_run_id",
    "Pump Speed": "pump_speed",
    "Replicates": "replicates",
    "Resin Mass": "resin_mass_mg",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume_uL",
    "Venting time": "venting_time_s",
    "Pump Duration": "pump_duration_s",
    "Incubation Time": "incubation_time_min",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume_uL",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature_c",
    "Measurement Wavelength": "measurement_wavelength_nm",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation_rpm",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration_s",
    "Number of salt concentrations": "n_salt_concentrations",
    "Number of ligand concentrations": "n_ligand_concentrations",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Buffer solution used during loading isotherm experiment",
        },
        "salt_name": {
            "type": "string",
            "description": "Name/identity of the salt used in the mobile phase",
        },
        "process_run_id": {
            "type": "string",
            "description": "Identifier of the automated process run (as stored in eLabFTW)",
        },
        "pump_speed": {
            "type": "number",
            "description": "Pump speed used during loading and equilibration (unit as configured on system)",
        },
        "replicates": {
            "type": "integer",
            "description": "Number of replicate wells per (salt, ligand) condition",
        },
        "resin_mass_mg": {
            "type": "number",
            "description": "Resin mass per well",
            "unit": "mg",
        },
        "ligand_name": {
            "type": "string",
            "description": "Name/identity of the ligand analyte",
        },
        "total_volume_uL": {
            "type": "number",
            "description": "Total liquid volume per well used for incubation",
            "unit": "µL",
        },
        "venting_time_s": {
            "type": "number",
            "description": "Venting time for automated system steps",
            "unit": "s",
        },
        "pump_duration_s": {
            "type": "number",
            "description": "Duration of the pump step during loading/equilibration",
            "unit": "s",
        },
        "incubation_time_min": {
            "type": "number",
            "description": "Incubation time of resin with ligand solution",
            "unit": "min",
        },
        "salt_concentrations": {
            "type": "array",
            "description": "List of salt concentrations used in the experiment (as provided in eLabFTW). Parsed from semicolon/comma-separated values where possible.",
            "items": {"type": "number"},
        },
        "equilibration_cycles": {
            "type": "integer",
            "description": "Number of equilibration cycles performed",
        },
        "equilibration_volume_uL": {
            "type": "number",
            "description": "Volume used for each equilibration cycle",
            "unit": "µL",
        },
        "ligand_concentrations": {
            "type": "array",
            "description": "List of ligand concentrations used in the experiment (as provided in eLabFTW). Parsed from semicolon/comma-separated values where possible.",
            "items": {"type": "number"},
        },
        "incubation_temperature_c": {
            "type": "number",
            "description": "Incubation temperature",
            "unit": "°C",
        },
        "measurement_wavelength_nm": {
            "type": "number",
            "description": "Measurement wavelength used by the Tecan plate reader",
            "unit": "nm",
        },
        "calibration_curve_slope": {
            "type": "number",
            "description": "Slope of the calibration curve used to convert absorbance to concentration",
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit of the salt concentrations (e.g. mM)",
        },
        "shaker_speed_incubation_rpm": {
            "type": "number",
            "description": "Shaker speed during incubation",
            "unit": "rpm",
        },
        "salt_stock_concentration": {
            "type": "number",
            "description": "Stock concentration of the salt solution",
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit of the ligand concentrations (e.g. µM, mM)",
        },
        "ligand_stock_concentration": {
            "type": "number",
            "description": "Stock concentration of the ligand solution",
        },
        "calibration_curve_intercept": {
            "type": "number",
            "description": "Intercept of the calibration curve used to convert absorbance to concentration",
        },
        "equilibration_cycle_duration_s": {
            "type": "number",
            "description": "Duration of one equilibration cycle",
            "unit": "s",
        },
        "n_salt_concentrations": {
            "type": "integer",
            "description": "Number of distinct salt concentrations used",
        },
        "n_ligand_concentrations": {
            "type": "integer",
            "description": "Number of distinct ligand concentrations used",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "success", "failed"],
            "description": "Status of the Tecan loading isotherm analysis",
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp at which results were committed to the database",
        },
        "analysis_results": {
            "type": "object",
            "description": "Raw analysis_results JSON produced by the analysis script (analysis_results_<id>.json)",
        },
        "summary": {
            "type": "object",
            "description": "Summary metrics extracted from Langmuir fits and aggregation results",
            "properties": {
                "n_salt_conditions": {
                    "type": "integer",
                    "description": "Number of distinct salt concentrations with Langmuir fits",
                },
                "n_ligand_conditions": {
                    "type": "integer",
                    "description": "Number of distinct ligand concentrations used in analysis",
                },
                "n_points_total": {
                    "type": "integer",
                    "description": "Total number of (salt, ligand) data points fitted (n_salt_conditions * n_ligand_conditions)",
                },
                "qmax_values": {
                    "type": "array",
                    "description": "List of fitted qmax values per salt concentration (may include nulls if fit failed)",
                    "items": {"type": ["number", "null"]},
                },
                "K_values": {
                    "type": "array",
                    "description": "List of fitted Langmuir K values per salt concentration (may include nulls if fit failed)",
                    "items": {"type": ["number", "null"]},
                },
                "r2_values": {
                    "type": "array",
                    "description": "List of R^2 values of Langmuir fits per salt concentration (may include nulls if fit failed)",
                    "items": {"type": ["number", "null"]},
                },
                "mean_qmax": {
                    "type": ["number", "null"],
                    "description": "Mean of all non-null qmax values",
                },
                "mean_r2": {
                    "type": ["number", "null"],
                    "description": "Mean of all non-null R^2 values",
                },
            },
        },
        "data_files": {
            "type": "object",
            "description": "Structured paths to result data files (CSV, Excel and JSON)",
            "properties": {
                "analysis_results_json": {
                    "type": "string",
                    "description": "Path to analysis_results_<id>.json",
                },
                "plate_raw_mapping_csv": {
                    "type": "string",
                    "description": "Path to plate_raw_mapping_<id>.csv",
                },
                "aggregated_conditions_csv": {
                    "type": "string",
                    "description": "Path to aggregated_conditions_<id>.csv",
                },
                "langmuir_fits_csv": {
                    "type": "string",
                    "description": "Path to langmuir_fits_<id>.csv",
                },
                "tecan_raw_file": {
                    "type": "string",
                    "description": "Path to downloaded Tecan raw Excel file",
                },
            },
        },
        "plots": {
            "type": "object",
            "description": "Paths to generated isotherm plots",
            "properties": {
                "isotherms_png": {
                    "type": "string",
                    "description": "Path to loading_isotherms_<id>.png",
                },
                "isotherms_pdf": {
                    "type": "string",
                    "description": "Path to loading_isotherms_<id>.pdf",
                },
            },
        },
        "warnings": {
            "type": "array",
            "description": "Any warnings generated during analysis (copied from analysis_results JSON if present)",
            "items": {"type": "string"},
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "analysis_results_{elab_id}.json",
        "plate_raw_mapping_{elab_id}.csv",
        "aggregated_conditions_{elab_id}.csv",
        "langmuir_fits_{elab_id}.csv",
        "tecan_data_{elab_id}.xlsx",
    ],
    "plots": [
        "loading_isotherms_{elab_id}.png",
        "loading_isotherms_{elab_id}.pdf",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value: str):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    text = str(value).strip()
    if text == "":
        return None
    import re

    match = re.search(r"[-+]?\d*[\.,]?\d+", text)
    if not match:
        return None
    num_str = match.group(0).replace(",", ".")
    try:
        return float(num_str)
    except ValueError:
        return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """

    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()
    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Check for potential decimal comma case: joined parts form a number
            joined = "".join(parts)
            maybe_number = parse_numeric(joined)
            # Heuristic: if joined parses as number and there was exactly one separator,
            # and original text contains no ';', treat as decimal rather than list.
            if maybe_number is not None and sep == "," and ";" not in text:
                return maybe_number
            # Try numeric list
            try:
                return [float(p.replace(",", ".")) for p in parts]
            except ValueError:
                return parts
    if field_type == "number":
        parsed = parse_numeric(text)
        return parsed if parsed is not None else text
    return text  # text stays text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields."""
    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name not in extra_fields:
            continue
        field = extra_fields[elab_name]
        value = field.get("value")
        field_type = field.get("type")
        parsed_value = parse_field(value, field_type=field_type)
        metadata[db_name] = parsed_value
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id):
    """Load analysis_results_<id>.json if present and return parsed dict.

    Returns (results_dict, path_str) or (None, None) if not found/parsable.
    """
    candidate_paths = [
        Path("../results") / f"analysis_results_{elab_id}.json",
        Path("../analysis") / f"analysis_results_{elab_id}.json",
    ]
    for p in candidate_paths:
        if p.exists():
            try:
                with open(p, "r") as f:
                    return json.load(f), str(p.resolve())
            except Exception:
                return None, None
    return None, None


def build_results(elab_id):
    """Build results JSONB structure from analysis outputs.

    This function is process-specific and tailored to the Tecan loading
    isotherm analysis script provided.
    """

    results: dict = {
        "analysis_status": "pending",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "analysis_results": None,
        "summary": {},
        "data_files": {},
        "plots": {},
        "warnings": [],
    }

    analysis_results, analysis_results_path = load_analysis_results(elab_id)
    if analysis_results is None:
        # No analysis results yet; still return minimal structure
        return results

    # Copy raw analysis_results JSON
    results["analysis_results"] = analysis_results

    # Determine status
    status = analysis_results.get("status") or analysis_results.get("analysis_status")
    if status in {"success", "failed", "pending"}:
        results["analysis_status"] = status
    else:
        results["analysis_status"] = "failed" if status not in (None, "") else "pending"

    # Warnings
    warnings = analysis_results.get("warnings")
    if isinstance(warnings, list):
        results["warnings"] = [str(w) for w in warnings]

    # Data files
    data_files = {
        "analysis_results_json": analysis_results_path,
    }
    data_outputs = analysis_results.get("data_outputs", {})
    if isinstance(data_outputs, dict):
        for key in [
            "plate_raw_mapping_csv",
            "aggregated_conditions_csv",
            "langmuir_fits_csv",
            "tecan_raw_file",
        ]:
            if key in data_outputs:
                data_files[key] = data_outputs[key]
    results["data_files"] = data_files

    # Plots
    plots = {}
    plots_dict = analysis_results.get("plots", {})
    if isinstance(plots_dict, dict):
        if "isotherms_png" in plots_dict:
            plots["isotherms_png"] = plots_dict["isotherms_png"]
        if "isotherms_pdf" in plots_dict:
            plots["isotherms_pdf"] = plots_dict["isotherms_pdf"]
    results["plots"] = plots

    # Summary from metadata and Langmuir fit CSV if accessible
    summary: dict = {}

    # Pull numeric metadata from analysis_results["metadata"] if available
    ar_meta = analysis_results.get("metadata", {})
    if isinstance(ar_meta, dict):
        n_salt = ar_meta.get("n_salt_conc")
        n_lig = ar_meta.get("n_ligand_conc")
        if isinstance(n_salt, int):
            summary["n_salt_conditions"] = n_salt
        if isinstance(n_lig, int):
            summary["n_ligand_conditions"] = n_lig

    # Attempt to parse Langmuir fit CSV for qmax, K, R2 statistics
    langmuir_csv = data_files.get("langmuir_fits_csv")
    qmax_values = []
    K_values = []
    r2_values = []
    if langmuir_csv and Path(langmuir_csv).exists():
        try:
            import csv

            with open(langmuir_csv, newline="") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    # Expected columns: salt_index,salt_concentration,qmax,K,R2
                    for key, target_list in [
                        ("qmax", qmax_values),
                        ("K", K_values),
                        ("R2", r2_values),
                    ]:
                        val = row.get(key)
                        if val is None or val == "" or str(val).lower() == "none":
                            target_list.append(None)
                        else:
                            try:
                                target_list.append(float(val))
                            except ValueError:
                                target_list.append(None)
        except Exception:
            # If parsing fails, continue with whatever we have
            pass

    def _mean_non_null(vals):
        nums = [v for v in vals if isinstance(v, (int, float))]
        if not nums:
            return None
        return sum(nums) / len(nums)

    if qmax_values:
        summary["qmax_values"] = qmax_values
        summary["mean_qmax"] = _mean_non_null(qmax_values)
    if r2_values:
        summary["r2_values"] = r2_values
        summary["mean_r2"] = _mean_non_null(r2_values)
    if K_values:
        summary["K_values"] = K_values

    # Estimate total number of points
    n_points = None
    if "n_salt_conditions" in summary and "n_ligand_conditions" in summary:
        try:
            n_points = int(summary["n_salt_conditions"]) * int(
                summary["n_ligand_conditions"]
            )
        except Exception:
            n_points = None
    if n_points is not None:
        summary["n_points_total"] = n_points

    results["summary"] = summary

    return results


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""
    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    return cursor.fetchone()[0]


def main():
    parser = argparse.ArgumentParser(
        description=f"Commit {PROCESS_NAME} to database"
    )
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {})
        workflow_json, lab_id = load_workflow()

        # Build data structures
        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": "completed",
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": extract_metadata(extra_fields),
            "raw_data": build_raw_data(args.elab_id),
            "results": build_results(args.elab_id),
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(
            f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})"
        )
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if "conn" in locals():
            conn.rollback()
        return 1
    finally:
        if "conn" in locals():
            conn.close()


if __name__ == "__main__":
    sys.exit(main())