#!/usr/bin/env python3
"""
Database commit script for AKTA - Gradient Elution (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 36
PROCESS_NAME = "AKTA - Gradient Elution (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Process ID": "linked_process_id",
    "CIP_DURATION": "cip_high_salt_duration_s",
    "WASH_DURATION": "wash_duration_s",
    "CIP_3_DURATION": "cip_h2o1_duration_s",
    "CIP_4_DURATION": "cip_hcl_duration_s",
    "CIP_5_DURATION": "cip_h2o2_duration_s",
    "WASH_FLOW_RATE": "wash_flow_rate_ml_min",
    "CIP_2_HOLD_DURATION": "cip_naoh_hold_duration_s",
    "LOAD_INJECT_DURATION": "load_inject_duration_s",
    "LOAD_INJECT_FLOW_RATE": "load_inject_flow_rate_ml_min",
    "EQUILIBRATION_DURATION": "equilibration_duration_s",
    "ELUTE_GRADIENT_DURATION": "elute_gradient_duration_s",
    "EQUILIBRATION_FLOW_RATE": "equilibration_flow_rate_ml_min",
    "ELUTE_GRADIENT_GRADIENT_END": "elute_gradient_end_percent",
    "ELUTE_GRADIENT_GRADIENT_START": "elute_gradient_start_percent",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "linked_process_id": {
            "type": "string",
            "description": "Linked process identifier from eLabFTW (do not modify).",
        },
        "cip_high_salt_duration_s": {
            "type": "number",
            "description": "CIP High Salt phase duration.",
            "unit": "s",
        },
        "wash_duration_s": {
            "type": "number",
            "description": "Wash phase duration.",
            "unit": "s",
        },
        "cip_h2o1_duration_s": {
            "type": "number",
            "description": "CIP H2O 1 phase duration.",
            "unit": "s",
        },
        "cip_hcl_duration_s": {
            "type": "number",
            "description": "CIP HCl phase duration.",
            "unit": "s",
        },
        "cip_h2o2_duration_s": {
            "type": "number",
            "description": "CIP H2O 2 phase duration.",
            "unit": "s",
        },
        "wash_flow_rate_ml_min": {
            "type": "number",
            "description": "Wash phase flow rate.",
            "unit": "mL/min",
        },
        "cip_naoh_hold_duration_s": {
            "type": "number",
            "description": "CIP NaOH hold duration.",
            "unit": "s",
        },
        "load_inject_duration_s": {
            "type": "number",
            "description": "Load/Inject phase duration.",
            "unit": "s",
        },
        "load_inject_flow_rate_ml_min": {
            "type": "number",
            "description": "Load/Inject phase flow rate.",
            "unit": "mL/min",
        },
        "equilibration_duration_s": {
            "type": "number",
            "description": "Equilibration phase duration.",
            "unit": "s",
        },
        "elute_gradient_duration_s": {
            "type": "number",
            "description": "Elution gradient phase duration.",
            "unit": "s",
        },
        "equilibration_flow_rate_ml_min": {
            "type": "number",
            "description": "Equilibration phase flow rate.",
            "unit": "mL/min",
        },
        "elute_gradient_end_percent": {
            "type": "number",
            "description": "Elution gradient end composition.",
            "unit": "%",
        },
        "elute_gradient_start_percent": {
            "type": "number",
            "description": "Elution gradient start composition.",
            "unit": "%",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "success", "failed"],
            "description": "Status of the AKTA chromatogram analysis.",
        },
        "analysis_timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when results were committed to the database (UTC).",
        },
        "summary": {
            "type": "object",
            "description": "Key metrics from AKTA chromatogram analysis.",
            "properties": {
                "num_peaks": {
                    "type": "integer",
                    "description": "Number of peaks detected in the UV trace.",
                },
                "files_processed": {
                    "type": "integer",
                    "description": "Number of data output files generated by the analysis script.",
                },
            },
        },
        "peaks": {
            "type": "array",
            "description": "List of detected peaks with retention times and heights.",
            "items": {
                "type": "object",
                "properties": {
                    "index": {
                        "type": "integer",
                        "description": "Index of the peak in the time-series array.",
                    },
                    "time_min": {
                        "type": "number",
                        "description": "Retention time of the peak.",
                        "unit": "min",
                    },
                    "height": {
                        "type": "number",
                        "description": "Peak height in UV absorbance.",
                        "unit": "mAU",
                    },
                },
            },
        },
        "data_files": {
            "type": "object",
            "description": "Output data file paths from the AKTA analysis script.",
            "properties": {
                "analysis_results_json": {
                    "type": "string",
                    "description": "Path to the main analysis results JSON file.",
                },
                "timeseries_csv": {
                    "type": "string",
                    "description": "Path to the exported AKTA time-series CSV file.",
                },
                "peaks_csv": {
                    "type": ["string", "null"],
                    "description": "Path to the exported detected peaks CSV file (if any).",
                },
            },
        },
        "plots": {
            "type": "object",
            "description": "Plot file paths generated by the AKTA analysis script.",
            "properties": {
                "chromatogram_png": {
                    "type": ["string", "null"],
                    "description": "Path to the chromatogram PNG plot.",
                },
                "chromatogram_pdf": {
                    "type": ["string", "null"],
                    "description": "Path to the chromatogram PDF plot.",
                },
            },
        },
        "raw_analysis_payload": {
            "type": "object",
            "description": "Raw analysis_results payload loaded from the analysis script's JSON output.",
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "analysis_results_{elab_id}.json",
        "akta_timeseries_{elab_id}.csv",
        "akta_peaks_{elab_id}.csv",
    ],
    "plots": [
        "chromatogram_{elab_id}.png",
        "chromatogram_{elab_id}.pdf",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        text = value.strip()
        import re

        match = re.search(r"[-+]?\d*\.?\d+", text.replace(",", "."))
        if match:
            try:
                return float(match.group())
            except ValueError:
                return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """
    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()
    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Check if this could be a decimal-comma single number like "1,5"
            if sep == "," and len(parts) == 2 and "".join(parts).replace(".", "", 1).isdigit():
                break
            # Try numeric list first
            try:
                return [float(p) for p in parts]
            except ValueError:
                return parts
    if field_type == "number":
        num = parse_numeric(text)
        return num if num is not None else text
    return text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path, encoding="utf-8") as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields."""
    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name in extra_fields:
            field = extra_fields[elab_name]
            value = field.get("value")
            field_type = field.get("type")
            parsed = parse_field(value, field_type=field_type)
            metadata[db_name] = parsed
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id):
    """Load the main analysis_results_<ID>.json produced by the analysis script.

    Returns the parsed JSON dict, or None if not found.
    """

    results_folder = Path("../results")
    analysis_json = results_folder / f"analysis_results_{elab_id}.json"
    if analysis_json.exists():
        try:
            with open(analysis_json, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as exc:  # pragma: no cover - defensive
            print(f"WARNING: Failed to read analysis results JSON {analysis_json}: {exc}")
            return None
    return None


def build_results(elab_id):
    """Build results JSONB structure from analysis outputs.

    This function mirrors the structure produced by the AKTA analysis script
    while flattening key metrics into top-level fields defined in RESULTS_SCHEMA.
    """

    results_folder = Path("../results")
    results_folder.mkdir(parents=True, exist_ok=True)

    analysis_payload = load_analysis_results(elab_id)

    timestamp = datetime.now(timezone.utc).isoformat()
    results = {
        "analysis_status": "pending",
        "analysis_timestamp": timestamp,
        "summary": {
            "num_peaks": None,
            "files_processed": None,
        },
        "peaks": [],
        "data_files": {
            "analysis_results_json": None,
            "timeseries_csv": None,
            "peaks_csv": None,
        },
        "plots": {
            "chromatogram_png": None,
            "chromatogram_pdf": None,
        },
        "raw_analysis_payload": analysis_payload or {},
    }

    if analysis_payload is None:
        # No analysis file found; keep status as pending
        return results

    # Map status
    status = analysis_payload.get("status")
    if status in {"success", "failed"}:
        results["analysis_status"] = status
    else:
        results["analysis_status"] = "failed" if status else "pending"

    # Summary metrics
    metadata = analysis_payload.get("metadata", {}) or {}
    num_peaks = metadata.get("num_peaks")
    if isinstance(num_peaks, int):
        results["summary"]["num_peaks"] = num_peaks
    else:
        # Fallback: infer from peaks list if present
        peaks_list = analysis_payload.get("peaks") or []
        if isinstance(peaks_list, list):
            results["summary"]["num_peaks"] = len(peaks_list)

    files_processed = analysis_payload.get("files_processed")
    if isinstance(files_processed, int):
        results["summary"]["files_processed"] = files_processed

    # Peaks list
    peaks = analysis_payload.get("peaks")
    if isinstance(peaks, list):
        cleaned_peaks = []
        for p in peaks:
            if not isinstance(p, dict):
                continue
            cleaned_peaks.append(
                {
                    "index": int(p.get("index")) if p.get("index") is not None else None,
                    "time_min": float(p.get("time_min")) if p.get("time_min") is not None else None,
                    "height": float(p.get("height")) if p.get("height") is not None else None,
                }
            )
        results["peaks"] = cleaned_peaks

    # Data files
    data_outputs = analysis_payload.get("data_outputs", {}) or {}
    ar_json_path = results_folder / f"analysis_results_{elab_id}.json"
    if ar_json_path.exists():
        results["data_files"]["analysis_results_json"] = str(ar_json_path.resolve())

    ts_csv = data_outputs.get("timeseries_csv")
    if isinstance(ts_csv, str):
        results["data_files"]["timeseries_csv"] = ts_csv
    else:
        ts_path = results_folder / f"akta_timeseries_{elab_id}.csv"
        if ts_path.exists():
            results["data_files"]["timeseries_csv"] = str(ts_path.resolve())

    peaks_csv = data_outputs.get("peaks_csv")
    if isinstance(peaks_csv, str):
        results["data_files"]["peaks_csv"] = peaks_csv
    else:
        pk_path = results_folder / f"akta_peaks_{elab_id}.csv"
        if pk_path.exists():
            results["data_files"]["peaks_csv"] = str(pk_path.resolve())

    # Plots
    plots = analysis_payload.get("plots", {}) or {}
    chrom = plots.get("chromatogram") or {}
    png_path = chrom.get("png")
    pdf_path = chrom.get("pdf")

    if isinstance(png_path, str):
        results["plots"]["chromatogram_png"] = png_path
    else:
        fallback_png = results_folder / f"chromatogram_{elab_id}.png"
        if fallback_png.exists():
            results["plots"]["chromatogram_png"] = str(fallback_png.resolve())

    if isinstance(pdf_path, str):
        results["plots"]["chromatogram_pdf"] = pdf_path
    else:
        fallback_pdf = results_folder / f"chromatogram_{elab_id}.pdf"
        if fallback_pdf.exists():
            results["plots"]["chromatogram_pdf"] = str(fallback_pdf.resolve())

    return results


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""
    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    return cursor.fetchone()[0]


def main():
    parser = argparse.ArgumentParser(description=f"Commit {PROCESS_NAME} to database")
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument("--dry-run", action="store_true", help="Don't commit, just show what would be done")
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path, encoding="utf-8") as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {})
        workflow_json, lab_id = load_workflow()

        # Build data structures
        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": "completed",
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": extract_metadata(extra_fields),
            "raw_data": build_raw_data(args.elab_id),
            "results": build_results(args.elab_id),
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})")
        return 0

    except Exception as e:  # pragma: no cover - CLI error path
        print(f"Error: {e}", file=sys.stderr)
        if "conn" in locals():
            conn.rollback()
        return 1
    finally:
        if "conn" in locals():
            conn.close()


if __name__ == "__main__":
    sys.exit(main())