#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

# Mapping from eLabFTW Extra Fields to internal snake_case names
FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_id_elab",
    "Pump Speed": "pump_speed",
    "Replicates": "replicates",
    "Resin Mass": "resin_mass_mg",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume_ul",
    "Venting time": "venting_time_s",
    "Pump Duration": "pump_duration_s",
    "Incubation Time": "incubation_time_min",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume_ul",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature_c",
    "Measurement Wavelength": "measurement_wavelength_nm",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation_rpm",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration_s",
    "Number of salt concentrations": "number_of_salt_concentrations",
    "Number of ligand concentrations": "number_of_ligand_concentrations",
}

# JSON Schema describing input parameters (metadata)
METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Buffer solution used for equilibration and incubation.",
        },
        "salt_name": {
            "type": "string",
            "description": "Name or identity of the salt used in the isotherm experiment.",
        },
        "process_id_elab": {
            "type": "string",
            "description": "Process identifier as stored in eLabFTW metadata.",
        },
        "pump_speed": {
            "type": "number",
            "description": "Pump speed during loading / equilibration.",
            "unit": "arbitrary units",
        },
        "replicates": {
            "type": "integer",
            "description": "Number of replicate wells per condition.",
        },
        "resin_mass_mg": {
            "type": "number",
            "description": "Mass of resin used in each well.",
            "unit": "mg",
        },
        "ligand_name": {
            "type": "string",
            "description": "Name or identity of the ligand/protein.",
        },
        "total_volume_ul": {
            "type": "number",
            "description": "Total liquid volume per well.",
            "unit": "uL",
        },
        "venting_time_s": {
            "type": "number",
            "description": "Time for venting / pressure equilibration.",
            "unit": "s",
        },
        "pump_duration_s": {
            "type": "number",
            "description": "Duration for which the pump is running during loading/equilibration.",
            "unit": "s",
        },
        "incubation_time_min": {
            "type": "number",
            "description": "Incubation time for binding equilibrium to be reached.",
            "unit": "min",
        },
        "salt_concentrations": {
            "type": "array",
            "description": "List of salt concentrations used in the experiment.",
            "items": {"type": "number"},
        },
        "equilibration_cycles": {
            "type": "integer",
            "description": "Number of equilibration cycles used prior to loading.",
        },
        "equilibration_volume_ul": {
            "type": "number",
            "description": "Volume used per equilibration cycle.",
            "unit": "uL",
        },
        "ligand_concentrations": {
            "type": "array",
            "description": "List of initial ligand concentrations for the loading isotherm.",
            "items": {"type": "number"},
        },
        "incubation_temperature_c": {
            "type": "number",
            "description": "Incubation temperature during binding.",
            "unit": "degC",
        },
        "measurement_wavelength_nm": {
            "type": "number",
            "description": "Measurement wavelength for plate reader.",
            "unit": "nm",
        },
        "calibration_curve_slope": {
            "type": "number",
            "description": "Slope of calibration curve used to convert absorbance to concentration.",
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit of salt concentrations (e.g. mM).",
        },
        "shaker_speed_incubation_rpm": {
            "type": "number",
            "description": "Shaker speed during incubation.",
            "unit": "rpm",
        },
        "salt_stock_concentration": {
            "type": "number",
            "description": "Concentration of the salt stock solution.",
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit of ligand concentrations (e.g. uM, mg/mL).",
        },
        "ligand_stock_concentration": {
            "type": "number",
            "description": "Concentration of the ligand stock solution.",
        },
        "calibration_curve_intercept": {
            "type": "number",
            "description": "Intercept of calibration curve used to convert absorbance to concentration.",
        },
        "equilibration_cycle_duration_s": {
            "type": "number",
            "description": "Duration of each equilibration cycle.",
            "unit": "s",
        },
        "number_of_salt_concentrations": {
            "type": "integer",
            "description": "Number of distinct salt concentrations used.",
        },
        "number_of_ligand_concentrations": {
            "type": "integer",
            "description": "Number of distinct ligand concentrations used.",
        },
    },
}

# JSON Schema describing analysis results
RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "success", "failed"],
            "description": "Status of the analysis run reported by the analysis script.",
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when results were committed to the database.",
        },
        "summary": {
            "type": "object",
            "description": "High-level metrics aggregated from analysis results.",
            "properties": {
                "files_processed": {
                    "type": "integer",
                    "description": "Number of raw data files processed by the analysis script.",
                },
                "n_ligand": {
                    "type": "integer",
                    "description": "Number of ligand concentration levels.",
                },
                "n_salt": {
                    "type": "integer",
                    "description": "Number of salt concentration levels.",
                },
                "n_replicates": {
                    "type": "integer",
                    "description": "Number of replicates per condition (if available).",
                },
                "n_langmuir_fits": {
                    "type": "integer",
                    "description": "Number of successful Langmuir fits.",
                },
            },
        },
        "langmuir_fits": {
            "type": "array",
            "description": "Per-salt Langmuir fit parameters.",
            "items": {
                "type": "object",
                "properties": {
                    "salt_index": {"type": "integer"},
                    "salt_concentration": {"type": "number"},
                    "q_max": {"type": "number"},
                    "K": {"type": "number"},
                    "R2": {"type": "number"},
                },
            },
        },
        "data_files": {
            "type": "object",
            "description": "Output data files generated by the analysis script.",
            "properties": {
                "analysis_results_json": {"type": "string"},
                "wells_processed_csv": {"type": "string"},
                "aggregated_isotherm_csv": {"type": "string"},
                "langmuir_fits_csv": {"type": "string"},
                "tecan_raw_excel": {"type": "string"},
            },
        },
        "plots": {
            "type": "object",
            "description": "Plot files generated by the analysis script.",
            "properties": {
                "loading_isotherms_png": {"type": "string"},
            },
        },
        "warnings": {
            "type": "array",
            "description": "Warnings reported by the analysis script.",
            "items": {"type": "string"},
        },
        "raw_analysis": {
            "type": "object",
            "description": "Raw analysis JSON loaded from analysis_results_*.json.",
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "analysis_results_{elab_id}.json",
        "wells_processed_{elab_id}.csv",
        "aggregated_isotherm_{elab_id}.csv",
        "langmuir_fits_{elab_id}.csv",
        "tecan_data_{elab_id}.xlsx",
    ],
    "plots": [
        "loading_isotherms_{elab_id}.png",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        text = value.strip()
        if text == "":
            return None
        import re

        match = re.search(r"[-+]?\d*\.?\d+", text.replace(",", "."))
        if match:
            try:
                return float(match.group())
            except ValueError:
                return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """

    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()
    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Try to interpret as list of floats (allow decimal comma)
            all_numeric = True
            floats = []
            for p in parts:
                p_norm = p.replace(",", ".")
                try:
                    floats.append(float(p_norm))
                except ValueError:
                    all_numeric = False
                    break
            if all_numeric:
                return floats
            return parts
    if field_type == "number":
        num = parse_numeric(text)
        return num if num is not None else text
    return text  # text stays text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields.

    Applies FIELD_MAPPING and respects field types and potential list values.
    """
    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name not in extra_fields:
            continue
        field = extra_fields[elab_name]
        value = field.get("value")
        field_type = field.get("type")
        parsed = parse_field(value, field_type=field_type)
        metadata[db_name] = parsed
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id):
    """Load analysis_results_{elab_id}.json if present.

    Returns tuple (analysis_json, path_str or None).
    """
    results_folder = Path("../results")
    analysis_path = results_folder / f"analysis_results_{elab_id}.json"
    if analysis_path.exists():
        try:
            with open(analysis_path, "r") as f:
                return json.load(f), str(analysis_path.resolve())
        except Exception:
            return None, None
    return None, None


def build_results(elab_id):
    """Build results JSONB structure by inspecting ../results and ../analysis.

    This function is generic but tailored to the outputs of the provided analysis
    script (loading isotherm evaluation).
    """

    results = {
        "analysis_status": "pending",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "summary": {},
        "langmuir_fits": [],
        "data_files": {},
        "plots": {},
        "warnings": [],
        "raw_analysis": {},
    }

    # Load analysis JSON if available
    analysis_json, analysis_path = load_analysis_results(elab_id)
    if analysis_json is not None:
        status = analysis_json.get("status", "pending")
        results["analysis_status"] = status
        results["raw_analysis"] = analysis_json
        if analysis_path:
            results["data_files"]["analysis_results_json"] = analysis_path

        # Summary fields
        meta = analysis_json.get("metadata", {}) or {}
        results["summary"]["files_processed"] = int(
            analysis_json.get("files_processed", 0) or 0
        )
        if "n_ligand" in meta:
            try:
                results["summary"]["n_ligand"] = int(meta.get("n_ligand"))
            except Exception:
                pass
        if "n_salt" in meta:
            try:
                results["summary"]["n_salt"] = int(meta.get("n_salt"))
            except Exception:
                pass
        if "n_replicates" in meta:
            try:
                results["summary"]["n_replicates"] = int(meta.get("n_replicates"))
            except Exception:
                pass

        # Warnings
        if isinstance(analysis_json.get("warnings"), list):
            results["warnings"] = analysis_json.get("warnings", [])

        # Data outputs and plots from analysis JSON
        data_outputs = analysis_json.get("data_outputs", {}) or {}
        plots = analysis_json.get("plots", {}) or {}

        for key, path in data_outputs.items():
            results["data_files"][key] = path
        for key, path in plots.items():
            results["plots"][key] = path

        # Try to load Langmuir fits CSV into a simplified structure if present
        langmuir_csv = data_outputs.get("langmuir_fits_csv")
        if langmuir_csv and Path(langmuir_csv).exists():
            try:
                import csv

                with open(langmuir_csv, newline="") as f:
                    reader = csv.DictReader(f)
                    for row in reader:
                        try:
                            results["langmuir_fits"].append(
                                {
                                    "salt_index": int(row.get("salt_index"))
                                    if row.get("salt_index") not in (None, "")
                                    else None,
                                    "salt_concentration": float(row.get("salt_concentration"))
                                    if row.get("salt_concentration") not in (None, "")
                                    else None,
                                    "q_max": float(row.get("q_max"))
                                    if row.get("q_max") not in (None, "")
                                    else None,
                                    "K": float(row.get("K"))
                                    if row.get("K") not in (None, "")
                                    else None,
                                    "R2": float(row.get("R2"))
                                    if row.get("R2") not in (None, "")
                                    else None,
                                }
                            )
                        except Exception:
                            continue
            except Exception:
                # If reading CSV fails, just omit structured langmuir_fits; raw CSV path is kept
                pass

        results["summary"]["n_langmuir_fits"] = len(results["langmuir_fits"])

    # Also scan results/ and analysis/ directories to list files (best-effort)
    results_folder = Path("../results")
    analysis_folder = Path("../analysis")

    if results_folder.exists():
        for f in results_folder.iterdir():
            if not f.is_file():
                continue
            name = f.name
            if name.endswith(".png") and "loading_isotherms" in name:
                results["plots"].setdefault("loading_isotherms_png", str(f.resolve()))
            elif name.endswith(f"wells_processed_{elab_id}.csv"):
                results["data_files"].setdefault("wells_processed_csv", str(f.resolve()))
            elif name.endswith(f"aggregated_isotherm_{elab_id}.csv"):
                results["data_files"].setdefault(
                    "aggregated_isotherm_csv", str(f.resolve())
                )
            elif name.endswith(f"langmuir_fits_{elab_id}.csv"):
                results["data_files"].setdefault("langmuir_fits_csv", str(f.resolve()))
            elif name.endswith(f"analysis_results_{elab_id}.json"):
                results["data_files"].setdefault("analysis_results_json", str(f.resolve()))
            elif name.endswith(f"tecan_data_{elab_id}.xlsx"):
                results["data_files"].setdefault("tecan_raw_excel", str(f.resolve()))

    if analysis_folder.exists():
        for f in analysis_folder.iterdir():
            if f.is_file():
                results.setdefault("additional_files", []).append(str(f.resolve()))

    return results


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""
    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    return cursor.fetchone()[0]


def main():
    parser = argparse.ArgumentParser(
        description=f"Commit {PROCESS_NAME} to database"
    )
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {})
        workflow_json, lab_id = load_workflow()

        # Build data structures
        metadata = extract_metadata(extra_fields)
        raw_data = build_raw_data(args.elab_id)
        results = build_results(args.elab_id)

        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": "completed" if results.get("analysis_status") == "success" else "failed",
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": metadata,
            "raw_data": raw_data,
            "results": results,
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})")
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if "conn" in locals():
            conn.rollback()
        return 1
    finally:
        if "conn" in locals():
            conn.close()


if __name__ == "__main__":
    sys.exit(main())