#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_id_field",
    "Pump Speed": "pump_speed",
    "Replicates": "replicates",
    "Resin Mass": "resin_mass_mg",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume_ul",
    "Venting time": "venting_time_s",
    "Pump Duration": "pump_duration_s",
    "Incubation Time": "incubation_time_min",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume_ul",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature_c",
    "Measurement Wavelength": "measurement_wavelength_nm",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation_rpm",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration_s",
    "Number of salt concentrations": "num_salt_concentrations",
    "Number of ligand concentrations": "num_ligand_concentrations",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Buffer solution used for the isotherm experiment",
        },
        "salt_name": {
            "type": "string",
            "description": "Name or identity of the salt used",
        },
        "process_id_field": {
            "type": "string",
            "description": "Process identifier as specified in eLabFTW metadata",
        },
        "pump_speed": {
            "type": "number",
            "description": "Pump speed used during loading and equilibration",
            "unit": "uL/min",
        },
        "replicates": {
            "type": "integer",
            "description": "Number of replicate wells per condition",
        },
        "resin_mass_mg": {
            "type": "number",
            "description": "Mass of resin in each well",
            "unit": "mg",
        },
        "ligand_name": {
            "type": "string",
            "description": "Name or identity of the ligand",
        },
        "total_volume_ul": {
            "type": "number",
            "description": "Total liquid volume per well used for loading",
            "unit": "uL",
        },
        "venting_time_s": {
            "type": "number",
            "description": "Venting time per equilibration or loading step",
            "unit": "s",
        },
        "pump_duration_s": {
            "type": "number",
            "description": "Pump duration per step",
            "unit": "s",
        },
        "incubation_time_min": {
            "type": "number",
            "description": "Incubation time for loading isotherm",
            "unit": "min",
        },
        "salt_concentrations": {
            "type": "array",
            "description": "List of salt concentrations used in the isotherm (parsed from semicolon- or comma-separated values when numeric)",
            "items": {"type": "number"},
        },
        "equilibration_cycles": {
            "type": "integer",
            "description": "Number of equilibration cycles before measurement",
        },
        "equilibration_volume_ul": {
            "type": "number",
            "description": "Volume used per equilibration cycle",
            "unit": "uL",
        },
        "ligand_concentrations": {
            "type": "array",
            "description": "List of ligand concentrations used in the isotherm (parsed from semicolon- or comma-separated values when numeric)",
            "items": {"type": "number"},
        },
        "incubation_temperature_c": {
            "type": "number",
            "description": "Incubation temperature during loading isotherm",
            "unit": "degC",
        },
        "measurement_wavelength_nm": {
            "type": "number",
            "description": "Measurement wavelength of the plate reader",
            "unit": "nm",
        },
        "calibration_curve_slope": {
            "type": "number",
            "description": "Slope of the calibration curve for converting absorbance to concentration",
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit of salt concentrations (e.g. mM)",
        },
        "shaker_speed_incubation_rpm": {
            "type": "number",
            "description": "Shaker speed during incubation",
            "unit": "rpm",
        },
        "salt_stock_concentration": {
            "type": "number",
            "description": "Concentration of the salt stock solution",
            "unit": "same as salt_concentration_unit",
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit of ligand concentrations (e.g. uM, mM)",
        },
        "ligand_stock_concentration": {
            "type": "number",
            "description": "Concentration of the ligand stock solution",
            "unit": "same as ligand_concentration_unit",
        },
        "calibration_curve_intercept": {
            "type": "number",
            "description": "Intercept of the calibration curve",
        },
        "equilibration_cycle_duration_s": {
            "type": "number",
            "description": "Duration of a single equilibration cycle",
            "unit": "s",
        },
        "num_salt_concentrations": {
            "type": "integer",
            "description": "Number of distinct salt concentrations in the plate",
        },
        "num_ligand_concentrations": {
            "type": "integer",
            "description": "Number of distinct ligand concentrations in the plate",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "success", "failed"],
            "description": "Status of the plate reader loading isotherm analysis",
        },
        "analysis_message": {
            "type": "string",
            "description": "Human-readable message about the analysis outcome",
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "UTC timestamp when results were committed to the database",
        },
        "metadata": {
            "type": "object",
            "description": "Key metadata extracted and reused from the analysis output",
            "properties": {
                "num_ligand_conc": {"type": "integer"},
                "num_salt_conc": {"type": "integer"},
                "replicates": {"type": "integer"},
                "ligand_concs": {"type": "array", "items": {"type": "number"}},
                "salt_concs": {"type": "array", "items": {"type": "number"}},
                "calib_slope": {"type": "number"},
                "calib_intercept": {"type": "number"},
                "resin_mass_mg": {"type": "number"},
                "total_volume_ul": {"type": "number"},
                "ligand_unit": {"type": "string"},
                "salt_unit": {"type": "string"},
            },
        },
        "summary": {
            "type": "object",
            "description": "Summary metrics from Langmuir fits across salt concentrations",
            "properties": {
                "num_salt_conditions": {
                    "type": "integer",
                    "description": "Number of salt conditions with fit parameters",
                },
                "q_max_mean": {
                    "type": "number",
                    "description": "Mean q_max across salt conditions (excluding NaN)",
                },
                "q_max_std": {
                    "type": "number",
                    "description": "Standard deviation of q_max across salt conditions",
                },
                "K_mean": {
                    "type": "number",
                    "description": "Mean Langmuir binding constant K across salt conditions",
                },
                "K_std": {
                    "type": "number",
                    "description": "Standard deviation of K across salt conditions",
                },
                "r2_mean": {
                    "type": "number",
                    "description": "Mean coefficient of determination R^2 across salt conditions",
                },
                "r2_min": {
                    "type": "number",
                    "description": "Minimum R^2 across salt conditions",
                },
            },
        },
        "data_files": {
            "type": "object",
            "description": "Paths to main data output files from the analysis script",
            "properties": {
                "analysis_results_json": {"type": "string"},
                "tecan_raw_file": {"type": "string"},
                "per_well_csv": {"type": "string"},
                "aggregated_csv": {"type": "string"},
                "langmuir_fit_params": {"type": "string"},
            },
        },
        "plots": {
            "type": "object",
            "description": "Paths to generated plots",
            "properties": {
                "isotherms_png": {"type": "string"},
            },
        },
        "warnings": {
            "type": "array",
            "description": "List of warnings propagated from the analysis script, if any",
            "items": {"type": "string"},
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "analysis_results_{elab_id}.json",
        "tecan_data_{elab_id}.xlsx",
        "per_well_results_{elab_id}.csv",
        "aggregated_isotherm_data_{elab_id}.csv",
        "langmuir_fit_params_{elab_id}.json",
    ],
    "plots": [
        "loading_isotherms_{elab_id}.png",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value: str):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    text = str(value).strip()
    if text == "":
        return None
    import re

    # Replace comma decimal separator with dot, but keep other commas for now
    # Here we only expect a single numeric token.
    text_norm = text.replace(",", ".")
    match = re.search(r"[-+]?\d*\.?\d+", text_norm)
    if match:
        try:
            return float(match.group(0))
        except ValueError:
            return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """

    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value

    text = str(value).strip()

    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Check if this could actually be a single number written with decimal comma
            if sep == "," and len(parts) == 2:
                # Try joining with a dot as decimal separator
                candidate = parts[0] + "." + parts[1]
                try:
                    return float(candidate)
                except ValueError:
                    # Fall back to treating as list
                    pass
            # Try to parse all parts as floats
            try:
                return [float(p.replace(",", ".")) for p in parts]
            except ValueError:
                return parts

    if field_type == "number":
        num = parse_numeric(text)
        return num if num is not None else text

    return text  # text stays text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""

    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""

    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields.

    Applies FIELD_MAPPING and uses parse_field with eLabFTW field type information
    to preserve lists and numeric values appropriately.
    """

    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name in extra_fields:
            field = extra_fields[elab_name]
            value = field.get("value")
            field_type = field.get("type")
            parsed = parse_field(value, field_type=field_type)
            metadata[db_name] = parsed
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""

    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""

    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def _load_analysis_results(elab_id):
    """Load analysis_results_{elab_id}.json from ../results if present."""

    results_folder = Path("../results")
    analysis_json = results_folder / f"analysis_results_{elab_id}.json"
    if analysis_json.exists():
        try:
            with open(analysis_json, "r") as f:
                return json.load(f), str(analysis_json.resolve())
        except Exception:
            return None, None
    return None, None


def build_results(elab_id):
    """Build results JSONB structure.

    Attempts to load the analysis_results_{elab_id}.json produced by the analysis
    script. If present, extracts key metrics, data file paths, and plots. If not
    present, falls back to a minimal structure with file listings only.
    """

    results_folder = Path("../results")
    analysis_data, analysis_json_path = _load_analysis_results(elab_id)

    # Common timestamp
    ts = datetime.now(timezone.utc).isoformat()

    if analysis_data is not None:
        status = analysis_data.get("status", "failed")
        message = analysis_data.get("message", "")
        meta = analysis_data.get("metadata", {}) or {}

        # Fit parameters summary if available
        summary = None
        fit_params_path = results_folder / f"langmuir_fit_params_{elab_id}.json"
        if fit_params_path.exists():
            try:
                with open(fit_params_path, "r") as f:
                    fit_params = json.load(f)
                q_max_list = []
                K_list = []
                r2_list = []
                for _, params in fit_params.items():
                    try:
                        qv = float(params.get("q_max"))
                        Kv = float(params.get("K"))
                        r2v = float(params.get("r2"))
                    except (TypeError, ValueError):
                        continue
                    # NaN check via comparison to itself
                    if not (qv != qv or Kv != Kv or r2v != r2v):
                        q_max_list.append(qv)
                        K_list.append(Kv)
                        r2_list.append(r2v)

                def _mean_std(vals):
                    if not vals:
                        return None, None
                    m = sum(vals) / len(vals)
                    if len(vals) > 1:
                        var = sum((v - m) ** 2 for v in vals) / (len(vals) - 1)
                        return m, var ** 0.5
                    return m, 0.0

                q_mean, q_std = _mean_std(q_max_list)
                K_mean, K_std = _mean_std(K_list)
                r2_mean, _ = _mean_std(r2_list)
                r2_min = min(r2_list) if r2_list else None
                summary = {
                    "num_salt_conditions": len(q_max_list),
                    "q_max_mean": q_mean,
                    "q_max_std": q_std,
                    "K_mean": K_mean,
                    "K_std": K_std,
                    "r2_mean": r2_mean,
                    "r2_min": r2_min,
                }
            except Exception:
                summary = None
        results = {
            "analysis_status": status,
            "analysis_message": message,
            "timestamp": ts,
            "metadata": {
                "num_ligand_conc": meta.get("num_ligand_conc"),
                "num_salt_conc": meta.get("num_salt_conc"),
                "replicates": meta.get("replicates"),
                "ligand_concs": meta.get("ligand_concs"),
                "salt_concs": meta.get("salt_concs"),
                "calib_slope": meta.get("calib_slope"),
                "calib_intercept": meta.get("calib_intercept"),
                "resin_mass_mg": meta.get("resin_mass_mg"),
                "total_volume_ul": meta.get("total_volume_ul"),
                "ligand_unit": meta.get("ligand_unit"),
                "salt_unit": meta.get("salt_unit"),
            },
            "summary": summary,
            "data_files": {
                "analysis_results_json": analysis_json_path,
                "tecan_raw_file": (analysis_data.get("data_outputs", {}) or {}).get(
                    "tecan_raw_file"
                ),
                "per_well_csv": (analysis_data.get("data_outputs", {}) or {}).get(
                    "per_well_csv"
                ),
                "aggregated_csv": (analysis_data.get("data_outputs", {}) or {}).get(
                    "aggregated_csv"
                ),
                "langmuir_fit_params": (analysis_data.get("data_outputs", {}) or {}).get(
                    "langmuir_fit_params"
                ),
            },
            "plots": {
                "isotherms_png": (analysis_data.get("plots", {}) or {}).get(
                    "isotherms_png"
                ),
            },
            "warnings": analysis_data.get("warnings", []) or [],
        }
        return results

    # Fallback if no analysis JSON exists
    return {
        "analysis_status": "pending",
        "analysis_message": "Analysis results JSON not found; only file listings stored.",
        "timestamp": ts,
        "metadata": {},
        "summary": None,
        "data_files": {},
        "plots": {},
        "warnings": [],
    }


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""

    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""

    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    return cursor.fetchone()[0]


def main():
    parser = argparse.ArgumentParser(
        description=f"Commit {PROCESS_NAME} to database"
    )
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get(
            "extra_fields", {}
        )
        workflow_json, lab_id = load_workflow()

        # Build data structures
        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": "completed",
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": extract_metadata(extra_fields),
            "raw_data": build_raw_data(args.elab_id),
            "results": build_results(args.elab_id),
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(
            f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})"
        )
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if "conn" in locals():
            conn.rollback()
        return 1
    finally:
        if "conn" in locals():
            conn.close()


if __name__ == "__main__":
    sys.exit(main())