#!/usr/bin/env python3
"""
Database commit script for AKTA - Gradient Elution (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 36
PROCESS_NAME = "AKTA - Gradient Elution (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Process ID": "linked_process_id",
    "CIP_DURATION": "cip_high_salt_duration_s",
    "WASH_DURATION": "wash_duration_s",
    "CIP_3_DURATION": "cip_h2o1_duration_s",
    "CIP_4_DURATION": "cip_hcl_duration_s",
    "CIP_5_DURATION": "cip_h2o2_duration_s",
    "WASH_FLOW_RATE": "wash_flow_rate_ml_min",
    "CIP_2_HOLD_DURATION": "cip_naoh_hold_duration_s",
    "LOAD_INJECT_DURATION": "load_inject_duration_s",
    "LOAD_INJECT_FLOW_RATE": "load_inject_flow_rate_ml_min",
    "EQUILIBRATION_DURATION": "equilibration_duration_s",
    "ELUTE_GRADIENT_DURATION": "elute_gradient_duration_s",
    "EQUILIBRATION_FLOW_RATE": "equilibration_flow_rate_ml_min",
    "ELUTE_GRADIENT_GRADIENT_END": "elute_gradient_gradient_end_percent",
    "ELUTE_GRADIENT_GRADIENT_START": "elute_gradient_gradient_start_percent",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "linked_process_id": {
            "type": "string",
            "description": "Identifier of the linked upstream or parent process (do not modify).",
        },
        "cip_high_salt_duration_s": {
            "type": "number",
            "description": "CIP High Salt phase duration.",
            "unit": "s",
        },
        "wash_duration_s": {
            "type": "number",
            "description": "Wash phase duration.",
            "unit": "s",
        },
        "cip_h2o1_duration_s": {
            "type": "number",
            "description": "CIP H2O 1 phase duration.",
            "unit": "s",
        },
        "cip_hcl_duration_s": {
            "type": "number",
            "description": "CIP HCl phase duration.",
            "unit": "s",
        },
        "cip_h2o2_duration_s": {
            "type": "number",
            "description": "CIP H2O 2 phase duration.",
            "unit": "s",
        },
        "wash_flow_rate_ml_min": {
            "type": "number",
            "description": "Wash phase flow rate.",
            "unit": "mL/min",
        },
        "cip_naoh_hold_duration_s": {
            "type": "number",
            "description": "CIP NaOH hold duration.",
            "unit": "s",
        },
        "load_inject_duration_s": {
            "type": "number",
            "description": "Load / Inject phase duration.",
            "unit": "s",
        },
        "load_inject_flow_rate_ml_min": {
            "type": "number",
            "description": "Load / Inject phase flow rate.",
            "unit": "mL/min",
        },
        "equilibration_duration_s": {
            "type": "number",
            "description": "Equilibration phase duration.",
            "unit": "s",
        },
        "elute_gradient_duration_s": {
            "type": "number",
            "description": "Elution gradient phase duration.",
            "unit": "s",
        },
        "equilibration_flow_rate_ml_min": {
            "type": "number",
            "description": "Equilibration phase flow rate.",
            "unit": "mL/min",
        },
        "elute_gradient_gradient_end_percent": {
            "type": "number",
            "description": "Elution gradient end percentage.",
            "unit": "%",
        },
        "elute_gradient_gradient_start_percent": {
            "type": "number",
            "description": "Elution gradient start percentage.",
            "unit": "%",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "completed", "failed"],
            "description": "Status of the AKTA chromatography analysis.",
        },
        "analysis_timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when the analysis summary was generated.",
        },
        "summary": {
            "type": "object",
            "description": "Summary metrics from AKTA chromatogram analysis.",
            "properties": {
                "n_peaks": {
                    "type": "integer",
                    "description": "Number of UV peaks detected in the chromatogram.",
                },
                "first_peak_time_min": {
                    "type": "number",
                    "description": "Retention time of the first detected peak (minutes).",
                    "unit": "min",
                },
                "last_peak_time_min": {
                    "type": "number",
                    "description": "Retention time of the last detected peak (minutes).",
                    "unit": "min",
                },
                "max_peak_height": {
                    "type": "number",
                    "description": "Maximum UV peak height detected (as reported by analysis).",
                },
            },
        },
        "peaks": {
            "type": "array",
            "description": "List of detected peaks with retention time and height.",
            "items": {
                "type": "object",
                "properties": {
                    "index": {
                        "type": "integer",
                        "description": "Index of the peak in the time series.",
                    },
                    "time_s": {
                        "type": "number",
                        "description": "Peak retention time in seconds.",
                        "unit": "s",
                    },
                    "time_min": {
                        "type": "number",
                        "description": "Peak retention time in minutes (as used for plotting).",
                        "unit": "min",
                    },
                    "height": {
                        "type": "number",
                        "description": "Peak height in UV signal units.",
                    },
                },
            },
        },
        "data_files": {
            "type": "object",
            "description": "Output data file names from the analysis.",
            "properties": {
                "analysis_results_json": {
                    "type": "string",
                    "description": "Path to analysis_results_<elab_id>.json produced by akta_analysis.py.",
                },
                "processed_data_csv": {
                    "type": "string",
                    "description": "Path to akta_processed_data_<elab_id>.csv containing processed chromatogram data.",
                },
            },
        },
        "plots": {
            "type": "object",
            "description": "Plot files generated by the analysis.",
            "properties": {
                "chromatogram": {
                    "type": "string",
                    "description": "Path to akta_chromatogram_<elab_id>.png chromatogram plot.",
                },
            },
        },
        "raw_analysis": {
            "type": "object",
            "description": "Raw analysis JSON payload loaded from analysis_results_<elab_id>.json.",
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "akta_results_{elab_id}.json",
        "data_{elab_id}.csv",
        "akta_results_{elab_id}.csv",
    ],
    "plots": [
        "akta_chromatogram_{elab_id}.png",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value: str):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    text = str(value).strip()
    if text == "":
        return None

    import re

    # Replace comma decimal separator with dot if it looks like a single number
    if "," in text and ";" not in text:
        # if it matches a pattern like 1,23 or -1,0 treat as decimal comma
        if re.fullmatch(r"[-+]?\d{1,3},\d+", text.replace(" ", "")):
            text = text.replace(",", ".")

    match = re.search(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", text)
    if match:
        try:
            return float(match.group(0))
        except ValueError:
            return None
    return None


def parse_field(value, field_type: str | None = None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """

    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value

    text = str(value).strip()
    if text == "":
        return None

    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Check if this could actually be a decimal-comma single number -> then skip
            if sep == "," and len(parts) == 2:
                joined = "".join(parts)
                if joined.replace(".", "").replace(",", "").replace("+", "").replace("-", "").isdigit():
                    # looks like a single number with decimal comma, don't treat as list
                    break
            # Try to parse all parts as floats; if any fail, keep as strings
            nums = []
            all_numeric = True
            for p in parts:
                try:
                    nums.append(float(p))
                except ValueError:
                    all_numeric = False
                    break
            if all_numeric:
                return nums
            return parts

    # Not a list -> maybe numeric if field_type says so
    if field_type == "number":
        num = parse_numeric(text)
        return num if num is not None else text

    return text  # text stays text


def find_experiment_json(elab_id: int) -> Path:
    """Find experiment JSON file."""

    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""

    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            lab_id = data.get("lab_id") or data.get("labId")
            return data, lab_id
    return None, None


def extract_metadata(extra_fields: dict) -> dict:
    """Extract and map metadata from eLabFTW extra fields.

    Uses FIELD_MAPPING and respects field types and potential list values.
    """

    metadata: dict = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name not in extra_fields:
            continue
        field = extra_fields[elab_name]
        if not isinstance(field, dict):
            continue
        value = field.get("value")
        field_type = field.get("type")  # e.g. 'number', 'text', etc.
        parsed_value = parse_field(value, field_type=field_type)
        metadata[db_name] = parsed_value
    return metadata


def list_folder_files(folder_path: Path) -> list:
    """List files in a folder."""

    if folder_path.exists() and folder_path.is_dir():
        return [f.name for f in folder_path.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id: int) -> dict:
    """Build raw_data JSONB structure."""

    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id: int):
    """Load analysis_results_<ID>.json produced by akta_analysis.py if present."""

    results_folder = Path("../results")
    analysis_path = results_folder / f"analysis_results_{elab_id}.json"
    if analysis_path.exists():
        try:
            with open(analysis_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:  # defensive
            print(f"WARNING: Failed to load analysis results JSON: {e}")
            return None
    return None


def build_results(elab_id: int) -> dict:
    """Build results JSONB structure from analysis outputs.

    This function inspects the ../results/ folder and, if available, ingests the
    analysis_results_<ID>.json file generated by akta_analysis.py to populate
    summary metrics and peak information.
    """

    results_folder = Path("../results")
    results_folder_resolved = results_folder.resolve()

    analysis_payload = load_analysis_results(elab_id)

    # Default values
    analysis_status = "pending"
    summary: dict = {}
    peaks_list: list = []
    data_files: dict = {}
    plots: dict = {}

    if analysis_payload is not None:
        status_raw = analysis_payload.get("status")
        if status_raw == "success":
            analysis_status = "completed"
        elif status_raw:
            analysis_status = "failed"

        # Peaks and summary metrics
        peaks = analysis_payload.get("peaks") or []
        if isinstance(peaks, list):
            peaks_list = peaks
            n_peaks = len(peaks)
            summary["n_peaks"] = n_peaks
            if n_peaks > 0:
                try:
                    times_min = [p.get("time_min") for p in peaks if isinstance(p.get("time_min"), (int, float))]
                    if times_min:
                        summary["first_peak_time_min"] = float(min(times_min))
                        summary["last_peak_time_min"] = float(max(times_min))
                except Exception:
                    pass
                try:
                    heights = [p.get("height") for p in peaks if isinstance(p.get("height"), (int, float))]
                    if heights:
                        summary["max_peak_height"] = float(max(heights))
                except Exception:
                    pass

        # File paths from analysis payload
        data_outputs = analysis_payload.get("data_outputs", {}) or {}
        if isinstance(data_outputs, dict):
            if "processed_data_csv" in data_outputs:
                data_files["processed_data_csv"] = data_outputs["processed_data_csv"]

        plots_payload = analysis_payload.get("plots", {}) or {}
        if isinstance(plots_payload, dict):
            if "chromatogram" in plots_payload:
                plots["chromatogram"] = plots_payload["chromatogram"]

        # Explicit analysis_results JSON file path
        analysis_results_name = f"analysis_results_{elab_id}.json"
        if (results_folder / analysis_results_name).exists():
            data_files["analysis_results_json"] = str(results_folder_resolved / analysis_results_name)

    # If paths not found via payload, fall back to expected naming in results folder
    processed_csv_name = f"akta_processed_data_{elab_id}.csv"
    processed_csv_path = results_folder_resolved / processed_csv_name
    if "processed_data_csv" not in data_files and processed_csv_path.exists():
        data_files["processed_data_csv"] = str(processed_csv_path)

    plot_name = f"akta_chromatogram_{elab_id}.png"
    plot_path = results_folder_resolved / plot_name
    if "chromatogram" not in plots and plot_path.exists():
        plots["chromatogram"] = str(plot_path)

    results = {
        "analysis_status": analysis_status,
        "analysis_timestamp": datetime.now(timezone.utc).isoformat(),
        "summary": summary,
        "peaks": peaks_list,
        "data_files": data_files,
        "plots": plots,
        "raw_analysis": analysis_payload,
    }

    return results


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""

    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
        """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id: int, data: dict) -> int:
    """Insert or update experiment execution."""

    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
        """,
        (
            elab_id,
            data.get("title", ""),
            PROCESS_ID,
            PROCESS_NAME,
            data.get("lab_id"),
            data.get("status", "pending"),
            data.get("user"),
            json.dumps(data.get("workflow_json")) if data.get("workflow_json") is not None else None,
            json.dumps(data.get("metadata", {})),
            json.dumps(data.get("raw_data", {})),
            json.dumps(data.get("results", {})),
        ),
    )
    row = cursor.fetchone()
    return int(row[0])


def main() -> int:
    parser = argparse.ArgumentParser(description=f"Commit {PROCESS_NAME} to database")
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument("--dry-run", action="store_true", help="Don't commit, just show what would be done")
    parser.add_argument("--init-schema-only", action="store_true", help="Only initialize process schema")
    args = parser.parse_args()

    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path, "r", encoding="utf-8") as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {}) or {}
        workflow_json, lab_id = load_workflow()

        # Build data structures
        metadata = extract_metadata(extra_fields)
        raw_data = build_raw_data(args.elab_id)
        results = build_results(args.elab_id)

        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": results.get("analysis_status", "pending"),
            "user": exp_data.get("userid_human") or exp_data.get("owner") or "",
            "workflow_json": workflow_json,
            "metadata": metadata,
            "raw_data": raw_data,
            "results": results,
        }

        if args.dry_run:
            print("DRY RUN - Would insert the following payload:")
            print(json.dumps(data, indent=2, default=str))
            if conn is not None:
                conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})")
        return 0

    except Exception as e:  # top-level safety
        print(f"Error: {e}", file=sys.stderr)
        if conn is not None:
            conn.rollback()
        return 1
    finally:
        if conn is not None:
            conn.close()


if __name__ == "__main__":
    sys.exit(main())