#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_run_id",
    "Pump Speed": "pump_speed",
    "Replicates": "replicates",
    "Resin Mass": "resin_mass",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume",
    "Venting time": "venting_time",
    "Pump Duration": "pump_duration",
    "Incubation Time": "incubation_time",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature",
    "Measurement Wavelength": "measurement_wavelength",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration",
    "Number of salt concentrations": "num_salt_concentrations",
    "Number of ligand concentrations": "num_ligand_concentrations",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Buffer solution used during loading and equilibration."
        },
        "salt_name": {
            "type": "string",
            "description": "Name or identity of the salt used in the experiment."
        },
        "process_run_id": {
            "type": "string",
            "description": "Identifier of the automated process run (as recorded in eLabFTW)."
        },
        "pump_speed": {
            "type": ["number", "string"],
            "description": "Pump speed setting used during loading (as configured in automation).",
            "unit": "arbitrary units or mL/min as configured"
        },
        "replicates": {
            "type": ["integer", "string"],
            "description": "Number of replicate wells per condition on the plate."
        },
        "resin_mass": {
            "type": ["number", "string"],
            "description": "Total resin mass per well used for loading isotherm calculation.",
            "unit": "mg"
        },
        "ligand_name": {
            "type": "string",
            "description": "Name of the ligand or protein whose loading is measured."
        },
        "total_volume": {
            "type": ["number", "string"],
            "description": "Total liquid volume per well for the loading experiment.",
            "unit": "µL"
        },
        "venting_time": {
            "type": ["number", "string"],
            "description": "Time spent on venting during the automated process.",
            "unit": "s"
        },
        "pump_duration": {
            "type": ["number", "string"],
            "description": "Duration of pumping during loading.",
            "unit": "s"
        },
        "incubation_time": {
            "type": ["number", "string"],
            "description": "Total incubation time before measurement.",
            "unit": "min"
        },
        "salt_concentrations": {
            "type": ["array", "string"],
            "description": "Salt concentrations used in the experiment; may be a semicolon- or comma-separated list in eLabFTW.",
            "items": {"type": "number"},
            "unit": "as specified in salt_concentration_unit"
        },
        "equilibration_cycles": {
            "type": ["integer", "string"],
            "description": "Number of equilibration cycles before loading."
        },
        "equilibration_volume": {
            "type": ["number", "string"],
            "description": "Volume used in each equilibration step.",
            "unit": "µL"
        },
        "ligand_concentrations": {
            "type": ["array", "string"],
            "description": "Ligand concentrations used in the experiment; may be a semicolon- or comma-separated list in eLabFTW.",
            "items": {"type": "number"},
            "unit": "as specified in ligand_concentration_unit"
        },
        "incubation_temperature": {
            "type": ["number", "string"],
            "description": "Incubation temperature for the loading step.",
            "unit": "°C"
        },
        "measurement_wavelength": {
            "type": ["number", "string"],
            "description": "Measurement wavelength used on the Tecan plate reader.",
            "unit": "nm"
        },
        "calibration_curve_slope": {
            "type": ["number", "string"],
            "description": "Slope of the calibration curve relating absorbance to concentration.",
            "unit": "1/(concentration unit)"
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit for salt concentrations (e.g. mM)."
        },
        "shaker_speed_incubation": {
            "type": ["number", "string"],
            "description": "Shaker speed during incubation.",
            "unit": "rpm"
        },
        "salt_stock_concentration": {
            "type": ["number", "string"],
            "description": "Stock concentration of the salt solution used for dilutions.",
            "unit": "as specified"
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit for ligand concentrations (e.g. µM, mg/mL)."
        },
        "ligand_stock_concentration": {
            "type": ["number", "string"],
            "description": "Stock concentration of the ligand solution used for dilutions.",
            "unit": "as specified"
        },
        "calibration_curve_intercept": {
            "type": ["number", "string"],
            "description": "Intercept of the calibration curve relating absorbance to concentration.",
            "unit": "absorbance units"
        },
        "equilibration_cycle_duration": {
            "type": ["number", "string"],
            "description": "Duration of each equilibration cycle.",
            "unit": "s"
        },
        "num_salt_concentrations": {
            "type": ["integer", "string"],
            "description": "Number of distinct salt concentrations specified in the design."
        },
        "num_ligand_concentrations": {
            "type": ["integer", "string"],
            "description": "Number of distinct ligand concentrations specified in the design."
        }
    }
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["success", "failed"],
            "description": "Status of the loading isotherm analysis as reported by the analysis script."
        },
        "message": {
            "type": "string",
            "description": "Summary message from the analysis script."
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when results were committed to the database (UTC)."
        },
        "summary": {
            "type": "object",
            "description": "Key metrics aggregated from analysis outputs.",
            "properties": {
                "num_ligand_concentrations": {
                    "type": ["integer", "null"],
                    "description": "Number of ligand concentrations used (from analysis metadata)."
                },
                "num_salt_concentrations": {
                    "type": ["integer", "null"],
                    "description": "Number of salt concentrations used (from analysis metadata)."
                },
                "replicates": {
                    "type": ["integer", "null"],
                    "description": "Number of replicates per condition (from analysis metadata)."
                },
                "n_wells_processed": {
                    "type": ["integer", "null"],
                    "description": "Total number of wells successfully processed."
                },
                "n_conditions": {
                    "type": ["integer", "null"],
                    "description": "Number of unique (ligand, salt) conditions aggregated."
                }
            }
        },
        "data_files": {
            "type": "object",
            "description": "Output data file names from the analysis script.",
            "properties": {
                "raw_tecan_excel": {"type": "string"},
                "per_well_results_csv": {"type": "string"},
                "aggregated_results_csv": {"type": "string"},
                "langmuir_fit_results_csv": {"type": "string"},
                "analysis_results_json": {"type": "string"}
            },
            "additionalProperties": True
        },
        "plots": {
            "type": "object",
            "description": "Plot files generated by the analysis script.",
            "properties": {
                "isotherms_png": {"type": "string"},
                "isotherms_pdf": {"type": "string"}
            },
            "additionalProperties": True
        },
        "warnings": {
            "type": "array",
            "description": "Warnings generated during analysis, if available.",
            "items": {"type": "string"}
        },
        "raw_analysis": {
            "type": "object",
            "description": "Full JSON object loaded from analysis_results_<id>.json for traceability.",
            "additionalProperties": True
        },
        "result_folder_listing": {
            "type": "object",
            "description": "Listings of the results and analysis folders for debugging.",
            "properties": {
                "results_folder": {"type": "string"},
                "results_files": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "analysis_folder": {"type": "string"},
                "analysis_files": {
                    "type": "array",
                    "items": {"type": "string"}
                }
            },
            "additionalProperties": True
        }
    }
}

EXPECTED_FILES = {
    "data": [
        "tecan_data_{elab_id}.xlsx",
        "per_well_results_{elab_id}.csv",
        "aggregated_results_{elab_id}.csv",
        "langmuir_fit_results_{elab_id}.csv",
        "analysis_results_{elab_id}.json"
    ],
    "plots": [
        "isotherms_{elab_id}.png",
        "isotherms_{elab_id}.pdf"
    ]
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get('EXPERIMENT_DB_HOST', 'sdl-experiment-db'),
        port=int(os.environ.get('EXPERIMENT_DB_INTERNAL_PORT', 5432)),
        database=os.environ.get('EXPERIMENT_DB_NAME', 'sdl_experiments'),
        user=os.environ.get('EXPERIMENT_DB_USER', 'sdl_admin'),
        password=os.environ.get('EXPERIMENT_DB_PASSWORD', 'sdl_secure_2025')
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if not isinstance(value, str):
        return None
    text = value.strip().replace(",", ".")
    import re
    match = re.search(r"[-+]?\d*\.?\d+", text)
    if match:
        try:
            return float(match.group())
        except ValueError:
            return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """
    if value is None or value == '':
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()
    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (';', ','):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Check if this is actually a decimal comma case like "1,5"
            if sep == ',' and len(parts) == 2:
                joined = ''.join(parts)
                try:
                    return float(joined)
                except ValueError:
                    pass
            # Try to convert all parts to float; if any fail, keep as strings
            all_floats = True
            float_parts = []
            for p in parts:
                p_norm = p.replace(',', '.')
                try:
                    float_parts.append(float(p_norm))
                except ValueError:
                    all_floats = False
                    break
            if all_floats:
                return float_parts
            return parts
    if field_type == 'number':
        parsed = parse_numeric(text)
        return parsed if parsed is not None else text
    return text  # text stays text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json")
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields.

    This respects eLabFTW field types to decide when to parse numeric values and
    also handles delimited lists generically.
    """
    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name not in extra_fields:
            continue
        field = extra_fields[elab_name]
        if not isinstance(field, dict):
            continue
        value = field.get("value")
        field_type = field.get("type")
        parsed_value = parse_field(value, field_type=field_type)
        metadata[db_name] = parsed_value
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder)
    }


def load_analysis_results(elab_id):
    """Load analysis_results_<id>.json if present and return dict and path."""
    results_folder = Path("../results")
    analysis_file = results_folder / f"analysis_results_{elab_id}.json"
    if analysis_file.exists():
        try:
            with open(analysis_file, 'r') as f:
                data = json.load(f)
            return data, analysis_file
        except Exception:
            return None, analysis_file
    return None, analysis_file


def build_results(elab_id):
    """Build results JSONB structure from analysis outputs.

    This function inspects the ../results folder, attempts to load the
    analysis_results_<id>.json created by the analysis script, and
    extracts key metrics and file/plot paths.
    """
    results_folder = Path("../results")
    results_folder_resolved = results_folder.resolve()

    analysis_data, analysis_path = load_analysis_results(elab_id)

    analysis_status = None
    message = None
    warnings_list = None
    summary = {
        "num_ligand_concentrations": None,
        "num_salt_concentrations": None,
        "replicates": None,
        "n_wells_processed": None,
        "n_conditions": None,
    }

    data_files = {}
    plots = {}

    if analysis_data is not None:
        analysis_status = analysis_data.get("status")
        message = analysis_data.get("message")
        warnings_list = analysis_data.get("warnings")

        # Map known data outputs
        data_outputs = analysis_data.get("data_outputs", {})
        if isinstance(data_outputs, dict):
            for key, path in data_outputs.items():
                if isinstance(path, str):
                    data_files[key] = path

        # Add the analysis_results JSON itself
        data_files.setdefault("analysis_results_json", str(analysis_path.resolve()))

        # Plots
        plots_dict = analysis_data.get("plots", {})
        if isinstance(plots_dict, dict):
            for key, path in plots_dict.items():
                if isinstance(path, str):
                    plots[key] = path

        # Summary metrics from analysis metadata and data
        meta = analysis_data.get("metadata", {}) or {}
        if isinstance(meta, dict):
            summary["num_ligand_concentrations"] = meta.get("num_ligand_concentrations")
            summary["num_salt_concentrations"] = meta.get("num_salt_concentrations")
            summary["replicates"] = meta.get("replicates")

        summary["n_wells_processed"] = analysis_data.get("files_processed")

        # Estimate number of conditions from langmuir fit results CSV if present
        langmuir_key = "langmuir_fit_results_csv"
        langmuir_path = data_outputs.get(langmuir_key) if isinstance(data_outputs, dict) else None
        if isinstance(langmuir_path, str):
            try:
                import pandas as pd  # local import to avoid mandatory dependency when not needed
                df = pd.read_csv(langmuir_path)
                summary["n_conditions"] = int(df.shape[0])
            except Exception:
                summary["n_conditions"] = None
    else:
        # No analysis JSON found; fall back to listing files
        analysis_status = "failed"
        message = f"analysis_results_{elab_id}.json not found in results folder."

    # Also include generic listing of results and analysis folders
    all_results_files = list_folder_files(results_folder_resolved)
    analysis_folder = Path("../analysis").resolve()
    analysis_files = list_folder_files(analysis_folder)

    result_obj = {
        "analysis_status": analysis_status,
        "message": message,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "summary": summary,
        "data_files": data_files,
        "plots": plots,
        "warnings": warnings_list if isinstance(warnings_list, list) else [],
        "raw_analysis": analysis_data if isinstance(analysis_data, dict) else None,
        "result_folder_listing": {
            "results_folder": str(results_folder_resolved),
            "results_files": all_results_files,
            "analysis_folder": str(analysis_folder),
            "analysis_files": analysis_files,
        },
    }

    return result_obj


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
        """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""
    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
        """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] is not None else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    row = cursor.fetchone()
    return row[0] if row else None


def main():
    parser = argparse.ArgumentParser(description=f"Commit {PROCESS_NAME} to database")
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument("--dry-run", action="store_true", help="Don't commit, just show what would be done")
    parser.add_argument("--init-schema-only", action="store_true", help="Only initialize process schema")
    args = parser.parse_args()

    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {})
        workflow_json, lab_id = load_workflow()

        # Build data structures
        metadata = extract_metadata(extra_fields)
        raw_data = build_raw_data(args.elab_id)
        results = build_results(args.elab_id)

        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": "completed" if results.get("analysis_status") == "success" else "failed",
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": metadata,
            "raw_data": raw_data,
            "results": results,
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})")
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if conn is not None:
            conn.rollback()
        return 1
    finally:
        if conn is not None:
            conn.close()


if __name__ == "__main__":
    sys.exit(main())