#!/usr/bin/env python3
"""
Database commit script for ÄKTA - Gradient Elution (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 36
PROCESS_NAME = "ÄKTA - Gradient Elution (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Process ID": "linked_process_id",
    "CIP_DURATION": "cip_high_salt_duration_s",
    "WASH_DURATION": "wash_duration_s",
    "CIP_3_DURATION": "cip_h2o1_duration_s",
    "CIP_4_DURATION": "cip_hcl_duration_s",
    "CIP_5_DURATION": "cip_h2o2_duration_s",
    "WASH_FLOW_RATE": "wash_flow_rate_ml_min",
    "CIP_2_HOLD_DURATION": "cip_naoh_hold_duration_s",
    "LOAD_INJECT_DURATION": "load_inject_duration_s",
    "LOAD_INJECT_FLOW_RATE": "load_inject_flow_rate_ml_min",
    "EQUILIBRATION_DURATION": "equilibration_duration_s",
    "ELUTE_GRADIENT_DURATION": "elute_gradient_duration_s",
    "EQUILIBRATION_FLOW_RATE": "equilibration_flow_rate_ml_min",
    "ELUTE_GRADIENT_GRADIENT_END": "elute_gradient_end_percent",
    "ELUTE_GRADIENT_GRADIENT_START": "elute_gradient_start_percent",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "linked_process_id": {
            "type": "string",
            "description": "Linked process identifier (do not modify). Stored as provided by eLabFTW.",
        },
        "cip_high_salt_duration_s": {
            "type": "number",
            "description": "CIP High Salt step duration.",
            "unit": "s",
        },
        "wash_duration_s": {
            "type": "number",
            "description": "Wash step duration.",
            "unit": "s",
        },
        "cip_h2o1_duration_s": {
            "type": "number",
            "description": "CIP H2O 1 step duration.",
            "unit": "s",
        },
        "cip_hcl_duration_s": {
            "type": "number",
            "description": "CIP HCl step duration.",
            "unit": "s",
        },
        "cip_h2o2_duration_s": {
            "type": "number",
            "description": "CIP H2O 2 step duration.",
            "unit": "s",
        },
        "wash_flow_rate_ml_min": {
            "type": "number",
            "description": "Wash step flow rate.",
            "unit": "mL/min",
        },
        "cip_naoh_hold_duration_s": {
            "type": "number",
            "description": "CIP NaOH hold duration.",
            "unit": "s",
        },
        "load_inject_duration_s": {
            "type": "number",
            "description": "Load/Inject step duration.",
            "unit": "s",
        },
        "load_inject_flow_rate_ml_min": {
            "type": "number",
            "description": "Load/Inject step flow rate.",
            "unit": "mL/min",
        },
        "equilibration_duration_s": {
            "type": "number",
            "description": "Equilibration step duration.",
            "unit": "s",
        },
        "elute_gradient_duration_s": {
            "type": "number",
            "description": "Elution gradient step duration.",
            "unit": "s",
        },
        "equilibration_flow_rate_ml_min": {
            "type": "number",
            "description": "Equilibration step flow rate.",
            "unit": "mL/min",
        },
        "elute_gradient_end_percent": {
            "type": "number",
            "description": "Elution gradient end percentage.",
            "unit": "%",
        },
        "elute_gradient_start_percent": {
            "type": "number",
            "description": "Elution gradient start percentage.",
            "unit": "%",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "description": "Status of the AKTA chromatogram analysis.",
            "enum": ["pending", "success", "failed"],
        },
        "analysis_timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when results were committed to the database.",
        },
        "summary": {
            "type": "object",
            "description": "Summary metrics from AKTA chromatogram analysis.",
            "properties": {
                "num_points": {
                    "type": "integer",
                    "description": "Number of time points in chromatogram.",
                },
                "num_peaks": {
                    "type": "integer",
                    "description": "Number of peaks detected in UV chromatogram.",
                },
                "retention_times_min": {
                    "type": "array",
                    "description": "List of detected peak retention times in minutes.",
                    "items": {"type": "number"},
                },
            },
        },
        "data_files": {
            "type": "object",
            "description": "Output data files generated by the analysis.",
            "properties": {
                "analysis_results_json": {
                    "type": "string",
                    "description": "Path to analysis_results_{elab_id}.json.",
                },
                "processed_chromatogram_csv": {
                    "type": "string",
                    "description": "Path to chromatogram_processed_{elab_id}.csv.",
                },
            },
        },
        "plots": {
            "type": "object",
            "description": "Plot files generated by the analysis.",
            "properties": {
                "chromatogram_png": {
                    "type": "string",
                    "description": "Path to chromatogram_{elab_id}.png.",
                },
                "chromatogram_pdf": {
                    "type": "string",
                    "description": "Path to chromatogram_{elab_id}.pdf.",
                },
            },
        },
        "raw_analysis_results": {
            "type": "object",
            "description": "Full contents of analysis_results_{elab_id}.json as produced by the analysis script.",
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "analysis_results_{elab_id}.json",
        "chromatogram_processed_{elab_id}.csv",
    ],
    "plots": [
        "chromatogram_{elab_id}.png",
        "chromatogram_{elab_id}.pdf",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        text = value.strip()
        if text == "":
            return None
        import re

        match = re.search(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", text)
        if match:
            try:
                # Replace decimal comma if present inside the matched number
                return float(match.group(0).replace(",", "."))
            except ValueError:
                return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """
    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()
    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Check if this could be a single number written with a decimal comma
            if sep == "," and len(parts) == 2:
                maybe_number = "".join(parts)
                try:
                    return float(maybe_number)
                except ValueError:
                    pass
            # Otherwise treat as list: numeric if all elements numeric, else strings
            all_numeric = True
            numeric_parts = []
            for p in parts:
                try:
                    numeric_parts.append(float(p))
                except ValueError:
                    all_numeric = False
                    break
            if all_numeric:
                return numeric_parts
            return parts
    if field_type == "number":
        num = parse_numeric(text)
        return num if num is not None else text
    return text  # text stays text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields.

    Uses FIELD_MAPPING and preserves numeric vs text according to field type and
    potential list delimiters.
    """

    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name not in extra_fields:
            continue
        field = extra_fields[elab_name]
        value = field.get("value")
        field_type = field.get("type")
        parsed = parse_field(value, field_type=field_type)
        metadata[db_name] = parsed
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id):
    """Load analysis_results_{elab_id}.json if present in ../results.

    Returns the parsed JSON dict or None if not found/invalid.
    """

    results_folder = Path("../results")
    results_json_path = results_folder / f"analysis_results_{elab_id}.json"
    if results_json_path.exists():
        try:
            with open(results_json_path, "r") as f:
                return json.load(f)
        except Exception as e:
            print(f"WARNING: Failed to read analysis results JSON {results_json_path}: {e}")
    return None


def build_results(elab_id):
    """Build results JSONB structure from analysis outputs.

    Attempts to parse analysis_results_{elab_id}.json produced by the
    AKTA analysis script and derive summary, data_files, and plots.
    """

    results_folder = Path("../results")
    results_folder_abs = results_folder.resolve()

    analysis_results = load_analysis_results(elab_id)

    # Default structure if analysis results are missing
    analysis_status = "pending"
    summary = {}
    data_files = {}
    plots = {}

    if analysis_results is not None:
        # Status
        status = analysis_results.get("status")
        if status in {"success", "failed"}:
            analysis_status = status
        else:
            analysis_status = "pending"

        # Summary metrics from metadata block
        meta = analysis_results.get("metadata", {}) or {}
        if "num_points" in meta:
            try:
                summary["num_points"] = int(meta["num_points"])
            except Exception:
                pass
        if "num_peaks" in meta:
            try:
                summary["num_peaks"] = int(meta["num_peaks"])
            except Exception:
                pass
        if "retention_times_min" in meta:
            rts = meta.get("retention_times_min")
            if isinstance(rts, list):
                try:
                    summary["retention_times_min"] = [float(x) for x in rts]
                except Exception:
                    summary["retention_times_min"] = rts

        # Data outputs
        data_out = analysis_results.get("data_outputs", {}) or {}
        proc_csv = data_out.get("processed_chromatogram_csv")
        if proc_csv:
            data_files["processed_chromatogram_csv"] = proc_csv
        # Also store path to analysis_results JSON itself
        results_json_name = f"analysis_results_{elab_id}.json"
        results_json_path = results_folder_abs / results_json_name
        if results_json_path.exists():
            data_files["analysis_results_json"] = str(results_json_path)

        # Plots
        plots_dict = analysis_results.get("plots", {}) or {}
        for key in ("chromatogram_png", "chromatogram_pdf"):
            if key in plots_dict:
                plots[key] = plots_dict[key]

    # If not found, still include expected file names (absolute) for traceability
    if "analysis_results_json" not in data_files:
        data_files["analysis_results_json"] = str(results_folder_abs / f"analysis_results_{elab_id}.json")
    if "processed_chromatogram_csv" not in data_files:
        data_files["processed_chromatogram_csv"] = str(
            results_folder_abs / f"chromatogram_processed_{elab_id}.csv"
        )

    if "chromatogram_png" not in plots:
        plots["chromatogram_png"] = str(results_folder_abs / f"chromatogram_{elab_id}.png")
    if "chromatogram_pdf" not in plots:
        plots["chromatogram_pdf"] = str(results_folder_abs / f"chromatogram_{elab_id}.pdf")

    return {
        "analysis_status": analysis_status,
        "analysis_timestamp": datetime.now(timezone.utc).isoformat(),
        "summary": summary,
        "data_files": data_files,
        "plots": plots,
        "raw_analysis_results": analysis_results,
    }


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""

    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""

    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    row = cursor.fetchone()
    return row[0] if row else None


def main():
    parser = argparse.ArgumentParser(description=f"Commit {PROCESS_NAME} to database")
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument("--dry-run", action="store_true", help="Don't commit, just show what would be done")
    parser.add_argument("--init-schema-only", action="store_true", help="Only initialize process schema")
    args = parser.parse_args()

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {}) or {}
        workflow_json, lab_id = load_workflow()

        # Build data structures
        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": "completed",
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": extract_metadata(extra_fields),
            "raw_data": build_raw_data(args.elab_id),
            "results": build_results(args.elab_id),
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})")
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if "conn" in locals():
            conn.rollback()
        return 1
    finally:
        if "conn" in locals():
            conn.close()


if __name__ == "__main__":
    sys.exit(main())