#!/usr/bin/env python3
"""
Database commit script for AKTA - Gradient Elution (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 36
PROCESS_NAME = "AKTA - Gradient Elution (automated)"
PROCESS_VERSION = "1.0"

# eLabFTW extra field name -> snake_case key used in DB metadata
FIELD_MAPPING = {
    "Process ID": "linked_process_id",
    "CIP_DURATION": "cip_high_salt_duration_s",
    "WASH_DURATION": "wash_duration_s",
    "CIP_3_DURATION": "cip_h2o1_duration_s",
    "CIP_4_DURATION": "cip_hcl_duration_s",
    "CIP_5_DURATION": "cip_h2o2_duration_s",
    "WASH_FLOW_RATE": "wash_flow_rate_ml_min",
    "CIP_2_HOLD_DURATION": "cip_naoh_hold_duration_s",
    "LOAD_INJECT_DURATION": "load_inject_duration_s",
    "LOAD_INJECT_FLOW_RATE": "load_inject_flow_rate_ml_min",
    "EQUILIBRATION_DURATION": "equilibration_duration_s",
    "ELUTE_GRADIENT_DURATION": "elute_gradient_duration_s",
    "EQUILIBRATION_FLOW_RATE": "equilibration_flow_rate_ml_min",
    "ELUTE_GRADIENT_GRADIENT_END": "elute_gradient_end_percent",
    "ELUTE_GRADIENT_GRADIENT_START": "elute_gradient_start_percent",
}

# JSON Schema for input parameters (metadata)
METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "linked_process_id": {
            "type": "string",
            "description": "Linked process identifier (do not modify)",
        },
        "cip_high_salt_duration_s": {
            "type": "number",
            "description": "CIP high-salt step duration",
            "unit": "s",
        },
        "wash_duration_s": {
            "type": "number",
            "description": "Wash step duration",
            "unit": "s",
        },
        "cip_h2o1_duration_s": {
            "type": "number",
            "description": "CIP H2O 1 step duration",
            "unit": "s",
        },
        "cip_hcl_duration_s": {
            "type": "number",
            "description": "CIP HCl step duration",
            "unit": "s",
        },
        "cip_h2o2_duration_s": {
            "type": "number",
            "description": "CIP H2O 2 step duration",
            "unit": "s",
        },
        "wash_flow_rate_ml_min": {
            "type": "number",
            "description": "Wash step flow rate",
            "unit": "mL/min",
        },
        "cip_naoh_hold_duration_s": {
            "type": "number",
            "description": "CIP NaOH hold duration",
            "unit": "s",
        },
        "load_inject_duration_s": {
            "type": "number",
            "description": "Load/Inject step duration",
            "unit": "s",
        },
        "load_inject_flow_rate_ml_min": {
            "type": "number",
            "description": "Load/Inject step flow rate",
            "unit": "mL/min",
        },
        "equilibration_duration_s": {
            "type": "number",
            "description": "Equilibration step duration",
            "unit": "s",
        },
        "elute_gradient_duration_s": {
            "type": "number",
            "description": "Elution gradient duration",
            "unit": "s",
        },
        "equilibration_flow_rate_ml_min": {
            "type": "number",
            "description": "Equilibration step flow rate",
            "unit": "mL/min",
        },
        "elute_gradient_end_percent": {
            "type": "number",
            "description": "Elution gradient final buffer percentage",
            "unit": "%",
        },
        "elute_gradient_start_percent": {
            "type": "number",
            "description": "Elution gradient initial buffer percentage",
            "unit": "%",
        },
    },
}

# JSON Schema for analysis results
RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "description": "Status of the AKTA analysis script",
            "enum": ["pending", "success", "failed"],
        },
        "message": {
            "type": "string",
            "description": "Human-readable message summarizing analysis outcome",
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when results were committed to the database",
        },
        "metadata": {
            "type": "object",
            "description": "Key metrics and flags reported by the analysis script",
            "properties": {
                "experiment_json_loaded": {
                    "type": "boolean",
                    "description": "Whether experiment_[ID].json could be loaded by the analysis script",
                },
                "num_peaks": {
                    "type": "integer",
                    "description": "Number of UV peaks detected in the chromatogram",
                },
            },
        },
        "data_files": {
            "type": "object",
            "description": "Paths to data output files produced by the analysis script",
            "properties": {
                "analysis_results_json": {
                    "type": "string",
                    "description": "Path to main analysis results JSON file",
                },
                "chromatogram_csv": {
                    "type": "string",
                    "description": "Path to CSV file containing parsed chromatogram data (time, UV, conductivity)",
                },
                "peaks_csv": {
                    "type": "string",
                    "description": "Path to CSV file containing detected peak table (if peaks were found)",
                },
            },
        },
        "plots": {
            "type": "object",
            "description": "Paths to generated chromatogram plots",
            "properties": {
                "chromatogram_png": {
                    "type": "string",
                    "description": "Path to PNG chromatogram plot with peak annotations",
                },
                "chromatogram_pdf": {
                    "type": "string",
                    "description": "Path to PDF chromatogram plot with peak annotations",
                },
            },
        },
        "files_processed": {
            "type": "integer",
            "description": "Number of files written by the analysis script (as reported in its results JSON)",
        },
        "results_folder": {
            "type": "object",
            "description": "Listing of all files present in the results folder at commit time",
            "properties": {
                "folder_path": {
                    "type": "string",
                    "description": "Absolute path to the results folder",
                },
                "files": {
                    "type": "array",
                    "description": "List of filenames present in the results folder",
                    "items": {"type": "string"},
                },
            },
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "analysis_results_{elab_id}.json",
        "akta_chromatogram_raw_{elab_id}.csv",
        "akta_peaks_{elab_id}.csv",
    ],
    "plots": [
        "chromatogram_{elab_id}.png",
        "chromatogram_{elab_id}.pdf",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value: str):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    text = str(value).strip()
    if text == "":
        return None

    import re

    # Replace comma decimal separator with dot if it looks like a decimal comma
    # (i.e. exactly one comma and no dots). This avoids mis-parsing '1,5' as a list.
    if "," in text and ";" not in text and text.count(",") == 1 and "." not in text:
        candidate = text.replace(",", ".")
    else:
        candidate = text

    match = re.search(r"[-+]?\d*\.?\d+(?:[eE][-+"]?\d+)?", candidate)
    if match:
        try:
            return float(match.group(0))
        except ValueError:
            return None
    return None


def parse_field(value, field_type: str | None = None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """

    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value

    text = str(value).strip()

    # A list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    # value, not two. We handle the decimal-comma special case here.
    for sep in (";", ","):
        if sep in text:
            parts = [p.strip() for p in text.split(sep) if p.strip()]
            if len(parts) > 1:
                # Try to interpret as all-float list
                all_float = True
                float_parts = []
                for p in parts:
                    num = parse_numeric(p)
                    if num is None:
                        all_float = False
                        break
                    float_parts.append(num)
                if all_float:
                    return float_parts
                return parts

    if field_type == "number":
        num = parse_numeric(text)
        return num if num is not None else text

    # For text or unknown types, keep as string
    return text


def find_experiment_json(elab_id: int) -> Path:
    """Find experiment JSON file."""

    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""

    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields: dict) -> dict:
    """Extract and map metadata from eLabFTW extra fields.

    Uses FIELD_MAPPING and parse_field, respecting the eLabFTW field type.
    """

    metadata: dict = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name not in extra_fields:
            continue
        field = extra_fields.get(elab_name, {})
        value = field.get("value")
        field_type = field.get("type")  # e.g. 'number', 'text'
        parsed_value = parse_field(value, field_type=field_type)
        metadata[db_name] = parsed_value
    return metadata


def list_folder_files(folder_path: Path) -> list:
    """List files in a folder."""

    if folder_path.exists() and folder_path.is_dir():
        return [f.name for f in folder_path.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id: int) -> dict:
    """Build raw_data JSONB structure."""

    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id: int) -> dict | None:
    """Load the main analysis_results_{id}.json produced by the analysis script."""

    results_folder = Path("../results")
    results_json = results_folder / f"analysis_results_{elab_id}.json"
    if results_json.exists():
        try:
            with open(results_json, "r") as f:
                return json.load(f)
        except Exception:
            return None
    return None


def build_results(elab_id: int) -> dict:
    """Build results JSONB structure from analysis outputs.

    This function is conservative: if the analysis_results JSON is missing, it will
    still populate file listings and mark analysis_status as 'pending'.
    """

    results_folder = Path("../results")
    results_folder_abs = str(results_folder.resolve())

    analysis = load_analysis_results(elab_id)

    # Default values if analysis_results JSON is not present
    analysis_status = "pending"
    message = "Analysis results JSON not found."
    metadata_block: dict = {}
    files_processed = None

    data_files: dict = {}
    plots: dict = {}

    if analysis is not None:
        # Map analysis content into our standardized structure
        status_raw = analysis.get("status")
        if status_raw in {"success", "failed"}:
            analysis_status = status_raw
        message = analysis.get("message", "")

        metadata_block = analysis.get("metadata", {}) or {}
        files_processed = analysis.get("files_processed")

        data_outputs = analysis.get("data_outputs", {}) or {}
        if "chromatogram_csv" in data_outputs:
            data_files["chromatogram_csv"] = data_outputs["chromatogram_csv"]
        if "peaks_csv" in data_outputs:
            data_files["peaks_csv"] = data_outputs["peaks_csv"]

        # Always record where the main analysis_results JSON file lives
        data_files["analysis_results_json"] = str(
            (results_folder / f"analysis_results_{elab_id}.json").resolve()
        )

        plots_block = analysis.get("plots", {}) or {}
        if plots_block.get("chromatogram_png"):
            plots["chromatogram_png"] = plots_block["chromatogram_png"]
        else:
            png_path = results_folder / f"chromatogram_{elab_id}.png"
            if png_path.exists():
                plots["chromatogram_png"] = str(png_path.resolve())

        if plots_block.get("chromatogram_pdf"):
            plots["chromatogram_pdf"] = plots_block["chromatogram_pdf"]
        else:
            pdf_path = results_folder / f"chromatogram_{elab_id}.pdf"
            if pdf_path.exists():
                plots["chromatogram_pdf"] = str(pdf_path.resolve())

    else:
        # No analysis JSON - still try to infer standard filenames
        ar_path = results_folder / f"analysis_results_{elab_id}.json"
        if ar_path.exists():
            data_files["analysis_results_json"] = str(ar_path.resolve())
        csv_path = results_folder / f"akta_chromatogram_raw_{elab_id}.csv"
        if csv_path.exists():
            data_files["chromatogram_csv"] = str(csv_path.resolve())
        peaks_path = results_folder / f"akta_peaks_{elab_id}.csv"
        if peaks_path.exists():
            data_files["peaks_csv"] = str(peaks_path.resolve())
        png_path = results_folder / f"chromatogram_{elab_id}.png"
        if png_path.exists():
            plots["chromatogram_png"] = str(png_path.resolve())
        pdf_path = results_folder / f"chromatogram_{elab_id}.pdf"
        if pdf_path.exists():
            plots["chromatogram_pdf"] = str(pdf_path.resolve())

    result_obj: dict = {
        "analysis_status": analysis_status,
        "message": message,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "metadata": metadata_block,
        "data_files": data_files,
        "plots": plots,
    }
    if files_processed is not None:
        result_obj["files_processed"] = files_processed

    # Also add a convenience listing of all files present in the results folder
    result_obj["results_folder"] = {
        "folder_path": results_folder_abs,
        "files": list_folder_files(results_folder),
    }

    return result_obj


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""

    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
        """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id: int, data: dict) -> int:
    """Insert or update experiment execution."""

    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
        """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] is not None else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    return cursor.fetchone()[0]


def main() -> int:
    parser = argparse.ArgumentParser(description=f"Commit {PROCESS_NAME} to database")
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {}) or {}
        workflow_json, lab_id = load_workflow()

        # Build data structures
        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": "completed",
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": extract_metadata(extra_fields),
            "raw_data": build_raw_data(args.elab_id),
            "results": build_results(args.elab_id),
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            if conn is not None:
                conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})")
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if conn is not None:
            conn.rollback()
        return 1
    finally:
        if conn is not None:
            conn.close()


if __name__ == "__main__":
    sys.exit(main())