#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_identifier",
    "Pump Speed": "pump_speed",
    "Replicates": "num_replicates",
    "Resin Mass": "resin_mass_mg",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume_ul",
    "Venting time": "venting_time_s",
    "Pump Duration": "pump_duration_s",
    "Incubation Time": "incubation_time_min",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume_ul",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature_c",
    "Measurement Wavelength": "measurement_wavelength_nm",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation_rpm",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration_s",
    "Number of salt concentrations": "num_salt_concentrations",
    "Number of ligand concentrations": "num_ligand_concentrations",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Buffer solution used during loading and equilibration",
        },
        "salt_name": {
            "type": "string",
            "description": "Name or identity of the salt used in the buffer",
        },
        "process_identifier": {
            "type": "string",
            "description": "Process ID recorded in eLabFTW (may duplicate workflow process ID)",
        },
        "pump_speed": {
            "type": "number",
            "description": "Pump speed used for loading/equilibration",
            "unit": "arbitrary",
        },
        "num_replicates": {
            "type": "integer",
            "description": "Number of replicate wells per condition",
        },
        "resin_mass_mg": {
            "type": "number",
            "description": "Mass of resin used per well",
            "unit": "mg",
        },
        "ligand_name": {
            "type": "string",
            "description": "Name or identifier of the ligand",
        },
        "total_volume_ul": {
            "type": "number",
            "description": "Total liquid volume per well",
            "unit": "µL",
        },
        "venting_time_s": {
            "type": "number",
            "description": "Venting time during automated protocol",
            "unit": "s",
        },
        "pump_duration_s": {
            "type": "number",
            "description": "Pump duration during automated protocol",
            "unit": "s",
        },
        "incubation_time_min": {
            "type": "number",
            "description": "Incubation time before measurement",
            "unit": "min",
        },
        "salt_concentrations": {
            "type": "array",
            "description": "List of salt concentrations used in the experiment (order matters, used for plate layout)",
            "items": {"type": "number"},
        },
        "equilibration_cycles": {
            "type": "integer",
            "description": "Number of equilibration cycles performed",
        },
        "equilibration_volume_ul": {
            "type": "number",
            "description": "Equilibration volume per cycle",
            "unit": "µL",
        },
        "ligand_concentrations": {
            "type": "array",
            "description": "List of ligand concentrations used in the experiment (order matters, used for plate layout)",
            "items": {"type": "number"},
        },
        "incubation_temperature_c": {
            "type": "number",
            "description": "Incubation temperature",
            "unit": "°C",
        },
        "measurement_wavelength_nm": {
            "type": "number",
            "description": "Measurement wavelength of the plate reader",
            "unit": "nm",
        },
        "calibration_curve_slope": {
            "type": "number",
            "description": "Slope of ligand calibration curve (Abs vs concentration)",
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit for salt concentrations (e.g. mM)",
        },
        "shaker_speed_incubation_rpm": {
            "type": "number",
            "description": "Shaker speed during incubation",
            "unit": "rpm",
        },
        "salt_stock_concentration": {
            "type": "number",
            "description": "Stock concentration of the salt solution",
            "unit": "same as salt_concentration_unit",
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit for ligand concentrations (e.g. µM, mM)",
        },
        "ligand_stock_concentration": {
            "type": "number",
            "description": "Stock concentration of the ligand solution",
            "unit": "same as ligand_concentration_unit",
        },
        "calibration_curve_intercept": {
            "type": "number",
            "description": "Intercept of ligand calibration curve (Abs vs concentration)",
        },
        "equilibration_cycle_duration_s": {
            "type": "number",
            "description": "Duration of one equilibration cycle",
            "unit": "s",
        },
        "num_salt_concentrations": {
            "type": "integer",
            "description": "Number of distinct salt concentrations in the plate layout",
        },
        "num_ligand_concentrations": {
            "type": "integer",
            "description": "Number of distinct ligand concentrations in the plate layout",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "success", "failed", "completed"],
            "description": "Status of the analysis script run",
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when results were committed to the database",
        },
        "summary": {
            "type": "object",
            "description": "Key metrics from Langmuir fits across salt concentrations",
            "properties": {
                "num_salt_concentrations": {
                    "type": "integer",
                    "description": "Number of salt concentrations analyzed",
                },
                "num_ligand_concentrations": {
                    "type": "integer",
                    "description": "Number of ligand concentrations analyzed",
                },
                "num_replicates": {
                    "type": "integer",
                    "description": "Number of replicates per condition (from metadata if available)",
                },
                "num_wells_mapped": {
                    "type": "integer",
                    "description": "Total number of wells mapped to experimental conditions or files processed",
                },
                "num_warnings": {
                    "type": "integer",
                    "description": "Number of warnings produced during analysis",
                },
            },
        },
        "langmuir_fits": {
            "type": "array",
            "description": "Langmuir fit parameters per salt concentration, reconstructed from fit CSV if available",
            "items": {
                "type": "object",
                "properties": {
                    "salt_index": {
                        "type": "integer",
                        "description": "Index of salt concentration",
                    },
                    "salt_concentration": {
                        "type": "number",
                        "description": "Salt concentration value",
                    },
                    "q_max": {
                        "type": ["number", "null"],
                        "description": "Fitted Langmuir q_max (capacity)",
                    },
                    "K": {
                        "type": ["number", "null"],
                        "description": "Fitted Langmuir affinity constant K",
                    },
                    "r2": {
                        "type": ["number", "null"],
                        "description": "Coefficient of determination for the fit",
                    },
                    "num_points": {
                        "type": "integer",
                        "description": "Number of data points used for the fit",
                    },
                },
            },
        },
        "data_files": {
            "type": "object",
            "description": "Output data file paths from analysis script",
            "properties": {
                "analysis_results_json": {
                    "type": "string",
                    "description": "Path to main analysis results JSON",
                },
                "raw_tecan_file": {
                    "type": "string",
                    "description": "Path to downloaded or copied raw Tecan Excel file",
                },
                "absorbance_wells_csv": {
                    "type": "string",
                    "description": "CSV with absorbance per well",
                },
                "well_conditions_csv": {
                    "type": "string",
                    "description": "CSV with mapped well conditions",
                },
                "aggregated_conditions_csv": {
                    "type": "string",
                    "description": "CSV with aggregated replicate statistics",
                },
                "langmuir_fits_csv": {
                    "type": "string",
                    "description": "CSV with Langmuir fit results",
                },
            },
        },
        "plots": {
            "type": "object",
            "description": "Generated plot files",
            "properties": {
                "isotherms_png": {
                    "type": "string",
                    "description": "PNG of loading isotherms with Langmuir fits",
                },
                "isotherms_pdf": {
                    "type": "string",
                    "description": "PDF of loading isotherms with Langmuir fits",
                },
            },
        },
        "raw_analysis": {
            "type": "object",
            "description": "Full raw JSON output of the analysis script for traceability",
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "tecan_data_{elab_id}.xlsx",
        "absorbance_wells_{elab_id}.csv",
        "well_conditions_{elab_id}.csv",
        "aggregated_conditions_{elab_id}.csv",
        "langmuir_fits_{elab_id}.csv",
        "analysis_results_{elab_id}.json",
    ],
    "plots": [
        "isotherms_{elab_id}.png",
        "isotherms_{elab_id}.pdf",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        text = value.strip().replace(",", ".")
        import re

        match = re.search(r"[-+]?\d*\.?\d+", text)
        if match:
            try:
                return float(match.group())
            except ValueError:
                return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """
    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()
    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Check for decimal comma case like "1,5"
            if sep == "," and len(parts) == 2:
                joined = "".join(parts)
                try:
                    return float(joined)
                except ValueError:
                    pass
            # Try numeric list first
            try:
                nums = [float(p.replace(",", ".")) for p in parts]
                return nums
            except ValueError:
                return parts
    if field_type == "number":
        num = parse_numeric(text)
        return num if num is not None else text
    return text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields.

    Uses FIELD_MAPPING and respects eLabFTW field types for numeric coercion and lists.
    """
    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name not in extra_fields:
            continue
        field = extra_fields[elab_name]
        value = field.get("value")
        field_type = field.get("type")  # e.g. 'number', 'text', etc.
        parsed = parse_field(value, field_type=field_type)
        metadata[db_name] = parsed
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id):
    """Load the main analysis results JSON if it exists.

    Returns a tuple (results_dict_or_None, results_json_path_or_None).
    """
    results_folder = Path("../results")
    candidates = [
        results_folder / f"analysis_results_{elab_id}.json",
        results_folder / "analysis_results.json",
    ]
    for path in candidates:
        if path.exists():
            try:
                with open(path, "r") as f:
                    data = json.load(f)
                return data, str(path.resolve())
            except Exception:
                continue
    return None, None


def build_results(elab_id):
    """Build results JSONB structure combining analysis outputs and files.

    This function is process-aware of the filenames generated by the loading
    isotherm analysis script.
    """
    results_dir = Path("../results")
    results_dir.mkdir(parents=True, exist_ok=True)

    analysis_data, analysis_json_path = load_analysis_results(elab_id)

    # Determine status and collect base info
    if analysis_data is None:
        analysis_status = "pending"
        raw_analysis = None
        warnings = []
        files_dict = {}
        plots_dict = {}
    else:
        analysis_status = analysis_data.get("status", "completed")
        raw_analysis = analysis_data
        warnings = analysis_data.get("warnings", [])
        data_outputs = analysis_data.get("data_outputs", {})
        plots = analysis_data.get("plots", {})
        files_dict = {}
        plots_dict = {}

        if analysis_json_path is not None:
            files_dict["analysis_results_json"] = analysis_json_path
        if "raw_tecan_file" in data_outputs:
            files_dict["raw_tecan_file"] = data_outputs["raw_tecan_file"]
        if "absorbance_wells_csv" in data_outputs:
            files_dict["absorbance_wells_csv"] = data_outputs["absorbance_wells_csv"]
        if "well_conditions_csv" in data_outputs:
            files_dict["well_conditions_csv"] = data_outputs["well_conditions_csv"]
        if "aggregated_conditions_csv" in data_outputs:
            files_dict["aggregated_conditions_csv"] = data_outputs[
                "aggregated_conditions_csv"
            ]
        if "langmuir_fits_csv" in data_outputs:
            files_dict["langmuir_fits_csv"] = data_outputs["langmuir_fits_csv"]

        if "isotherms_png" in plots:
            plots_dict["isotherms_png"] = plots["isotherms_png"]
        if "isotherms_pdf" in plots:
            plots_dict["isotherms_pdf"] = plots["isotherms_pdf"]

    # Also scan results directory for expected files by naming pattern
    elab_str = str(elab_id)
    for pattern, key in [
        (f"absorbance_wells_{elab_str}.csv", "absorbance_wells_csv"),
        (f"well_conditions_{elab_str}.csv", "well_conditions_csv"),
        (f"aggregated_conditions_{elab_str}.csv", "aggregated_conditions_csv"),
        (f"langmuir_fits_{elab_str}.csv", "langmuir_fits_csv"),
        (f"analysis_results_{elab_str}.json", "analysis_results_json"),
    ]:
        p = results_dir / pattern
        if p.exists() and key not in files_dict:
            files_dict[key] = str(p.resolve())

    for pattern, key in [
        (f"isotherms_{elab_str}.png", "isotherms_png"),
        (f"isotherms_{elab_str}.pdf", "isotherms_pdf"),
    ]:
        p = results_dir / pattern
        if p.exists() and key not in plots_dict:
            plots_dict[key] = str(p.resolve())

    # Build a high-level summary from analysis_data if available
    summary = {}
    if analysis_data is not None:
        meta = analysis_data.get("metadata", {})
        summary["num_salt_concentrations"] = int(meta.get("num_salt_concentrations", 0))
        summary["num_ligand_concentrations"] = int(
            meta.get("num_ligand_concentrations", 0)
        )
        summary["num_replicates"] = int(meta.get("num_replicates", 0))
        # files_processed in analysis_results counts files, not wells, but we store it anyway
        summary["num_wells_mapped"] = int(analysis_data.get("files_processed", 0))
        summary["num_warnings"] = len(warnings)

    # Extract Langmuir fits if present via CSV
    langmuir_fits = []
    if analysis_data is not None:
        fits_csv_path = files_dict.get("langmuir_fits_csv")
        if fits_csv_path:
            try:
                import csv

                with open(fits_csv_path, newline="") as csvfile:
                    reader = csv.DictReader(csvfile)
                    for row in reader:
                        try:
                            langmuir_fits.append(
                                {
                                    "salt_index": int(row.get("salt_index", 0)),
                                    "salt_concentration": float(
                                        row.get("salt_concentration", "nan")
                                    ),
                                    "q_max": float(row["q_max"])
                                    if row.get("q_max") not in (None, "", "nan")
                                    else None,
                                    "K": float(row["K"])
                                    if row.get("K") not in (None, "", "nan")
                                    else None,
                                    "r2": float(row["r2"])
                                    if row.get("r2") not in (None, "", "nan")
                                    else None,
                                    "num_points": int(row.get("num_points", 0)),
                                }
                            )
                        except Exception:
                            # Skip problematic rows
                            continue
            except Exception:
                langmuir_fits = []

    results = {
        "analysis_status": analysis_status,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "summary": summary,
        "langmuir_fits": langmuir_fits,
        "data_files": files_dict,
        "plots": plots_dict,
        "raw_analysis": raw_analysis,
    }

    return results


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""
    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"])
            if data["workflow_json"] is not None
            else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    row = cursor.fetchone()
    return row[0] if row else None


def main():
    parser = argparse.ArgumentParser(
        description=f"Commit {PROCESS_NAME} to database"
    )
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {})
        workflow_json, lab_id = load_workflow()

        # Build data structures
        metadata = extract_metadata(extra_fields)
        raw_data = build_raw_data(args.elab_id)
        results = build_results(args.elab_id)

        db_status = (
            "completed"
            if results.get("analysis_status") in {"success", "completed"}
            else "failed"
        )

        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": db_status,
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": metadata,
            "raw_data": raw_data,
            "results": results,
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})")
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if conn is not None:
            try:
                conn.rollback()
            except Exception:
                pass
        return 1
    finally:
        if conn is not None:
            try:
                conn.close()
            except Exception:
                pass


if __name__ == "__main__":
    sys.exit(main())