#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_run_id",
    "Pump Speed": "pump_speed",
    "Replicates": "replicates",
    "Resin Mass": "resin_mass_mg",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume_ul",
    "Venting time": "venting_time_s",
    "Pump Duration": "pump_duration_s",
    "Incubation Time": "incubation_time_min",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume_ul",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature_c",
    "Measurement Wavelength": "measurement_wavelength_nm",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation_rpm",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration_s",
    "Number of salt concentrations": "number_of_salt_concentrations",
    "Number of ligand concentrations": "number_of_ligand_concentrations",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Buffer solution used for equilibration and loading",
        },
        "salt_name": {
            "type": "string",
            "description": "Name or identity of the salt used in the buffer",
        },
        "process_run_id": {
            "type": "string",
            "description": "Identifier of the automated process run (as configured on the robot/controller)",
        },
        "pump_speed": {
            "type": "number",
            "description": "Pump speed during loading / equilibration steps",
            "unit": "arbitrary unit or mL/min as defined in SOP",
        },
        "replicates": {
            "type": "integer",
            "description": "Number of replicate wells per condition on the plate",
        },
        "resin_mass_mg": {
            "type": "number",
            "description": "Mass of resin used per well",
            "unit": "mg",
        },
        "ligand_name": {
            "type": "string",
            "description": "Name or identity of the ligand/solute loaded onto the resin",
        },
        "total_volume_ul": {
            "type": "number",
            "description": "Total liquid volume per well used for the isotherm experiment",
            "unit": "µL",
        },
        "venting_time_s": {
            "type": "number",
            "description": "Venting time during automated process",
            "unit": "s",
        },
        "pump_duration_s": {
            "type": "number",
            "description": "Duration of pump operation for loading / equilibration",
            "unit": "s",
        },
        "incubation_time_min": {
            "type": "number",
            "description": "Incubation time for reaching equilibrium loading",
            "unit": "min",
        },
        "salt_concentrations": {
            "type": "array",
            "description": "List of salt concentrations used in the experiment (order as laid out on plate)",
            "items": {"type": "number"},
            "unit": "as specified by salt_concentration_unit",
        },
        "equilibration_cycles": {
            "type": "integer",
            "description": "Number of equilibration cycles performed on the resin",
        },
        "equilibration_volume_ul": {
            "type": "number",
            "description": "Volume per equilibration cycle",
            "unit": "µL",
        },
        "ligand_concentrations": {
            "type": "array",
            "description": "List of initial ligand concentrations loaded on the resin (per row)",
            "items": {"type": "number"},
            "unit": "as specified by ligand_concentration_unit",
        },
        "incubation_temperature_c": {
            "type": "number",
            "description": "Incubation temperature of the plate",
            "unit": "°C",
        },
        "measurement_wavelength_nm": {
            "type": "number",
            "description": "Wavelength used by the plate reader for absorbance measurement",
            "unit": "nm",
        },
        "calibration_curve_slope": {
            "type": "number",
            "description": "Slope of the absorbance-to-concentration calibration curve",
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit for salt concentrations (e.g. mM, M)",
        },
        "shaker_speed_incubation_rpm": {
            "type": "number",
            "description": "Shaker speed used during incubation",
            "unit": "rpm",
        },
        "salt_stock_concentration": {
            "type": "number",
            "description": "Stock concentration of the salt solution",
            "unit": "same as salt_concentration_unit",
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit for ligand concentrations (e.g. µM, mM)",
        },
        "ligand_stock_concentration": {
            "type": "number",
            "description": "Stock concentration of the ligand solution",
            "unit": "same as ligand_concentration_unit",
        },
        "calibration_curve_intercept": {
            "type": "number",
            "description": "Intercept of the absorbance-to-concentration calibration curve",
        },
        "equilibration_cycle_duration_s": {
            "type": "number",
            "description": "Duration of a single equilibration cycle",
            "unit": "s",
        },
        "number_of_salt_concentrations": {
            "type": "integer",
            "description": "Number of distinct salt concentrations used on the plate",
        },
        "number_of_ligand_concentrations": {
            "type": "integer",
            "description": "Number of distinct ligand concentrations (rows) used on the plate",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "success", "failed"],
            "description": "Status of the loading isotherm analysis as reported by the analysis script",
        },
        "analysis_timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when results were committed to the database",
        },
        "summary": {
            "type": "object",
            "description": "Key numerical summary metrics from analysis",
            "properties": {
                "files_processed": {
                    "type": "integer",
                    "description": "Number of raw data files successfully processed",
                },
                "num_ligand_concentrations": {
                    "type": "integer",
                    "description": "Number of ligand concentrations used (from metadata)",
                },
                "num_salt_concentrations": {
                    "type": "integer",
                    "description": "Number of salt concentrations used (from metadata)",
                },
                "replicates": {
                    "type": "integer",
                    "description": "Number of replicates per condition (from metadata)",
                },
                "langmuir_fits_per_salt": {
                    "type": "integer",
                    "description": "Number of salt conditions for which Langmuir fits were successfully obtained",
                },
            },
        },
        "metadata_used": {
            "type": "object",
            "description": "Subset of metadata used directly by the analysis script (copied from analysis JSON)",
        },
        "langmuir_fits": {
            "type": "object",
            "description": "Per-salt Langmuir fit parameters and diagnostics from the analysis script",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "salt_conc": {"type": ["number", "null"]},
                    "q_max": {"type": "number"},
                    "K": {"type": "number"},
                    "R2": {"type": "number"},
                    "num_points": {"type": "integer"},
                },
            },
        },
        "data_files": {
            "type": "object",
            "description": "Output data file paths produced by the analysis script plus folder listings",
            "properties": {
                "raw_tecan_excel": {"type": ["string", "null"]},
                "per_well_csv": {"type": ["string", "null"]},
                "aggregated_csv": {"type": ["string", "null"]},
                "fit_parameters_csv": {"type": ["string", "null"]},
                "results_json": {"type": ["string", "null"]},
                "results_folder_listing": {
                    "type": "array",
                    "items": {"type": "string"},
                },
                "analysis_folder_listing": {
                    "type": "array",
                    "items": {"type": "string"},
                },
            },
        },
        "plots": {
            "type": "object",
            "description": "Plot file paths produced by the analysis script",
            "properties": {
                "isotherms_png": {"type": ["string", "null"]},
                "isotherms_pdf": {"type": ["string", "null"]},
            },
        },
        "raw_analysis_output": {
            "type": "object",
            "description": "Full JSON output structure from analyze_experiment (for debugging / provenance)",
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "tecan_data_{elab_id}.xlsx",
        "per_well_data_{elab_id}.csv",
        "aggregated_isotherm_data_{elab_id}.csv",
        "langmuir_fit_parameters_{elab_id}.csv",
        "analysis_results_{elab_id}.json",
    ],
    "plots": [
        "isotherms_{elab_id}.png",
        "isotherms_{elab_id}.pdf",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        text = value.strip()
        import re

        match = re.search(r"[-+]?\d*[,\.]?\d+", text)
        if match:
            num_str = match.group(0).replace(",", ".")
            try:
                return float(num_str)
            except ValueError:
                return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """

    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value

    text = str(value).strip()

    # Treat semicolon or comma as a delimiter only if it yields more than one token
    # and is not just a decimal comma representation.
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Try to parse all parts as numbers; if any fail, keep as strings
            all_numeric = True
            numeric_parts = []
            for p in parts:
                p_norm = p.replace(",", ".")
                try:
                    numeric_parts.append(float(p_norm))
                except ValueError:
                    all_numeric = False
                    break
            if all_numeric:
                return numeric_parts
            return parts

    # Single-valued
    if field_type == "number":
        parsed = parse_numeric(text)
        return parsed if parsed is not None else text

    return text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""

    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""

    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields.

    Uses FIELD_MAPPING and parse_field, respecting field['type'] when available.
    """

    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        field = extra_fields.get(elab_name)
        if not field:
            continue
        value = field.get("value")
        field_type = field.get("type")
        parsed_value = parse_field(value, field_type=field_type)
        metadata[db_name] = parsed_value
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""

    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""

    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id):
    """Load analysis_results_{elab_id}.json if present.

    Returns dict or None.
    """

    results_folder = Path("../results")
    json_path = results_folder / f"analysis_results_{elab_id}.json"
    if json_path.exists():
        try:
            with open(json_path, "r") as f:
                return json.load(f)
        except Exception:
            return None
    # Fallback: sometimes analysis may be stored under ../analysis
    alt_folder = Path("../analysis")
    alt_path = alt_folder / f"analysis_results_{elab_id}.json"
    if alt_path.exists():
        try:
            with open(alt_path, "r") as f:
                return json.load(f)
        except Exception:
            return None
    return None


def build_results(elab_id):
    """Build results JSONB structure from analysis outputs and file listings."""

    analysis = load_analysis_results(elab_id) or {}

    status = analysis.get("status") or analysis.get("analysis_status") or "pending"
    if status not in {"pending", "success", "failed"}:
        status = "failed"

    files_processed = analysis.get("files_processed")
    metadata_used = analysis.get("metadata", {}) or {}

    langmuir_fits_meta = metadata_used.get("langmuir_fits")
    if isinstance(langmuir_fits_meta, dict):
        langmuir_fits = langmuir_fits_meta
    else:
        langmuir_fits = {}

    # summary numbers from metadata if available
    num_ligand = metadata_used.get("num_ligand") or metadata_used.get(
        "number_of_ligand_concentrations"
    )
    num_salt = metadata_used.get("num_salt") or metadata_used.get(
        "number_of_salt_concentrations"
    )
    replicates = metadata_used.get("replicates")

    # Count fits per salt
    if isinstance(langmuir_fits, dict):
        langmuir_fits_per_salt = len(langmuir_fits)
    else:
        langmuir_fits_per_salt = 0

    # Data files and plots from analysis JSON
    data_outputs = analysis.get("data_outputs", {}) or {}
    plots_outputs = analysis.get("plots", {}) or {}

    # Also list files in results/ and analysis/ folders
    results_folder = Path("../results")
    analysis_folder = Path("../analysis")

    results_files = list_folder_files(results_folder)
    analysis_files = list_folder_files(analysis_folder)

    results_json_path = results_folder / f"analysis_results_{elab_id}.json"

    data_files = {
        "raw_tecan_excel": data_outputs.get("raw_tecan_excel"),
        "per_well_csv": data_outputs.get("per_well_csv"),
        "aggregated_csv": data_outputs.get("aggregated_csv"),
        "fit_parameters_csv": data_outputs.get("fit_parameters_csv"),
        "results_json": str(results_json_path.resolve())
        if results_json_path.exists()
        else None,
        "results_folder_listing": results_files,
        "analysis_folder_listing": analysis_files,
    }

    plots = {
        "isotherms_png": plots_outputs.get("isotherms_png"),
        "isotherms_pdf": plots_outputs.get("isotherms_pdf"),
    }

    results_struct = {
        "analysis_status": status,
        "analysis_timestamp": datetime.now(timezone.utc).isoformat(),
        "summary": {
            "files_processed": int(files_processed)
            if isinstance(files_processed, int)
            else 0,
            "num_ligand_concentrations": int(num_ligand)
            if isinstance(num_ligand, (int, float))
            else None,
            "num_salt_concentrations": int(num_salt)
            if isinstance(num_salt, (int, float))
            else None,
            "replicates": int(replicates)
            if isinstance(replicates, (int, float))
            else None,
            "langmuir_fits_per_salt": int(langmuir_fits_per_salt),
        },
        "metadata_used": metadata_used,
        "langmuir_fits": langmuir_fits,
        "data_files": data_files,
        "plots": plots,
        "raw_analysis_output": analysis,
    }

    return results_struct


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""

    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""

    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    row = cursor.fetchone()
    return row[0] if row else None


def main():
    parser = argparse.ArgumentParser(
        description=f"Commit {PROCESS_NAME} to database"
    )
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    conn = None
    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {})
        workflow_json, lab_id = load_workflow()

        metadata = extract_metadata(extra_fields)

        raw_data = build_raw_data(args.elab_id)
        results = build_results(args.elab_id)

        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": "completed",  # experiment execution status
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": metadata,
            "raw_data": raw_data,
            "results": results,
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(
            f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})"
        )
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if conn is not None:
            conn.rollback()
        return 1

    finally:
        if conn is not None:
            conn.close()


if __name__ == "__main__":
    sys.exit(main())