#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_run_id",
    "Pump Speed": "pump_speed",
    "Replicates": "replicates",
    "Resin Mass": "resin_mass_mg",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume_ul",
    "Venting time": "venting_time_s",
    "Pump Duration": "pump_duration_s",
    "Incubation Time": "incubation_time_min",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume_ul",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature_c",
    "Measurement Wavelength": "measurement_wavelength_nm",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation_rpm",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration_s",
    "Number of salt concentrations": "number_of_salt_concentrations",
    "Number of ligand concentrations": "number_of_ligand_concentrations",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Equilibration / loading buffer composition",
        },
        "salt_name": {
            "type": "string",
            "description": "Name or identity of the salt used in the isotherm experiment",
        },
        "process_run_id": {
            "type": "string",
            "description": "Identifier of the automated process run on the liquid handling system",
        },
        "pump_speed": {
            "type": "number",
            "description": "Pump speed used for liquid handling",
            "unit": "instrument units",
        },
        "replicates": {
            "type": "integer",
            "description": "Number of technical replicates per condition on the plate",
        },
        "resin_mass_mg": {
            "type": "number",
            "description": "Mass of chromatography resin loaded per well",
            "unit": "mg",
        },
        "ligand_name": {
            "type": "string",
            "description": "Name or identity of the ligand molecule",
        },
        "total_volume_ul": {
            "type": "number",
            "description": "Total liquid volume in each well during incubation",
            "unit": "µL",
        },
        "venting_time_s": {
            "type": "number",
            "description": "Venting time used in the automated protocol",
            "unit": "s",
        },
        "pump_duration_s": {
            "type": "number",
            "description": "Duration of pumping during loading or equilibration steps",
            "unit": "s",
        },
        "incubation_time_min": {
            "type": "number",
            "description": "Incubation time for achieving adsorption equilibrium",
            "unit": "min",
        },
        "salt_concentrations": {
            "type": "array",
            "description": "List of salt concentrations used in the isotherm experiment (as provided in metadata)",
            "items": {"type": "number"},
        },
        "equilibration_cycles": {
            "type": "integer",
            "description": "Number of column equilibration cycles performed before loading",
        },
        "equilibration_volume_ul": {
            "type": "number",
            "description": "Volume used per equilibration cycle",
            "unit": "µL",
        },
        "ligand_concentrations": {
            "type": "array",
            "description": "List of nominal ligand concentrations loaded onto the resin (as provided in metadata)",
            "items": {"type": "number"},
        },
        "incubation_temperature_c": {
            "type": "number",
            "description": "Incubation temperature during loading isotherm experiment",
            "unit": "°C",
        },
        "measurement_wavelength_nm": {
            "type": "number",
            "description": "Measurement wavelength used on the plate reader",
            "unit": "nm",
        },
        "calibration_curve_slope": {
            "type": "number",
            "description": "Slope of the linear calibration curve relating absorbance to ligand concentration",
            "unit": "Abs / ligand_concentration_unit",
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit for the salt concentrations, e.g. mM or mol/L",
        },
        "shaker_speed_incubation_rpm": {
            "type": "number",
            "description": "Shaker speed used during incubation",
            "unit": "rpm",
        },
        "salt_stock_concentration": {
            "type": "number",
            "description": "Concentration of the salt stock solution",
            "unit": "same as salt_concentration_unit",
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit for the ligand concentrations, e.g. µM or mg/mL",
        },
        "ligand_stock_concentration": {
            "type": "number",
            "description": "Concentration of the ligand stock solution",
            "unit": "same as ligand_concentration_unit",
        },
        "calibration_curve_intercept": {
            "type": "number",
            "description": "Intercept of the linear calibration curve (absorbance at zero concentration)",
            "unit": "Abs",
        },
        "equilibration_cycle_duration_s": {
            "type": "number",
            "description": "Duration of a single equilibration cycle",
            "unit": "s",
        },
        "number_of_salt_concentrations": {
            "type": "integer",
            "description": "Number of distinct salt concentrations used on the plate",
        },
        "number_of_ligand_concentrations": {
            "type": "integer",
            "description": "Number of distinct ligand concentrations used on the plate",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "success", "failed"],
            "description": "Status of the loading isotherm analysis as reported by the analysis script",
        },
        "analysis_message": {
            "type": "string",
            "description": "Human-readable message summarizing the outcome of the analysis",
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when the commit script packaged the analysis results",
        },
        "summary": {
            "type": "object",
            "description": "Key metrics extracted from Langmuir fits and plate statistics",
            "properties": {
                "num_ligand_conc": {
                    "type": "integer",
                    "description": "Number of ligand concentrations used (from analysis metadata)",
                },
                "num_salt_conc": {
                    "type": "integer",
                    "description": "Number of salt concentrations used (from analysis metadata)",
                },
                "replicates": {
                    "type": "integer",
                    "description": "Number of replicates per condition as used in analysis",
                },
                "num_wells_analyzed": {
                    "type": "integer",
                    "description": "Total number of wells with valid absorbance data used in analysis",
                },
                "num_groups": {
                    "type": "integer",
                    "description": "Number of (ligand, salt) condition groups after replicate aggregation",
                },
                "num_fits": {
                    "type": "integer",
                    "description": "Number of Langmuir fits attempted (one per salt concentration)",
                },
                "num_successful_fits": {
                    "type": "integer",
                    "description": "Number of Langmuir fits that returned finite parameters",
                },
                "r2_min": {
                    "type": "number",
                    "description": "Minimum R-squared among successful Langmuir fits",
                },
                "r2_max": {
                    "type": "number",
                    "description": "Maximum R-squared among successful Langmuir fits",
                },
                "r2_mean": {
                    "type": "number",
                    "description": "Mean R-squared among successful Langmuir fits",
                },
            },
        },
        "fits": {
            "type": "array",
            "description": "Per-salt Langmuir fit parameters as reconstructed from the CSV file (if available)",
            "items": {
                "type": "object",
                "properties": {
                    "salt_conc": {
                        "type": "number",
                        "description": "Salt concentration for this fit",
                    },
                    "q_max": {
                        "type": ["number", "null"],
                        "description": "Fitted q_max parameter",
                    },
                    "K": {
                        "type": ["number", "null"],
                        "description": "Fitted Langmuir binding constant K",
                    },
                    "R2": {
                        "type": ["number", "null"],
                        "description": "Coefficient of determination for the fit",
                    },
                    "warning": {
                        "type": ["string", "null"],
                        "description": "Warning or failure reason for this fit",
                    },
                },
            },
        },
        "warnings": {
            "type": "array",
            "description": "List of warnings emitted by the analysis script",
            "items": {"type": "string"},
        },
        "data_files": {
            "type": "object",
            "description": "Paths or filenames of main data output files produced by the analysis script",
            "properties": {
                "analysis_results_json": {
                    "type": "string",
                    "description": "Main analysis JSON summary file",
                },
                "raw_tecan_excel": {
                    "type": "string",
                    "description": "Path to raw Tecan Excel file used in analysis",
                },
                "well_level_csv": {
                    "type": "string",
                    "description": "CSV file with well-level data",
                },
                "aggregated_isotherm_csv": {
                    "type": "string",
                    "description": "CSV file with aggregated isotherm data",
                },
                "langmuir_fits_csv": {
                    "type": "string",
                    "description": "CSV file with Langmuir fit parameters",
                },
            },
        },
        "plots": {
            "type": "object",
            "description": "Plot files produced by the analysis script",
            "properties": {
                "loading_isotherms_png": {
                    "type": "string",
                    "description": "PNG figure with loading isotherms and Langmuir fits",
                }
            },
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "analysis_results_{elab_id}.json",
        "well_level_data_{elab_id}.csv",
        "aggregated_isotherm_data_{elab_id}.csv",
        "langmuir_fits_{elab_id}.csv",
        "tecan_data_{elab_id}.xlsx",
    ],
    "plots": [
        "loading_isotherms_{elab_id}.png",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        text = value.strip()
        if text == "":
            return None
        import re

        match = re.search(r"[-+]?\d*[,\.]?\d+", text)
        if match:
            num_str = match.group(0).replace(",", ".")
            try:
                return float(num_str)
            except ValueError:
                return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """

    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()
    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Check if this is actually a decimal comma case like "1,5"
            if sep == "," and len(parts) == 2:
                try:
                    _ = float(text.replace(",", "."))
                    # treat as single numeric value, not list
                    break
                except ValueError:
                    pass
            # Try to parse all parts as floats; if any fail, treat as strings
            all_numeric = True
            numeric_parts = []
            for p in parts:
                try:
                    numeric_parts.append(float(p.replace(",", ".")))
                except ValueError:
                    all_numeric = False
                    break
            if all_numeric:
                return numeric_parts
            return parts
    if field_type == "number":
        num = parse_numeric(text)
        return num if num is not None else text
    return text  # text stays text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields.

    Applies FIELD_MAPPING and uses parse_field with the eLab field's declared type.
    """
    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name in extra_fields:
            field = extra_fields[elab_name]
            value = field.get("value")
            field_type = field.get("type")  # 'number', 'text', etc.
            metadata[db_name] = parse_field(value, field_type=field_type)
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def _load_analysis_results(elab_id):
    """Load the main analysis_results_{elab_id}.json if it exists.

    Returns a tuple (results_dict_or_None, path_or_None).
    """
    results_folder = Path("../results")
    analysis_json_name = f"analysis_results_{elab_id}.json"
    analysis_path = results_folder / analysis_json_name
    if not analysis_path.exists():
        return None, None
    try:
        with open(analysis_path, "r") as f:
            data = json.load(f)
        return data, str(analysis_path.resolve())
    except Exception:
        return None, str(analysis_path.resolve())


def _safe_float(value):
    try:
        return float(value)
    except Exception:
        return None


def build_results(elab_id):
    """Build results JSONB structure.

    Uses the analysis_results_{elab_id}.json generated by the analysis script
    when available and augments it with file listings.
    """
    results_folder = Path("../results")
    analysis_data, analysis_json_path = _load_analysis_results(elab_id)

    now_iso = datetime.now(timezone.utc).isoformat()

    # Defaults if no analysis JSON is available
    results = {
        "analysis_status": "pending",
        "analysis_message": "Analysis results JSON not found.",
        "timestamp": now_iso,
        "summary": {},
        "fits": [],
        "warnings": [],
        "data_files": {},
        "plots": {},
    }

    if analysis_data is not None:
        status = analysis_data.get("status") or "pending"
        results["analysis_status"] = status
        results["analysis_message"] = analysis_data.get("message", "")
        results["warnings"] = analysis_data.get("warnings", [])

        meta = analysis_data.get("metadata", {}) or {}
        summary = {}
        for key in ("num_ligand_conc", "num_salt_conc", "replicates"):
            if key in meta:
                try:
                    summary[key] = int(meta[key])
                except Exception:
                    pass

        # Attempt to reconstruct fit statistics from langmuir_fits CSV if present
        fits_csv_name = f"langmuir_fits_{elab_id}.csv"
        fits_csv_path = results_folder / fits_csv_name
        fits = []
        if fits_csv_path.exists():
            try:
                import csv

                with open(fits_csv_path, newline="") as csvfile:
                    reader = csv.DictReader(csvfile)
                    for row in reader:
                        fit_entry = {
                            "salt_conc": _safe_float(row.get("salt_conc")),
                            "q_max": _safe_float(row.get("q_max"))
                            if row.get("q_max") not in ("", None)
                            else None,
                            "K": _safe_float(row.get("K"))
                            if row.get("K") not in ("", None)
                            else None,
                            "R2": _safe_float(row.get("R2"))
                            if row.get("R2") not in ("", None)
                            else None,
                            "warning": row.get("warning"),
                        }
                        fits.append(fit_entry)
            except Exception as e:
                results["warnings"].append(f"Failed to parse Langmuir fits CSV: {e}")

        results["fits"] = fits

        if fits:
            r2_values = [
                f["R2"] for f in fits if isinstance(f.get("R2"), (int, float, float))
            ]
            r2_values = [v for v in r2_values if v is not None]
            if r2_values:
                summary["num_fits"] = len(fits)
                summary["num_successful_fits"] = len(r2_values)
                summary["r2_min"] = min(r2_values)
                summary["r2_max"] = max(r2_values)
                summary["r2_mean"] = sum(r2_values) / len(r2_values)

        results["summary"] = summary

        # Data files from analysis JSON
        data_files = {}
        if analysis_json_path:
            data_files["analysis_results_json"] = analysis_json_path
        data_outputs = analysis_data.get("data_outputs", {}) or {}
        if "raw_tecan_excel" in data_outputs:
            data_files["raw_tecan_excel"] = data_outputs["raw_tecan_excel"]
        if "well_level_csv" in data_outputs:
            data_files["well_level_csv"] = data_outputs["well_level_csv"]
        if "aggregated_isotherm_csv" in data_outputs:
            data_files["aggregated_isotherm_csv"] = data_outputs[
                "aggregated_isotherm_csv"
            ]
        if "langmuir_fits_csv" in data_outputs:
            data_files["langmuir_fits_csv"] = data_outputs["langmuir_fits_csv"]

        results["data_files"] = data_files

        # Plots
        plots = {}
        plots_dict = analysis_data.get("plots", {}) or {}
        if "loading_isotherms_png" in plots_dict:
            plots["loading_isotherms_png"] = plots_dict["loading_isotherms_png"]
        else:
            plot_path = results_folder / f"loading_isotherms_{elab_id}.png"
            if plot_path.exists():
                plots["loading_isotherms_png"] = str(plot_path.resolve())
        results["plots"] = plots

    else:
        # No analysis JSON; we can still expose expected filenames if they exist
        data_files = {}
        if analysis_json_path:
            data_files["analysis_results_json"] = analysis_json_path
        for name in [
            f"well_level_data_{elab_id}.csv",
            f"aggregated_isotherm_data_{elab_id}.csv",
            f"langmuir_fits_{elab_id}.csv",
            f"tecan_data_{elab_id}.xlsx",
        ]:
            path = results_folder / name
            if path.exists():
                key = name.replace(f"_{elab_id}", "").rsplit(".", 1)[0]
                data_files[key] = str(path.resolve())
        results["data_files"] = data_files
        plot_path = results_folder / f"loading_isotherms_{elab_id}.png"
        if plot_path.exists():
            results["plots"] = {"loading_isotherms_png": str(plot_path.resolve())}

    return results


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""
    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    return cursor.fetchone()[0]


def main():
    parser = argparse.ArgumentParser(
        description=f"Commit {PROCESS_NAME} to database"
    )
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {})
        workflow_json, lab_id = load_workflow()

        # Build data structures
        metadata = extract_metadata(extra_fields)
        raw_data = build_raw_data(args.elab_id)
        results = build_results(args.elab_id)

        status = (
            "completed"
            if results.get("analysis_status") in ("success", "failed")
            else "pending"
        )

        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": status,
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": metadata,
            "raw_data": raw_data,
            "results": results,
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(
            f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})"
        )
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if "conn" in locals():
            conn.rollback()
        return 1
    finally:
        if "conn" in locals():
            conn.close()


if __name__ == "__main__":
    sys.exit(main())