#!/usr/bin/env python3
"""
Database commit script for ÄKTA - Gradient Elution (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import re
import argparse
from pathlib import Path
from datetime import datetime, timezone

import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 36
PROCESS_NAME = "ÄKTA - Gradient Elution (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Process ID": "process_id",
    "CIP_DURATION": "cip_duration",
    "WASH_DURATION": "wash_duration",
    "CIP_3_DURATION": "cip_3_duration",
    "CIP_4_DURATION": "cip_4_duration",
    "CIP_5_DURATION": "cip_5_duration",
    "WASH_FLOW_RATE": "wash_flow_rate",
    "CIP_2_HOLD_DURATION": "cip_2_hold_duration",
    "LOAD_INJECT_DURATION": "load_inject_duration",
    "LOAD_INJECT_FLOW_RATE": "load_inject_flow_rate",
    "EQUILIBRATION_DURATION": "equilibration_duration",
    "ELUTE_GRADIENT_DURATION": "elute_gradient_duration",
    "EQUILIBRATION_FLOW_RATE": "equilibration_flow_rate",
    "ELUTE_GRADIENT_GRADIENT_END": "elute_gradient_gradient_end",
    "ELUTE_GRADIENT_GRADIENT_START": "elute_gradient_gradient_start",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "process_id": {
            "type": "integer",
            "description": "Process identifier from eLabFTW metadata"
        },
        "cip_duration": {
            "type": "number",
            "description": "Duration of the main CIP step",
            "unit": "s"
        },
        "wash_duration": {
            "type": "number",
            "description": "Duration of the wash step",
            "unit": "s"
        },
        "cip_3_duration": {
            "type": "number",
            "description": "Duration of CIP step 3",
            "unit": "s"
        },
        "cip_4_duration": {
            "type": "number",
            "description": "Duration of CIP step 4",
            "unit": "s"
        },
        "cip_5_duration": {
            "type": "number",
            "description": "Duration of CIP step 5",
            "unit": "s"
        },
        "wash_flow_rate": {
            "type": "number",
            "description": "Flow rate during the wash step",
            "unit": "mL/min"
        },
        "cip_2_hold_duration": {
            "type": "number",
            "description": "Hold duration during CIP step 2",
            "unit": "s"
        },
        "load_inject_duration": {
            "type": "number",
            "description": "Duration of the load injection step",
            "unit": "s"
        },
        "load_inject_flow_rate": {
            "type": "number",
            "description": "Flow rate during sample loading/injection",
            "unit": "mL/min"
        },
        "equilibration_duration": {
            "type": "number",
            "description": "Duration of the equilibration step",
            "unit": "s"
        },
        "elute_gradient_duration": {
            "type": "number",
            "description": "Duration of the elution gradient step",
            "unit": "s"
        },
        "equilibration_flow_rate": {
            "type": "number",
            "description": "Flow rate during equilibration",
            "unit": "mL/min"
        },
        "elute_gradient_gradient_end": {
            "type": "number",
            "description": "End value of the elution gradient",
            "unit": "%"
        },
        "elute_gradient_gradient_start": {
            "type": "number",
            "description": "Start value of the elution gradient",
            "unit": "%"
        }
    }
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "completed", "failed", "success"],
            "description": "Overall status of the analysis and result collection"
        },
        "timestamp": {
            "type": "string",
            "description": "Timestamp when results were collected"
        },
        "message": {
            "type": "string",
            "description": "Analysis summary or error message"
        },
        "files_processed": {
            "type": "integer",
            "description": "Number of AKTA data files processed"
        },
        "summary": {
            "type": "object",
            "description": "Key AKTA chromatogram analysis metrics",
            "properties": {
                "num_peaks": {
                    "type": "integer",
                    "description": "Number of UV peaks detected"
                },
                "has_conductivity": {
                    "type": "boolean",
                    "description": "Whether conductivity data was available"
                },
                "first_peak_retention_time_min": {
                    "type": ["number", "null"],
                    "description": "Retention time of the first detected peak",
                    "unit": "min"
                },
                "max_peak_height_mau": {
                    "type": ["number", "null"],
                    "description": "Maximum detected UV peak height",
                    "unit": "mAU"
                }
            }
        },
        "peak_analysis": {
            "type": "object",
            "description": "Detailed detected peak information",
            "properties": {
                "num_peaks": {
                    "type": "integer",
                    "description": "Number of peaks detected"
                },
                "peaks": {
                    "type": "array",
                    "description": "List of detected chromatogram peaks",
                    "items": {
                        "type": "object",
                        "properties": {
                            "peak_index": {
                                "type": "integer",
                                "description": "Index of the peak in the valid signal array"
                            },
                            "retention_time_s": {
                                "type": "number",
                                "description": "Peak retention time",
                                "unit": "s"
                            },
                            "retention_time_min": {
                                "type": "number",
                                "description": "Peak retention time",
                                "unit": "min"
                            },
                            "peak_height_mAU": {
                                "type": "number",
                                "description": "Peak height in the UV280 trace",
                                "unit": "mAU"
                            },
                            "prominence_mAU": {
                                "type": ["number", "null"],
                                "description": "Peak prominence in the UV280 trace",
                                "unit": "mAU"
                            }
                        }
                    }
                }
            }
        },
        "data_files": {
            "type": "object",
            "description": "Produced data output files"
        },
        "plots": {
            "type": "object",
            "description": "Produced plot files"
        }
    }
}

EXPECTED_FILES = {
    "data": [
        "analysis_results_{elab_id}.json",
        "akta_results_{elab_id}.json",
        "processed_chromatogram_{elab_id}.csv"
    ],
    "plots": [
        "chromatogram_{elab_id}.png",
        "chromatogram_{elab_id}.pdf"
    ]
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================

def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025")
    )

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def parse_numeric(value):
    """Extract numeric value from strings like '25 °C' or '100 mM'."""
    if value is None:
        return None
    if isinstance(value, bool):
        return value
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return value
    if isinstance(value, str):
        s = value.strip()
        if s == "":
            return None
        match = re.search(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", s)
        if match:
            num = float(match.group())
            if num.is_integer():
                return int(num)
            return num
    return None

def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    candidates = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for path in candidates:
        if path.exists():
            return path
    raise FileNotFoundError(
        f"Experiment JSON not found for {elab_id}. Checked: "
        f"{', '.join(str(p) for p in candidates)}"
    )

def load_json_file(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if not workflow_path.exists():
        return None, None
    data = load_json_file(workflow_path)
    lab_id = data.get("lab_id")
    if lab_id is None:
        lab_id = data.get("labId")
    return data, lab_id

def normalize_value(db_name, raw_value):
    """Normalize field values based on expected schema semantics."""
    numeric_value = parse_numeric(raw_value)
    if numeric_value is not None:
        if db_name == "process_id":
            try:
                return int(numeric_value)
            except Exception:
                return numeric_value
        return numeric_value

    if isinstance(raw_value, str):
        stripped = raw_value.strip()
        return stripped if stripped != "" else None

    return raw_value

def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields."""
    metadata = {}
    if not isinstance(extra_fields, dict):
        return metadata

    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name not in extra_fields:
            continue

        field_obj = extra_fields.get(elab_name)
        if isinstance(field_obj, dict):
            raw_value = field_obj.get("value")
            unit = field_obj.get("unit")
        else:
            raw_value = field_obj
            unit = None

        value = normalize_value(db_name, raw_value)
        if value is not None:
            metadata[db_name] = value

        if unit:
            unit_key = f"{db_name}_unit"
            metadata[unit_key] = unit

    return metadata

def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if not folder.exists() or not folder.is_dir():
        return []
    return sorted([f.name for f in folder.iterdir() if f.is_file()])

def build_raw_data():
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder)
    }

def load_analysis_results_file(elab_id):
    """Load analysis_results_{elab_id}.json if present."""
    candidates = [
        Path("../results") / f"analysis_results_{elab_id}.json",
        Path("../analysis") / f"analysis_results_{elab_id}.json",
    ]
    for path in candidates:
        if path.exists():
            return load_json_file(path), path
    return None, None

def categorize_result_files(folder):
    """Split folder files into likely data files and plot files."""
    data_files = {}
    plot_files = {}
    if not folder.exists() or not folder.is_dir():
        return data_files, plot_files

    for f in sorted(folder.iterdir()):
        if not f.is_file():
            continue
        suffix = f.suffix.lower()
        if suffix in [".png", ".pdf", ".svg", ".jpg", ".jpeg"]:
            plot_files[f.stem] = f.name
        else:
            data_files[f.stem] = f.name
    return data_files, plot_files

def build_results(elab_id):
    """Build results JSONB structure from analysis outputs."""
    results_folder = Path("../results")
    analysis_folder = Path("../analysis")

    analysis_json, analysis_json_path = load_analysis_results_file(elab_id)

    result_data_files, result_plot_files = categorize_result_files(results_folder)
    analysis_data_files, analysis_plot_files = categorize_result_files(analysis_folder)

    combined_data_files = {}
    combined_data_files.update(analysis_data_files)
    combined_data_files.update(result_data_files)

    combined_plot_files = {}
    combined_plot_files.update(analysis_plot_files)
    combined_plot_files.update(result_plot_files)

    results = {
        "analysis_status": "pending",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "message": "",
        "files_processed": 0,
        "summary": {
            "num_peaks": 0,
            "has_conductivity": False,
            "first_peak_retention_time_min": None,
            "max_peak_height_mau": None
        },
        "peak_analysis": {
            "num_peaks": 0,
            "peaks": []
        },
        "data_files": combined_data_files,
        "plots": combined_plot_files
    }

    if analysis_json:
        status = analysis_json.get("status", "pending")
        if status == "success":
            db_status = "completed"
        elif status == "failed":
            db_status = "failed"
        else:
            db_status = status

        peaks = analysis_json.get("peak_analysis", {}).get("peaks", []) or []
        num_peaks = analysis_json.get("peak_analysis", {}).get("num_peaks", len(peaks))
        first_peak_rt = peaks[0].get("retention_time_min") if peaks else None

        max_peak_height = None
        if peaks:
            heights = [p.get("peak_height_mAU") for p in peaks if p.get("peak_height_mAU") is not None]
            if heights:
                max_peak_height = max(heights)

        has_conductivity = False
        processed_csv = analysis_json.get("data_outputs", {}).get("processed_csv")
        akta_json = analysis_json.get("data_outputs", {}).get("akta_results_json")
        if akta_json:
            try:
                akta_path = Path(akta_json)
                if not akta_path.is_absolute():
                    akta_path = (Path(".") / akta_path).resolve()
                if akta_path.exists():
                    akta_data = load_json_file(akta_path)
                    has_conductivity = "cond" in akta_data
            except Exception:
                has_conductivity = False

        results.update({
            "analysis_status": db_status,
            "message": analysis_json.get("message", ""),
            "files_processed": analysis_json.get("files_processed", 0),
            "summary": {
                "num_peaks": num_peaks,
                "has_conductivity": has_conductivity,
                "first_peak_retention_time_min": first_peak_rt,
                "max_peak_height_mau": max_peak_height
            },
            "peak_analysis": analysis_json.get("peak_analysis", {"num_peaks": 0, "peaks": []})
        })

        data_outputs = analysis_json.get("data_outputs", {})
        plots = analysis_json.get("plots", {})

        for key, value in data_outputs.items():
            if value:
                results["data_files"][key] = Path(value).name

        for key, value in plots.items():
            if value:
                results["plots"][key] = Path(value).name

        if analysis_json_path:
            results["data_files"]["analysis_results_json"] = analysis_json_path.name

    else:
        if combined_data_files or combined_plot_files:
            results["analysis_status"] = "completed"

    return results

def parse_datetime(value):
    """Best-effort parsing of datetime strings from eLabFTW JSON."""
    if not value:
        return None
    if isinstance(value, datetime):
        return value
    if not isinstance(value, str):
        return None

    text = value.strip()
    if not text:
        return None

    candidates = [
        text,
        text.replace("Z", "+00:00"),
    ]
    for candidate in candidates:
        try:
            return datetime.fromisoformat(candidate)
        except Exception:
            pass

    formats = [
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d %H:%M",
        "%Y-%m-%d",
    ]
    for fmt in formats:
        try:
            return datetime.strptime(text, fmt)
        except Exception:
            pass
    return None

def infer_execution_status(results):
    status = results.get("analysis_status", "pending")
    if status == "success":
        return "completed"
    return status

# ============================================================================
# MAIN FUNCTIONS
# ============================================================================

def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute("""
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files, description
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            description = EXCLUDED.description,
            updated_at = NOW()
    """, (
        PROCESS_ID,
        PROCESS_NAME,
        PROCESS_VERSION,
        json.dumps(METADATA_SCHEMA),
        json.dumps(RESULTS_SCHEMA),
        json.dumps(FIELD_MAPPING),
        json.dumps(EXPECTED_FILES),
        "Automated ÄKTA gradient elution process with chromatogram peak detection and plotting."
    ))

def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""
    cursor.execute("""
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", started_at, completed_at,
            workflow_json, metadata, raw_data, results, comments
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """, (
        elab_id,
        data["title"],
        PROCESS_ID,
        PROCESS_NAME,
        data["lab_id"],
        data["status"],
        data["user"],
        data["started_at"],
        data["completed_at"],
        json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
        json.dumps(data["metadata"]),
        json.dumps(data["raw_data"]),
        json.dumps(data["results"]),
        data["comments"]
    ))
    row = cursor.fetchone()
    return row[0] if row else None

def main():
    parser = argparse.ArgumentParser(description=f"Commit {PROCESS_NAME} to database")
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument("--dry-run", action="store_true", help="Don't commit, just show what would be done")
    parser.add_argument("--init-schema-only", action="store_true", help="Only initialize process schema")
    args = parser.parse_args()

    conn = None

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        upsert_process_schema(cursor)
        print(f"✓ Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            if args.dry_run:
                print("DRY RUN - Schema initialization only; no database commit performed.")
                conn.rollback()
            else:
                conn.commit()
                print("Schema-only mode, skipping experiment data.")
            return 0

        exp_json_path = find_experiment_json(args.elab_id)
        exp_data = load_json_file(exp_json_path)

        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {})
        workflow_json, lab_id = load_workflow()
        metadata = extract_metadata(extra_fields)
        raw_data = build_raw_data()
        results = build_results(args.elab_id)

        title = exp_data.get("title", "")
        user_value = (
            exp_data.get("userid_human")
            or exp_data.get("fullname")
            or exp_data.get("user")
            or ""
        )

        started_at = (
            parse_datetime(exp_data.get("started_at"))
            or parse_datetime(exp_data.get("start_time"))
            or parse_datetime(exp_data.get("created_at"))
            or parse_datetime(exp_data.get("date"))
        )

        completed_at = (
            parse_datetime(exp_data.get("completed_at"))
            or parse_datetime(exp_data.get("finish_time"))
            or parse_datetime(exp_data.get("updated_at"))
        )

        comments = exp_data.get("body") or exp_data.get("comments") or None
        status = infer_execution_status(results)

        data = {
            "title": title,
            "lab_id": lab_id,
            "status": status,
            "user": user_value,
            "started_at": started_at,
            "completed_at": completed_at,
            "workflow_json": workflow_json,
            "metadata": metadata,
            "raw_data": raw_data,
            "results": results,
            "comments": comments
        }

        if args.dry_run:
            print("DRY RUN - Would upsert process schema and experiment execution with:")
            print(json.dumps({
                "elab_id": args.elab_id,
                "experiment_json_path": str(exp_json_path),
                "payload": data
            }, indent=2, default=str))
            conn.rollback()
            return 0

        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(f"✓ Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})")
        return 0

    except Exception as e:
        print(f"✗ Error: {e}", file=sys.stderr)
        if conn is not None:
            try:
                conn.rollback()
            except Exception:
                pass
        return 1

    finally:
        if conn is not None:
            try:
                conn.close()
            except Exception:
                pass

if __name__ == "__main__":
    sys.exit(main())