#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_id_metadata",
    "Pump Speed": "pump_speed",
    "Replicates": "replicates",
    "Resin Mass": "resin_mass_mg",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume_uL",
    "Venting time": "venting_time_s",
    "Pump Duration": "pump_duration_s",
    "Incubation Time": "incubation_time_min",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume_uL",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature_c",
    "Measurement Wavelength": "measurement_wavelength_nm",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation_rpm",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration_s",
    "Number of salt concentrations": "number_salt_concentrations",
    "Number of ligand concentrations": "number_ligand_concentrations",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Buffer solution used during loading and equilibration.",
        },
        "salt_name": {
            "type": "string",
            "description": "Name or identity of the salt used in the isotherm.",
        },
        "process_id_metadata": {
            "type": "string",
            "description": "Process identifier as recorded in eLabFTW metadata.",
        },
        "pump_speed": {
            "type": "number",
            "description": "Pump speed used during loading (as configured in automation script).",
            "unit": "arbitrary units",
        },
        "replicates": {
            "type": "integer",
            "description": "Number of replicate wells per (ligand, salt) condition.",
        },
        "resin_mass_mg": {
            "type": "number",
            "description": "Resin mass used per condition.",
            "unit": "mg",
        },
        "ligand_name": {
            "type": "string",
            "description": "Ligand or protein name whose loading is characterized.",
        },
        "total_volume_uL": {
            "type": "number",
            "description": "Total liquid volume per well used for loading.",
            "unit": "µL",
        },
        "venting_time_s": {
            "type": "number",
            "description": "Venting time configured in the automation protocol.",
            "unit": "s",
        },
        "pump_duration_s": {
            "type": "number",
            "description": "Pump duration during loading step.",
            "unit": "s",
        },
        "incubation_time_min": {
            "type": "number",
            "description": "Incubation time for the loading isotherm.",
            "unit": "min",
        },
        "salt_concentrations": {
            "type": "array",
            "description": "List of salt concentrations used.",
            "items": {"type": "number"},
        },
        "equilibration_cycles": {
            "type": "integer",
            "description": "Number of equilibration cycles performed on resin.",
        },
        "equilibration_volume_uL": {
            "type": "number",
            "description": "Volume used per equilibration cycle.",
            "unit": "µL",
        },
        "ligand_concentrations": {
            "type": "array",
            "description": "List of initial ligand concentrations used.",
            "items": {"type": "number"},
        },
        "incubation_temperature_c": {
            "type": "number",
            "description": "Incubation temperature during loading.",
            "unit": "°C",
        },
        "measurement_wavelength_nm": {
            "type": "number",
            "description": "Measurement wavelength of plate reader.",
            "unit": "nm",
        },
        "calibration_curve_slope": {
            "type": "number",
            "description": "Slope of calibration curve used to convert absorbance to concentration.",
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit of salt concentrations (e.g. mM).",
        },
        "shaker_speed_incubation_rpm": {
            "type": "number",
            "description": "Shaker speed during incubation.",
            "unit": "rpm",
        },
        "salt_stock_concentration": {
            "type": "number",
            "description": "Stock concentration of salt solution.",
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit of ligand concentrations (e.g. µM, mg/mL).",
        },
        "ligand_stock_concentration": {
            "type": "number",
            "description": "Stock concentration of ligand solution.",
        },
        "calibration_curve_intercept": {
            "type": "number",
            "description": "Intercept of calibration curve used to convert absorbance to concentration.",
        },
        "equilibration_cycle_duration_s": {
            "type": "number",
            "description": "Duration of a single equilibration cycle.",
            "unit": "s",
        },
        "number_salt_concentrations": {
            "type": "integer",
            "description": "Number of distinct salt concentrations used in the plate layout.",
        },
        "number_ligand_concentrations": {
            "type": "integer",
            "description": "Number of distinct ligand concentrations used in the plate layout.",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "success", "failed"],
            "description": "Status of the loading isotherm analysis.",
        },
        "analysis_timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when results were committed to the database.",
        },
        "summary": {
            "type": "object",
            "description": "Key metrics aggregated from the analysis script output.",
            "properties": {
                "files_processed": {
                    "type": "integer",
                    "description": "Number of Tecan data files processed.",
                },
                "n_ligand_concentrations": {
                    "type": "integer",
                    "description": "Number of ligand concentrations in the analysis.",
                },
                "n_salt_concentrations": {
                    "type": "integer",
                    "description": "Number of salt concentrations in the analysis.",
                },
                "replicates": {
                    "type": "integer",
                    "description": "Replicates per (ligand, salt) condition used in analysis.",
                },
                "warnings": {
                    "type": "array",
                    "description": "List of non-fatal warnings raised during analysis.",
                    "items": {"type": "string"},
                },
            },
        },
        "tecan_metadata": {
            "type": "object",
            "description": "Subset of metadata returned by analysis script (e.g. calibration, units).",
        },
        "data_files": {
            "type": "object",
            "description": "Paths to processed data files generated by analysis script.",
            "properties": {
                "tecan_raw_excel": {"type": "string"},
                "wells_processed_csv": {"type": "string"},
                "isotherm_points_csv": {"type": "string"},
                "langmuir_fits_csv": {"type": "string"},
                "analysis_results_json": {"type": "string"},
            },
        },
        "plots": {
            "type": "object",
            "description": "Paths to plots generated during analysis.",
            "properties": {
                "isotherms_png": {"type": "string"},
                "isotherms_pdf": {"type": "string"},
            },
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "tecan_data_{elab_id}.xlsx",
        "wells_processed_{elab_id}.csv",
        "loading_isotherm_points_{elab_id}.csv",
        "langmuir_fits_{elab_id}.csv",
        "analysis_results_{elab_id}.json",
    ],
    "plots": [
        "loading_isotherms_{elab_id}.png",
        "loading_isotherms_{elab_id}.pdf",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        text = value.strip().replace(",", ".")
        import re

        match = re.search(r"[-+]?\d*\.?\d+", text)
        if match:
            try:
                return float(match.group())
            except ValueError:
                return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """
    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()
    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # attempt numeric list first
            all_numeric = True
            nums = []
            for p in parts:
                p_norm = p.replace(",", ".")
                try:
                    nums.append(float(p_norm))
                except ValueError:
                    all_numeric = False
                    break
            if all_numeric:
                return nums
            return parts
    if field_type == "number":
        parsed = parse_numeric(text)
        return parsed if parsed is not None else text
    return text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields."""
    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name in extra_fields:
            field = extra_fields[elab_name]
            value = field.get("value")
            field_type = field.get("type")
            parsed_value = parse_field(value, field_type=field_type)
            metadata[db_name] = parsed_value
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id):
    """Load analysis_results_<id>.json if it exists in ../results.

    Returns the parsed JSON dict or None if not present/invalid.
    """
    results_folder = Path("../results")
    results_json = results_folder / f"analysis_results_{elab_id}.json"
    if not results_json.exists():
        return None
    try:
        with open(results_json, "r") as f:
            return json.load(f)
    except Exception:
        return None


def build_results(elab_id):
    """Build results JSONB structure from analysis outputs.

    This function is process-specific and mirrors the structure produced by the
    analysis script while adapting it to the generic DB results schema.
    """
    analysis = load_analysis_results(elab_id)
    timestamp = datetime.now(timezone.utc).isoformat()

    results = {
        "analysis_status": "pending",
        "analysis_timestamp": timestamp,
        "summary": {},
        "tecan_metadata": {},
        "data_files": {},
        "plots": {},
    }

    results_folder = Path("../results").resolve()

    if analysis is None:
        # No dedicated analysis JSON; still list whatever files exist.
        results["analysis_status"] = "pending"
        all_files = list_folder_files(results_folder)
        results["data_files"]["all_results_files"] = [
            str(results_folder / f) for f in all_files
        ]
        return results

    # Map status
    status = analysis.get("status", "failed")
    if status not in ("success", "failed"):
        status = "failed"
    results["analysis_status"] = status

    # Summary from analysis
    files_processed = analysis.get("files_processed")
    metadata_block = analysis.get("metadata", {}) or {}
    warnings = analysis.get("warnings", []) or []

    results["summary"] = {
        "files_processed": int(files_processed)
        if isinstance(files_processed, int)
        else files_processed,
        "n_ligand_concentrations": metadata_block.get("n_ligand_concentrations"),
        "n_salt_concentrations": metadata_block.get("n_salt_concentrations"),
        "replicates": metadata_block.get("replicates"),
        "warnings": warnings,
    }

    # Store the full metadata block from analysis under tecan_metadata
    results["tecan_metadata"] = metadata_block

    # Data outputs
    data_outputs = analysis.get("data_outputs", {}) or {}
    data_files = {
        "tecan_raw_excel": data_outputs.get("tecan_raw_excel"),
        "wells_processed_csv": data_outputs.get("wells_processed_csv"),
        "isotherm_points_csv": data_outputs.get("isotherm_points_csv"),
        "langmuir_fits_csv": data_outputs.get("langmuir_fits_csv"),
        "analysis_results_json": str(
            (Path("../results") / f"analysis_results_{elab_id}.json").resolve()
        ),
    }
    results["data_files"] = {k: v for k, v in data_files.items() if v is not None}

    # Plots
    plots_block = analysis.get("plots", {}) or {}
    plots = {
        "isotherms_png": plots_block.get("isotherms_png"),
        "isotherms_pdf": plots_block.get("isotherms_pdf"),
    }
    results["plots"] = {k: v for k, v in plots.items() if v is not None}

    return results


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""
    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    return cursor.fetchone()[0]


def main():
    parser = argparse.ArgumentParser(
        description=f"Commit {PROCESS_NAME} to database"
    )
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get(
            "extra_fields", {}
        )
        workflow_json, lab_id = load_workflow()

        # Build data structures
        metadata = extract_metadata(extra_fields)
        raw_data = build_raw_data(args.elab_id)
        results = build_results(args.elab_id)

        status = "completed" if results.get("analysis_status") == "success" else "failed"

        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": status,
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": metadata,
            "raw_data": raw_data,
            "results": results,
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(
            f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})"
        )
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if "conn" in locals():
            conn.rollback()
        return 1
    finally:
        if "conn" in locals():
            conn.close()


if __name__ == "__main__":
    sys.exit(main())