#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_run_id",
    "Pump Speed": "pump_speed",
    "Replicates": "replicates",
    "Resin Mass": "resin_mass_mg",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume_ul",
    "Venting time": "venting_time_s",
    "Pump Duration": "pump_duration_s",
    "Incubation Time": "incubation_time_min",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume_ul",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature_c",
    "Measurement Wavelength": "measurement_wavelength_nm",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation_rpm",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration_s",
    "Number of salt concentrations": "number_of_salt_concentrations",
    "Number of ligand concentrations": "number_of_ligand_concentrations",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Buffer solution used during loading experiment."
        },
        "salt_name": {
            "type": "string",
            "description": "Name/identity of the salt used in the buffer.",
        },
        "process_run_id": {
            "type": "string",
            "description": "Identifier of the automated process run on the platform.",
        },
        "pump_speed": {
            "type": "string",
            "description": "Pump speed setting used for loading (units as in eLabFTW).",
        },
        "replicates": {
            "type": "integer",
            "description": "Number of replicate wells per ligand/salt condition.",
        },
        "resin_mass_mg": {
            "type": "number",
            "description": "Mass of resin used in the experiment.",
            "unit": "mg",
        },
        "ligand_name": {
            "type": "string",
            "description": "Name/identity of the ligand or protein loaded onto the resin.",
        },
        "total_volume_ul": {
            "type": "number",
            "description": "Total liquid volume per well in the loading experiment.",
            "unit": "µL",
        },
        "venting_time_s": {
            "type": "number",
            "description": "Venting time used during loading.",
            "unit": "s",
        },
        "pump_duration_s": {
            "type": "number",
            "description": "Duration for which the pump was running during loading.",
            "unit": "s",
        },
        "incubation_time_min": {
            "type": "number",
            "description": "Incubation time before measurement.",
            "unit": "min",
        },
        "salt_concentrations": {
            "type": "array",
            "description": "List of salt concentrations used in the experiment.",
            "items": {"type": "number"},
        },
        "equilibration_cycles": {
            "type": "integer",
            "description": "Number of equilibration cycles applied to the resin.",
        },
        "equilibration_volume_ul": {
            "type": "number",
            "description": "Equilibration volume per cycle.",
            "unit": "µL",
        },
        "ligand_concentrations": {
            "type": "array",
            "description": "List of ligand concentrations used in the experiment.",
            "items": {"type": "number"},
        },
        "incubation_temperature_c": {
            "type": "number",
            "description": "Incubation temperature.",
            "unit": "°C",
        },
        "measurement_wavelength_nm": {
            "type": "number",
            "description": "Wavelength used by the plate reader for absorbance measurement.",
            "unit": "nm",
        },
        "calibration_curve_slope": {
            "type": "number",
            "description": "Slope of the calibration curve converting absorbance to concentration.",
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit of the salt concentrations (e.g. mM).",
        },
        "shaker_speed_incubation_rpm": {
            "type": "number",
            "description": "Shaker speed during incubation.",
            "unit": "rpm",
        },
        "salt_stock_concentration": {
            "type": "number",
            "description": "Concentration of salt stock solution.",
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit of the ligand concentrations (e.g. µM, mg/mL).",
        },
        "ligand_stock_concentration": {
            "type": "number",
            "description": "Concentration of ligand stock solution.",
        },
        "calibration_curve_intercept": {
            "type": "number",
            "description": "Intercept of the calibration curve converting absorbance to concentration.",
        },
        "equilibration_cycle_duration_s": {
            "type": "number",
            "description": "Duration of each equilibration cycle.",
            "unit": "s",
        },
        "number_of_salt_concentrations": {
            "type": "integer",
            "description": "Number of distinct salt concentrations used.",
        },
        "number_of_ligand_concentrations": {
            "type": "integer",
            "description": "Number of distinct ligand concentrations used.",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "description": "Status of the Tecan loading isotherm analysis.",
            "enum": ["pending", "success", "failed"],
        },
        "analysis_timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when the analysis results were recorded to the database.",
        },
        "analysis_message": {
            "type": "string",
            "description": "Short human-readable summary of the analysis outcome.",
        },
        "experiment_id": {
            "type": "string",
            "description": "Experiment ID used by the analysis script.",
        },
        "warnings": {
            "type": "array",
            "description": "List of warning messages emitted during analysis.",
            "items": {"type": "string"},
        },
        "summary": {
            "type": "object",
            "description": "Summary metrics derived from the Langmuir fits and grouped data.",
            "properties": {
                "n_salt": {
                    "type": "integer",
                    "description": "Number of salt concentrations analyzed.",
                },
                "n_ligand": {
                    "type": "integer",
                    "description": "Number of ligand concentrations analyzed.",
                },
                "replicates": {
                    "type": "integer",
                    "description": "Number of replicates per condition.",
                },
                "best_r2": {
                    "type": "number",
                    "description": "Best Langmuir fit R^2 across all salt concentrations.",
                },
                "mean_r2": {
                    "type": "number",
                    "description": "Mean Langmuir fit R^2 across all salt concentrations.",
                },
            },
        },
        "data_outputs": {
            "type": "object",
            "description": "Key data output file paths produced by the analysis script.",
            "properties": {
                "tecan_raw_excel": {
                    "type": "string",
                    "description": "Path to the raw Tecan Excel file used for analysis.",
                },
                "plate_raw_with_mapping_csv": {
                    "type": "string",
                    "description": "CSV file with well-wise absorbance and condition mapping.",
                },
                "grouped_isotherm_csv": {
                    "type": "string",
                    "description": "CSV file with grouped isotherm data (cE_mean, q, etc.).",
                },
                "langmuir_fit_results_csv": {
                    "type": "string",
                    "description": "CSV file with per-salt Langmuir fit parameters and R^2.",
                },
                "analysis_results_json": {
                    "type": "string",
                    "description": "JSON file with the full analysis_results structure from the script.",
                },
            },
        },
        "plots": {
            "type": "object",
            "description": "Plot files generated by the analysis script.",
            "properties": {
                "loading_isotherms_png": {
                    "type": "string",
                    "description": "PNG plot of loading isotherms with Langmuir fits.",
                },
                "loading_isotherms_pdf": {
                    "type": "string",
                    "description": "PDF plot of loading isotherms with Langmuir fits.",
                },
            },
        },
        "raw_analysis": {
            "type": "object",
            "description": "Raw analysis_results dictionary loaded from analysis_results_*.json (if available).",
        },
        "results_folder_listing": {
            "type": "object",
            "description": "Listing of files present in the ../results folder at commit time.",
        },
        "analysis_folder_listing": {
            "type": "object",
            "description": "Listing of files present in the ../analysis folder at commit time.",
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "tecan_data_{elab_id}.xlsx",
        "plate_raw_with_mapping_{elab_id}.csv",
        "isotherm_grouped_{elab_id}.csv",
        "langmuir_fit_results_{elab_id}.csv",
        "analysis_results_{elab_id}.json",
    ],
    "plots": [
        "loading_isotherms_{elab_id}.png",
        "loading_isotherms_{elab_id}.pdf",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        txt = value.strip().replace(",", ".")
        if txt == "":
            return None
        import re

        match = re.search(r"[-+]?\d*\.?\d+", txt)
        if match:
            try:
                return float(match.group())
            except ValueError:
                return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """

    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()

    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Check if this could be a single number written with decimal comma like "1,5"
            if sep == "," and len(parts) == 2:
                joined = "".join(parts)
                try:
                    return float(joined)
                except ValueError:
                    pass
            # it's a list
            all_numeric = True
            numeric_parts = []
            for p in parts:
                p_norm = p.replace(",", ".")
                try:
                    numeric_parts.append(float(p_norm))
                except ValueError:
                    all_numeric = False
                    break
            if all_numeric:
                return numeric_parts
            return parts

    if field_type == "number":
        num = parse_numeric(text)
        return num if num is not None else text

    return text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            lab_id = data.get("lab_id") or data.get("labId")
            return data, lab_id
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields.

    Uses FIELD_MAPPING and respects eLabFTW field types when parsing numerics and arrays.
    """
    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name not in extra_fields:
            continue
        field = extra_fields[elab_name]
        value = field.get("value")
        field_type = field.get("type")
        parsed = parse_field(value, field_type=field_type)
        metadata[db_name] = parsed
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id):
    """Load analysis_results JSON if available and summarize key metrics.

    Returns a tuple (analysis_results_dict_or_None, summary_dict).
    """
    results_folder = Path("../results")
    analysis_file = results_folder / f"analysis_results_{elab_id}.json"
    if not analysis_file.exists():
        return None, {}

    try:
        with open(analysis_file, "r") as f:
            analysis = json.load(f)
    except Exception:
        return None, {}

    # Build a compact summary from the analysis dict
    metadata = analysis.get("metadata", {}) or {}
    fits_path = analysis.get("data_outputs", {}).get("langmuir_fit_results_csv")

    summary = {}
    try:
        # attempt to derive simple summary if langmuir_fit_results_csv exists
        if fits_path and Path(fits_path).exists():
            import csv

            r2_values = []
            with open(fits_path, newline="") as csvfile:
                reader = csv.DictReader(csvfile)
                for row in reader:
                    r2_str = row.get("R2")
                    if r2_str is None or r2_str == "":
                        continue
                    try:
                        r2 = float(r2_str)
                        if r2 == r2:  # not NaN
                            r2_values.append(r2)
                    except ValueError:
                        continue
            if r2_values:
                best_r2 = max(r2_values)
                mean_r2 = sum(r2_values) / len(r2_values)
            else:
                best_r2 = None
                mean_r2 = None
        else:
            best_r2 = None
            mean_r2 = None

        summary = {
            "n_salt": metadata.get("n_salt"),
            "n_ligand": metadata.get("n_ligand"),
            "replicates": metadata.get("replicates"),
            "best_r2": best_r2,
            "mean_r2": mean_r2,
        }
    except Exception:
        summary = {}

    return analysis, summary


def build_results(elab_id):
    """Build results JSONB structure by inspecting ../results and ../analysis.

    If an analysis_results_{elab_id}.json file exists, load and embed it.
    """
    results_base = Path("../results")
    analysis_base = Path("../analysis")

    # Load structured analysis JSON if available
    analysis_dict, summary = load_analysis_results(elab_id)

    # Determine status/message from analysis_dict if present
    if analysis_dict is not None:
        status = analysis_dict.get("status", "success")
        message = analysis_dict.get("message", "")
        warnings = analysis_dict.get("warnings", []) or []
        data_outputs_from_analysis = analysis_dict.get("data_outputs", {}) or {}
        plots_from_analysis = analysis_dict.get("plots", {}) or {}
    else:
        status = "pending"
        message = "No analysis_results JSON found; analysis may not have run yet."
        warnings = []
        data_outputs_from_analysis = {}
        plots_from_analysis = {}

    # Gather files present in results and analysis folders
    results_files = list_folder_files(results_base) if results_base.exists() else []
    analysis_files = list_folder_files(analysis_base) if analysis_base.exists() else []

    # Identify key expected files by name
    elab_str = str(elab_id)
    expected_map = {
        "tecan_raw_excel": f"tecan_data_{elab_str}.xlsx",
        "plate_raw_with_mapping_csv": f"plate_raw_with_mapping_{elab_str}.csv",
        "grouped_isotherm_csv": f"isotherm_grouped_{elab_str}.csv",
        "langmuir_fit_results_csv": f"langmuir_fit_results_{elab_str}.csv",
        "analysis_results_json": f"analysis_results_{elab_str}.json",
    }

    data_files = dict(data_outputs_from_analysis)  # start with analysis-produced paths
    for key, fname in expected_map.items():
        if key in data_files and data_files[key]:
            continue
        # Search for file in results folder
        if fname in results_files:
            data_files[key] = str((results_base / fname).resolve())

    plot_expected = {
        "loading_isotherms_png": f"loading_isotherms_{elab_str}.png",
        "loading_isotherms_pdf": f"loading_isotherms_{elab_str}.pdf",
    }

    plots = dict(plots_from_analysis)
    for key, fname in plot_expected.items():
        if key in plots and plots[key]:
            continue
        if fname in results_files:
            plots[key] = str((results_base / fname).resolve())

    results = {
        "analysis_status": status,
        "analysis_timestamp": datetime.now(timezone.utc).isoformat(),
        "analysis_message": message,
        "experiment_id": str(elab_id),
        "warnings": warnings,
        "summary": summary,
        "data_outputs": data_files,
        "plots": plots,
        "raw_analysis": analysis_dict if analysis_dict is not None else None,
        "results_folder_listing": {
            "folder_path": str(results_base.resolve()),
            "files": results_files,
        },
        "analysis_folder_listing": {
            "folder_path": str(analysis_base.resolve()),
            "files": analysis_files,
        },
    }

    return results


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""
    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] is not None else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    row = cursor.fetchone()
    return row[0] if row else None


def main():
    parser = argparse.ArgumentParser(
        description=f"Commit {PROCESS_NAME} to database"
    )
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {})
        workflow_json, lab_id = load_workflow()

        # Build data structures
        metadata = extract_metadata(extra_fields)
        raw_data = build_raw_data(args.elab_id)
        results = build_results(args.elab_id)

        status = "completed" if results.get("analysis_status") == "success" else "pending"

        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": status,
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": metadata,
            "raw_data": raw_data,
            "results": results,
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})")
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if "conn" in locals():
            conn.rollback()
        return 1
    finally:
        if "conn" in locals():
            conn.close()


if __name__ == "__main__":
    sys.exit(main())