#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_id_field",
    "Pump Speed": "pump_speed",
    "Replicates": "replicates",
    "Resin Mass": "resin_mass_mg",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume_uL",
    "Venting time": "venting_time_s",
    "Pump Duration": "pump_duration_s",
    "Incubation Time": "incubation_time_min",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume_uL",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature_c",
    "Measurement Wavelength": "measurement_wavelength_nm",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation_rpm",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration_s",
    "Number of salt concentrations": "num_salt_concentrations",
    "Number of ligand concentrations": "num_ligand_concentrations",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Buffer solution used during loading isotherm experiment.",
        },
        "salt_name": {
            "type": "string",
            "description": "Name/identity of the salt used in the experiment.",
        },
        "process_id_field": {
            "type": "string",
            "description": "Process identifier recorded in eLabFTW metadata (may differ from PROCESS_ID).",
        },
        "pump_speed": {
            "type": "string",
            "description": "Pump speed setting used for loading / equilibration steps (as entered in eLabFTW).",
        },
        "replicates": {
            "type": "integer",
            "description": "Number of replicate wells per (ligand, salt) condition on the plate.",
        },
        "resin_mass_mg": {
            "type": "number",
            "description": "Mass of resin used per condition.",
            "unit": "mg",
        },
        "ligand_name": {
            "type": "string",
            "description": "Name/identity of the ligand loaded onto the resin.",
        },
        "total_volume_uL": {
            "type": "number",
            "description": "Total liquid volume in each well used in the loading isotherm.",
            "unit": "uL",
        },
        "venting_time_s": {
            "type": "number",
            "description": "Duration of venting step during loading/equilibration.",
            "unit": "s",
        },
        "pump_duration_s": {
            "type": "number",
            "description": "Duration for which the pump was running per cycle.",
            "unit": "s",
        },
        "incubation_time_min": {
            "type": "number",
            "description": "Incubation time for the loading isotherm experiment.",
            "unit": "min",
        },
        "salt_concentrations": {
            "type": "array",
            "description": "List of salt concentrations used across the plate.",
            "items": {"type": "number"},
        },
        "equilibration_cycles": {
            "type": "integer",
            "description": "Number of equilibration cycles applied before measurement.",
        },
        "equilibration_volume_uL": {
            "type": "number",
            "description": "Volume used for each equilibration cycle.",
            "unit": "uL",
        },
        "ligand_concentrations": {
            "type": "array",
            "description": "List of initial ligand concentrations used in the plate layout.",
            "items": {"type": "number"},
        },
        "incubation_temperature_c": {
            "type": "number",
            "description": "Incubation temperature during loading isotherm.",
            "unit": "C",
        },
        "measurement_wavelength_nm": {
            "type": "number",
            "description": "Measurement wavelength for absorbance readout on the Tecan plate reader.",
            "unit": "nm",
        },
        "calibration_curve_slope": {
            "type": "number",
            "description": "Slope of the linear calibration curve relating absorbance to ligand concentration.",
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit of salt concentrations (e.g. mM).",
        },
        "shaker_speed_incubation_rpm": {
            "type": "number",
            "description": "Shaker speed during incubation.",
            "unit": "rpm",
        },
        "salt_stock_concentration": {
            "type": "number",
            "description": "Concentration of the salt stock solution used for dilutions.",
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit of ligand concentrations (e.g. uM).",
        },
        "ligand_stock_concentration": {
            "type": "number",
            "description": "Concentration of the ligand stock solution used for dilutions.",
        },
        "calibration_curve_intercept": {
            "type": "number",
            "description": "Intercept of the linear calibration curve relating absorbance to ligand concentration.",
        },
        "equilibration_cycle_duration_s": {
            "type": "number",
            "description": "Duration of a single equilibration cycle.",
            "unit": "s",
        },
        "num_salt_concentrations": {
            "type": "integer",
            "description": "Number of distinct salt concentrations used on the plate.",
        },
        "num_ligand_concentrations": {
            "type": "integer",
            "description": "Number of distinct ligand concentrations used on the plate.",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "success", "failed"],
            "description": "Status of the Tecan loading isotherm analysis.",
        },
        "analysis_timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "UTC timestamp when results were stored to the database.",
        },
        "summary": {
            "type": "object",
            "description": "Key metrics summarizing Langmuir fits across salt concentrations.",
            "properties": {
                "num_salt_concentrations": {
                    "type": "integer",
                    "description": "Number of salt concentrations included in the fit results.",
                },
                "num_ligand_concentrations": {
                    "type": "integer",
                    "description": "Number of ligand concentrations included in the analysis.",
                },
                "replicates": {
                    "type": "integer",
                    "description": "Number of replicate wells per condition (from analysis metadata).",
                },
                "n_points_total": {
                    "type": "integer",
                    "description": "Total number of (c0, salt) data points used for Langmuir fitting.",
                },
                "n_salt_fit_success": {
                    "type": "integer",
                    "description": "Number of salt concentrations where Langmuir fitting succeeded.",
                },
                "n_salt_fit_failed": {
                    "type": "integer",
                    "description": "Number of salt concentrations where Langmuir fitting failed.",
                },
                "qmax_mean": {
                    "type": "number",
                    "description": "Mean fitted qmax over successful salt conditions.",
                },
                "qmax_std": {
                    "type": "number",
                    "description": "Standard deviation of fitted qmax over successful salt conditions.",
                },
                "K_mean": {
                    "type": "number",
                    "description": "Mean fitted Langmuir affinity constant K over successful salt conditions.",
                },
                "K_std": {
                    "type": "number",
                    "description": "Standard deviation of fitted Langmuir affinity constant K over successful salt conditions.",
                },
                "r2_mean": {
                    "type": "number",
                    "description": "Mean R^2 of Langmuir fits over successful salt conditions.",
                },
                "r2_std": {
                    "type": "number",
                    "description": "Standard deviation of R^2 over successful salt conditions.",
                },
            },
        },
        "analysis_metadata": {
            "type": "object",
            "description": "Subset of analysis metadata returned by the analysis script.",
            "properties": {
                "num_ligand_concentrations": {"type": "integer"},
                "num_salt_concentrations": {"type": "integer"},
                "replicates": {"type": "integer"},
                "ligand_concentrations": {
                    "type": "array",
                    "items": {"type": "number"},
                },
                "salt_concentrations": {
                    "type": "array",
                    "items": {"type": "number"},
                },
                "ligand_concentration_unit": {"type": "string"},
                "salt_concentration_unit": {"type": "string"},
                "resin_mass_mg": {"type": "number"},
                "total_volume_uL": {"type": "number"},
                "calibration_slope": {"type": "number"},
                "calibration_intercept": {"type": "number"},
                "data_source": {"type": "string"},
            },
        },
        "data_files": {
            "type": "object",
            "description": "Output data file names and paths from the analysis script.",
            "properties": {
                "tecan_raw": {"type": "string"},
                "absorbance_matrix_csv": {"type": "string"},
                "equilibrium_concentrations_csv": {"type": "string"},
                "aggregated_cE_csv": {"type": "string"},
                "loading_q_csv": {"type": "string"},
                "langmuir_fit_results_csv": {"type": "string"},
                "analysis_results_json": {"type": "string"},
            },
        },
        "plots": {
            "type": "object",
            "description": "Generated plot file names and paths.",
            "properties": {
                "isotherms_png": {"type": "string"},
                "isotherms_pdf": {"type": "string"},
            },
        },
        "fit_results_per_salt": {
            "type": "array",
            "description": "Per-salt Langmuir fit parameters and quality metrics.",
            "items": {
                "type": "object",
                "properties": {
                    "salt_conc": {"type": "number"},
                    "qmax": {"type": "number"},
                    "K": {"type": "number"},
                    "r2": {"type": "number"},
                    "n_points": {"type": "integer"},
                    "success": {"type": "boolean"},
                    "message": {"type": "string"},
                },
            },
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "tecan_data_{elab_id}.xlsx",
        "absorbance_matrix_{elab_id}.csv",
        "equilibrium_concentrations_{elab_id}.csv",
        "aggregated_cE_{elab_id}.csv",
        "loading_q_{elab_id}.csv",
        "langmuir_fit_results_{elab_id}.csv",
        "analysis_results_{elab_id}.json",
    ],
    "plots": [
        "isotherms_{elab_id}.png",
        "isotherms_{elab_id}.pdf",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value: str):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    text = str(value).strip()
    import re

    match = re.search(r"[-+]?\d*\.?\d+", text.replace(",", "."))
    if match:
        try:
            return float(match.group())
        except ValueError:
            return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """

    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()

    # Detect delimited lists, but handle decimal commas like "1,5"
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Could this be a decimal comma like "1,5"? Then "1" and "5" -> "15" or "1.5"
            joined = "".join(parts)
            try:
                float(joined.replace(",", "."))
                # Looks like a decimal-comma number, treat as single value, break list logic
            except ValueError:
                # Treat as list
                all_numeric = True
                numeric_parts = []
                for p in parts:
                    try:
                        numeric_parts.append(float(p.replace(",", ".")))
                    except ValueError:
                        all_numeric = False
                        break
                if all_numeric:
                    return numeric_parts
                return parts

    if field_type == "number":
        num = parse_numeric(text)
        return num if num is not None else text
    return text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields."""
    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name in extra_fields:
            field = extra_fields[elab_name]
            value = field.get("value")
            field_type = field.get("type")
            parsed = parse_field(value, field_type=field_type)
            metadata[db_name] = parsed
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id: int):
    """Load analysis_results_{elab_id}.json if present."""
    results_dir = Path("../results")
    analysis_json = results_dir / f"analysis_results_{elab_id}.json"
    if analysis_json.exists():
        try:
            with open(analysis_json) as f:
                return json.load(f), str(analysis_json.resolve())
        except Exception:
            return None, None
    return None, None


def build_results(elab_id):
    """Build results JSONB structure from analysis outputs in ../results/."""
    results_folder = Path("../results")
    results_folder.mkdir(parents=True, exist_ok=True)

    analysis_data, analysis_json_path = load_analysis_results(elab_id)

    analysis_status = "pending"
    analysis_metadata = None
    data_files = {}
    plots = {}
    summary = {}
    fit_results_per_salt = []

    if analysis_data is not None:
        # The analysis script uses "status": "success" / "failed"
        analysis_status = analysis_data.get("status", "pending")
        analysis_metadata = analysis_data.get("metadata", {})
        data_outputs = analysis_data.get("data_outputs", {})
        plots_dict = analysis_data.get("plots", {})

        # Include the main analysis results JSON file
        if analysis_json_path:
            data_files["analysis_results_json"] = analysis_json_path

        # Add any paths the analysis script already recorded
        for key, path in data_outputs.items():
            data_files[key] = path

        # Extract plot paths (isotherms)
        isotherms = plots_dict.get("isotherms", {})
        png = isotherms.get("png")
        pdf = isotherms.get("pdf")
        if png:
            plots["isotherms_png"] = png
        if pdf:
            plots["isotherms_pdf"] = pdf

        # Parse per-salt Langmuir fit results from CSV if present
        fit_results_path = results_folder / f"langmuir_fit_results_{elab_id}.csv"
        if fit_results_path.exists():
            try:
                import csv

                with open(fit_results_path, newline="") as csvfile:
                    reader = csv.DictReader(csvfile)
                    for row in reader:
                        converted = {}
                        for k, v in row.items():
                            if v is None or v == "":
                                converted[k] = None
                                continue
                            try:
                                if k in {"salt_conc", "qmax", "K", "r2"}:
                                    converted[k] = float(v)
                                elif k in {"n_points"}:
                                    converted[k] = int(float(v))
                                elif k in {"success"}:
                                    converted[k] = str(v).lower() in {"true", "1", "yes"}
                                else:
                                    converted[k] = v
                            except Exception:
                                converted[k] = v
                        fit_results_per_salt.append(converted)
            except Exception:
                fit_results_per_salt = []

        # Build summary statistics if we have any fit results
        if fit_results_per_salt:
            import math

            successful = [fr for fr in fit_results_per_salt if fr.get("success")]
            n_success = len(successful)
            n_fail = len(fit_results_per_salt) - n_success

            def _stats(values):
                vals = [
                    v
                    for v in values
                    if isinstance(v, (int, float)) and math.isfinite(v)
                ]
                if not vals:
                    return None, None
                mean = sum(vals) / len(vals)
                if len(vals) > 1:
                    var = sum((x - mean) ** 2 for x in vals) / (len(vals) - 1)
                    std = math.sqrt(var)
                else:
                    std = 0.0
                return mean, std

            qmax_mean, qmax_std = _stats([fr.get("qmax") for fr in successful])
            K_mean, K_std = _stats([fr.get("K") for fr in successful])
            r2_mean, r2_std = _stats([fr.get("r2") for fr in successful])

            # Infer number of ligand/salt concentrations from equilibrium_concentrations CSV
            try:
                import csv

                eq_csv = results_folder / f"equilibrium_concentrations_{elab_id}.csv"
                ligand_vals = set()
                salt_vals = set()
                if eq_csv.exists():
                    with open(eq_csv, newline="") as csvfile:
                        reader = csv.DictReader(csvfile)
                        for row in reader:
                            if "c0" in row and row["c0"] != "":
                                try:
                                    ligand_vals.add(float(row["c0"]))
                                except Exception:
                                    pass
                            if "salt_conc" in row and row["salt_conc"] != "":
                                try:
                                    salt_vals.add(float(row["salt_conc"]))
                                except Exception:
                                    pass
                num_lig = len(ligand_vals) if ligand_vals else None
                num_salt = len(salt_vals) if salt_vals else None
            except Exception:
                num_lig = None
                num_salt = None

            total_points = sum(fr.get("n_points") or 0 for fr in fit_results_per_salt)

            summary = {
                "num_salt_concentrations": num_salt,
                "num_ligand_concentrations": num_lig,
                "replicates": analysis_metadata.get("replicates")
                if isinstance(analysis_metadata, dict)
                else None,
                "n_points_total": int(total_points),
                "n_salt_fit_success": n_success,
                "n_salt_fit_failed": n_fail,
                "qmax_mean": qmax_mean,
                "qmax_std": qmax_std,
                "K_mean": K_mean,
                "K_std": K_std,
                "r2_mean": r2_mean,
                "r2_std": r2_std,
            }

    results = {
        "analysis_status": analysis_status,
        "analysis_timestamp": datetime.now(timezone.utc).isoformat(),
        "summary": summary,
        "analysis_metadata": analysis_metadata,
        "data_files": data_files,
        "plots": plots,
        "fit_results_per_salt": fit_results_per_salt,
    }

    return results


# ============================================================================
# MAIN DB FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
        """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""
    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
        """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    return cursor.fetchone()[0]


# ============================================================================
# CLI
# ============================================================================


def main():
    parser = argparse.ArgumentParser(
        description=f"Commit {PROCESS_NAME} to database"
    )
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get(
            "extra_fields", {}
        )
        workflow_json, lab_id = load_workflow()

        # Build data structures
        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": "completed",
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": extract_metadata(extra_fields),
            "raw_data": build_raw_data(args.elab_id),
            "results": build_results(args.elab_id),
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(
            f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})"
        )
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if "conn" in locals():
            conn.rollback()
        return 1
    finally:
        if "conn" in locals():
            conn.close()


if __name__ == "__main__":
    sys.exit(main())