#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_run_id",
    "Pump Speed": "pump_speed",
    "Replicates": "replicates",
    "Resin Mass": "resin_mass",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume",
    "Venting time": "venting_time",
    "Pump Duration": "pump_duration",
    "Incubation Time": "incubation_time",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature",
    "Measurement Wavelength": "measurement_wavelength",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration",
    "Number of salt concentrations": "number_of_salt_concentrations",
    "Number of ligand concentrations": "number_of_ligand_concentrations",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Buffer solution used for resin loading",
        },
        "salt_name": {
            "type": "string",
            "description": "Name/identity of the salt in the loading buffer",
        },
        "process_run_id": {
            "type": "string",
            "description": "Identifier of the automated process run (as provided in eLabFTW)",
        },
        "pump_speed": {
            "type": "number",
            "description": "Pump speed used during loading (units as configured on instrument)",
        },
        "replicates": {
            "type": "integer",
            "description": "Number of replicate wells per condition on the plate",
        },
        "resin_mass": {
            "type": "number",
            "description": "Mass of resin used per condition",
            "unit": "mg",
        },
        "ligand_name": {
            "type": "string",
            "description": "Name/identity of the ligand loaded onto the resin",
        },
        "total_volume": {
            "type": "number",
            "description": "Total volume of ligand solution per well",
            "unit": "uL",
        },
        "venting_time": {
            "type": "number",
            "description": "Venting time during loading step",
            "unit": "s",
        },
        "pump_duration": {
            "type": "number",
            "description": "Total pump duration for loading",
            "unit": "s",
        },
        "incubation_time": {
            "type": "number",
            "description": "Incubation time after loading before measurement",
            "unit": "min",
        },
        "salt_concentrations": {
            "type": "array",
            "description": "List of salt concentrations used on the plate (ordering matches columns)",
            "items": {"type": "number"},
        },
        "equilibration_cycles": {
            "type": "integer",
            "description": "Number of equilibration cycles before loading",
        },
        "equilibration_volume": {
            "type": "number",
            "description": "Equilibration volume per cycle",
            "unit": "uL",
        },
        "ligand_concentrations": {
            "type": "array",
            "description": "List of initial ligand concentrations used on the plate (ordering matches rows)",
            "items": {"type": "number"},
        },
        "incubation_temperature": {
            "type": "number",
            "description": "Incubation temperature during loading",
            "unit": "°C",
        },
        "measurement_wavelength": {
            "type": "number",
            "description": "Measurement wavelength of plate reader",
            "unit": "nm",
        },
        "calibration_curve_slope": {
            "type": "number",
            "description": "Slope of the calibration curve converting absorbance to concentration",
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit for salt concentrations (e.g. mM)",
        },
        "shaker_speed_incubation": {
            "type": "number",
            "description": "Shaker speed during incubation",
            "unit": "rpm",
        },
        "salt_stock_concentration": {
            "type": "number",
            "description": "Stock concentration of salt solution",
            "unit": "(same as salt_concentration_unit)",
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit for ligand concentrations (e.g. mM, µM)",
        },
        "ligand_stock_concentration": {
            "type": "number",
            "description": "Stock concentration of ligand solution",
            "unit": "(same as ligand_concentration_unit)",
        },
        "calibration_curve_intercept": {
            "type": "number",
            "description": "Intercept of the calibration curve converting absorbance to concentration",
        },
        "equilibration_cycle_duration": {
            "type": "number",
            "description": "Duration of a single equilibration cycle",
            "unit": "s",
        },
        "number_of_salt_concentrations": {
            "type": "integer",
            "description": "Number of distinct salt concentrations on the plate",
        },
        "number_of_ligand_concentrations": {
            "type": "integer",
            "description": "Number of distinct ligand concentrations on the plate",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "success", "failed"],
            "description": "Status of the Tecan loading isotherm analysis",
        },
        "analysis_timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when results were committed to the database",
        },
        "message": {
            "type": "string",
            "description": "Human-readable message summarizing analysis outcome",
        },
        "summary": {
            "type": "object",
            "description": "Key metrics aggregated from analysis outputs",
            "properties": {
                "n_points_raw": {
                    "type": "integer",
                    "description": "Number of raw well-level data points extracted from the plate",
                },
                "n_points_aggregated": {
                    "type": "integer",
                    "description": "Number of aggregated (c0, salt) combinations",
                },
                "n_salt_conditions": {
                    "type": "integer",
                    "description": "Number of salt concentrations fitted",
                },
                "qmax_values": {
                    "type": "array",
                    "description": "List of fitted qmax values across salt conditions (may contain nulls if fit failed)",
                    "items": {"type": ["number", "null"]},
                },
                "K_values": {
                    "type": "array",
                    "description": "List of fitted Langmuir affinity constants K across salt conditions (may contain nulls)",
                    "items": {"type": ["number", "null"]},
                },
                "R2_values": {
                    "type": "array",
                    "description": "List of Langmuir fit R² values across salt conditions (may contain nulls)",
                    "items": {"type": ["number", "null"]},
                },
            },
        },
        "data_files": {
            "type": "object",
            "description": "Output data file names produced by analysis",
            "additionalProperties": {"type": "string"},
        },
        "plots": {
            "type": "object",
            "description": "Output plot file names produced by analysis",
            "additionalProperties": {"type": "string"},
        },
        "raw_analysis": {
            "type": "object",
            "description": "Raw JSON contents of analysis_results_{elab_id}.json for full traceability",
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "analysis_results_{elab_id}.json",
        "plate_absorbance_ce_{elab_id}.csv",
        "aggregated_ce_q_{elab_id}.csv",
        "langmuir_fits_{elab_id}.csv",
        "tecan_data_{elab_id}.xlsx",
    ],
    "plots": [
        "loading_isotherms_{elab_id}.png",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value: str):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if not isinstance(value, str):
        return None
    text = value.strip()
    if text == "":
        return None
    text = text.replace(",", ".")
    import re

    match = re.search(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", text)
    if match:
        try:
            return float(match.group(0))
        except ValueError:
            return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """
    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()
    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Try to interpret as all numbers (with decimal comma support)
            normalized_parts = [p.replace(",", ".") for p in parts]
            try:
                return [float(p) for p in normalized_parts]
            except ValueError:
                return parts
    if field_type == "number":
        num = parse_numeric(text)
        return num if num is not None else text
    return text  # text stays text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields.

    This function respects eLab field types for numeric parsing and correctly
    handles potentially list-like values.
    """
    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name not in extra_fields:
            continue
        field = extra_fields[elab_name]
        value = field.get("value")
        field_type = field.get("type")
        parsed_value = parse_field(value, field_type=field_type)
        metadata[db_name] = parsed_value
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id):
    """Load analysis_results_{elab_id}.json if present in ../results.

    Returns a tuple (raw_json, status, message, meta_summary).
    """
    results_dir = Path("../results")
    results_file = results_dir / f"analysis_results_{elab_id}.json"
    raw_json = None
    status = "pending"
    message = ""
    meta_summary = {}

    if results_file.exists():
        try:
            with open(results_file, "r") as f:
                raw_json = json.load(f)
            status = raw_json.get("status", "pending")
            message = raw_json.get("message", "")
            md = raw_json.get("metadata", {}) or {}
            meta_summary = {
                "n_points_raw": md.get("n_points_raw"),
                "n_points_aggregated": md.get("n_points_aggregated"),
            }
        except Exception as e:  # defensive
            status = "failed"
            message = f"Failed to load analysis_results JSON: {e}"
    else:
        message = "analysis_results JSON not found"

    return raw_json, status, message, meta_summary


def build_results(elab_id):
    """Build results JSONB structure from files in ../results and ../analysis."""
    results_root = Path("../results")
    analysis_root = Path("../analysis")

    # Load raw analysis JSON if present
    raw_analysis, status, message, meta_summary = load_analysis_results(elab_id)

    # Collect data files and plots following EXPECTED_FILES patterns where possible
    def find_matching(pattern: str, base: Path):
        out = None
        candidate = base / pattern.format(elab_id=elab_id)
        if candidate.exists():
            out = candidate.name
        else:
            # Fallback: look for any file that loosely matches prefix
            prefix = pattern.format(elab_id="")
            for f in base.glob("*"):
                if f.is_file() and f.name.startswith(prefix):
                    out = f.name
                    break
        return out

    data_files = {}
    plots = {}

    if results_root.exists():
        for key_pattern in EXPECTED_FILES.get("data", []):
            name = find_matching(key_pattern, results_root)
            if name:
                key = (
                    key_pattern.replace("_{elab_id}", "")
                    .replace(".csv", "")
                    .replace(".json", "")
                    .replace(".xlsx", "")
                )
                data_files[key] = name
        # Also include any other files in results folder
        for f in results_root.iterdir():
            if f.is_file():
                data_files.setdefault(f.stem, f.name)

        for key_pattern in EXPECTED_FILES.get("plots", []):
            name = find_matching(key_pattern, results_root)
            if name:
                key = key_pattern.replace("_{elab_id}", "").replace(".png", "")
                plots[key] = name

    if analysis_root.exists():
        # Include analysis directory files (if any) under a separate namespace
        for f in analysis_root.iterdir():
            if f.is_file():
                data_files.setdefault(f"analysis_{f.stem}", f.name)

    # Build summary arrays for Langmuir fits if CSV is present
    qmax_list = []
    K_list = []
    R2_list = []
    n_salt_conditions = None
    langmuir_csv_name = data_files.get("langmuir_fits_", None) or data_files.get(
        "langmuir_fits", None
    )
    if langmuir_csv_name:
        try:
            import csv

            csv_path = results_root / langmuir_csv_name
            with open(csv_path, newline="") as csvfile:
                reader = csv.DictReader(csvfile)

                def parse_float_maybe(val):
                    if val is None or val == "":
                        return None
                    try:
                        return float(val)
                    except ValueError:
                        return None

                for row in reader:
                    qmax_list.append(parse_float_maybe(row.get("qmax")))
                    K_list.append(parse_float_maybe(row.get("K")))
                    R2_list.append(parse_float_maybe(row.get("R2")))
            n_salt_conditions = len(qmax_list) if qmax_list else None
        except Exception:
            qmax_list = []
            K_list = []
            R2_list = []
            n_salt_conditions = None

    summary = {
        "n_points_raw": meta_summary.get("n_points_raw"),
        "n_points_aggregated": meta_summary.get("n_points_aggregated"),
        "n_salt_conditions": n_salt_conditions,
        "qmax_values": qmax_list if qmax_list else None,
        "K_values": K_list if K_list else None,
        "R2_values": R2_list if R2_list else None,
    }

    # If every summary value is None, drop summary
    if all(v is None for v in summary.values()):
        summary = None

    results = {
        "analysis_status": status,
        "analysis_timestamp": datetime.now(timezone.utc).isoformat(),
        "message": message,
        "summary": summary,
        "data_files": data_files,
        "plots": plots,
        "raw_analysis": raw_analysis,
    }
    return results


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""
    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    row = cursor.fetchone()
    return row[0] if row else None


def main():
    parser = argparse.ArgumentParser(
        description=f"Commit {PROCESS_NAME} to database"
    )
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {}) or {}
        workflow_json, lab_id = load_workflow()

        # Build data structures
        metadata = extract_metadata(extra_fields)
        raw_data = build_raw_data(args.elab_id)
        results = build_results(args.elab_id)

        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": results.get("analysis_status", "pending"),
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": metadata,
            "raw_data": raw_data,
            "results": results,
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})")
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if "conn" in locals():
            try:
                conn.rollback()
            except Exception:
                pass
        return 1
    finally:
        if "conn" in locals():
            try:
                conn.close()
            except Exception:
                pass


if __name__ == "__main__":
    sys.exit(main())