#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_id",
    "Pump Speed": "pump_speed",
    "Replicates": "replicates",
    "Resin Mass": "resin_mass_mg",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume_uL",
    "Venting time": "venting_time",
    "Pump Duration": "pump_duration",
    "Incubation Time": "incubation_time",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume_uL",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature",
    "Measurement Wavelength": "measurement_wavelength_nm",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration",
    "Number of salt concentrations": "num_salt_concentrations",
    "Number of ligand concentrations": "num_ligand_concentrations",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Buffer solution name or composition",
        },
        "salt_name": {
            "type": "string",
            "description": "Name of the salt used in the experiment",
        },
        "process_id": {
            "type": "string",
            "description": "Process identifier configured in the automation system",
        },
        "pump_speed": {
            "type": "string",
            "description": "Pump speed setting (unit as configured on instrument)",
        },
        "replicates": {
            "type": "integer",
            "description": "Number of replicate wells per condition",
        },
        "resin_mass_mg": {
            "type": "number",
            "description": "Mass of resin loaded per well",
            "unit": "mg",
        },
        "ligand_name": {
            "type": "string",
            "description": "Name of the ligand (solute) loaded onto the resin",
        },
        "total_volume_uL": {
            "type": "number",
            "description": "Total volume of ligand solution used per well",
            "unit": "µL",
        },
        "venting_time": {
            "type": "string",
            "description": "Venting time for the pumping step (string to preserve units)",
        },
        "pump_duration": {
            "type": "string",
            "description": "Duration of pump operation (string to preserve units)",
        },
        "incubation_time": {
            "type": "string",
            "description": "Total incubation time before measurement (string to preserve units)",
        },
        "salt_concentrations": {
            "type": "array",
            "description": "List of salt concentrations used across columns",
            "items": {"type": "number"},
        },
        "equilibration_cycles": {
            "type": "string",
            "description": "Number of equilibration cycles (kept as string due to possible annotations)",
        },
        "equilibration_volume_uL": {
            "type": "string",
            "description": "Volume per equilibration cycle",
        },
        "ligand_concentrations": {
            "type": "array",
            "description": "List of initial ligand concentrations used for each row",
            "items": {"type": "number"},
        },
        "incubation_temperature": {
            "type": "string",
            "description": "Incubation temperature (raw string including units)",
        },
        "measurement_wavelength_nm": {
            "type": "string",
            "description": "Measurement wavelength configured on the plate reader",
        },
        "calibration_curve_slope": {
            "type": "number",
            "description": "Slope of the calibration curve used to convert absorbance to concentration",
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit for salt concentrations (e.g., mM)",
        },
        "shaker_speed_incubation": {
            "type": "string",
            "description": "Shaker speed during incubation (raw string)",
        },
        "salt_stock_concentration": {
            "type": "string",
            "description": "Salt stock solution concentration (raw string)",
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit for ligand concentrations (e.g., mM, µM)",
        },
        "ligand_stock_concentration": {
            "type": "string",
            "description": "Ligand stock solution concentration (raw string)",
        },
        "calibration_curve_intercept": {
            "type": "number",
            "description": "Intercept of the calibration curve used to convert absorbance to concentration",
        },
        "equilibration_cycle_duration": {
            "type": "string",
            "description": "Duration of a single equilibration cycle (raw string)",
        },
        "num_salt_concentrations": {
            "type": "integer",
            "description": "Number of distinct salt concentrations defined in the metadata",
        },
        "num_ligand_concentrations": {
            "type": "integer",
            "description": "Number of distinct ligand concentrations defined in the metadata",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "completed", "failed"],
            "description": "Status of the analysis pipeline",
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when results were committed to the database",
        },
        "analysis_results": {
            "type": "object",
            "description": "Raw analysis_results dictionary produced by the Tecan loading isotherm analysis script",
        },
        "summary": {
            "type": "object",
            "description": "Key derived metrics across all salt conditions",
            "properties": {
                "num_salt_conditions": {
                    "type": "integer",
                    "description": "Number of distinct salt concentrations with fits",
                },
                "num_ligand_conditions": {
                    "type": "integer",
                    "description": "Number of distinct ligand concentrations per salt condition (where available)",
                },
                "num_fit_success": {
                    "type": "integer",
                    "description": "Number of salt conditions where Langmuir fitting returned finite parameters",
                },
                "num_fit_failed": {
                    "type": "integer",
                    "description": "Number of salt conditions where Langmuir fitting failed or returned invalid parameters",
                },
                "q_max_mean": {
                    "type": "number",
                    "description": "Mean q_max across all successful Langmuir fits",
                },
                "q_max_std": {
                    "type": "number",
                    "description": "Standard deviation of q_max across successful fits",
                },
                "K_mean": {
                    "type": "number",
                    "description": "Mean binding constant K across all successful Langmuir fits",
                },
                "K_std": {
                    "type": "number",
                    "description": "Standard deviation of binding constant K across successful fits",
                },
                "r2_mean": {
                    "type": "number",
                    "description": "Mean coefficient of determination R^2 across successful fits",
                },
                "r2_std": {
                    "type": "number",
                    "description": "Standard deviation of R^2 across successful fits",
                },
            },
        },
        "data_files": {
            "type": "object",
            "description": "Structured links to key output data files",
            "properties": {
                "analysis_results_json": {
                    "type": "string",
                    "description": "Path to the main analysis_results_*.json file",
                },
                "tecan_raw_file": {
                    "type": "string",
                    "description": "Path to the downloaded or discovered raw Tecan Excel file",
                },
                "per_well_csv": {
                    "type": "string",
                    "description": "Path to per-well processed CSV file",
                },
                "aggregated_csv": {
                    "type": "string",
                    "description": "Path to aggregated per-condition CSV file",
                },
            },
        },
        "plots": {
            "type": "object",
            "description": "Plot output file names",
            "properties": {
                "isotherms_png": {
                    "type": "string",
                    "description": "PNG plot of loading isotherms with Langmuir fits",
                },
                "isotherms_pdf": {
                    "type": "string",
                    "description": "PDF plot of loading isotherms with Langmuir fits",
                },
            },
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "analysis_results_{elab_id}.json",
        "tecan_data_{elab_id}.xlsx",
        "tecan_loading_isotherm_per_well_{elab_id}.csv",
        "tecan_loading_isotherm_aggregated_{elab_id}.csv",
    ],
    "plots": [
        "loading_isotherms_{elab_id}.png",
        "loading_isotherms_{elab_id}.pdf",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value: str):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    text = str(value).strip()
    if text == "":
        return None
    # Replace decimal comma by dot if present and there is only one numeric token
    import re

    # Find first float-like pattern
    match = re.search(r"[-+]?\d*[,\.]?\d+(?:[eE][-+]?\d+)?", text)
    if not match:
        return None
    num_str = match.group(0).replace(",", ".")
    try:
        return float(num_str)
    except ValueError:
        return None


def parse_field(value, field_type: str | None = None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """

    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()

    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Try numeric list first (support decimal comma)
            all_numeric = True
            nums = []
            for p in parts:
                p_norm = p.replace(",", ".")
                try:
                    nums.append(float(p_norm))
                except ValueError:
                    all_numeric = False
                    break
            if all_numeric:
                return nums
            return parts

    if field_type == "number":
        return parse_numeric(text)

    return text


def find_experiment_json(elab_id: int) -> Path:
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields: dict) -> dict:
    """Extract and map metadata from eLabFTW extra fields.

    This function respects field types and possible list encodings.
    """
    metadata: dict = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name not in extra_fields:
            continue
        field = extra_fields[elab_name]
        if not isinstance(field, dict):
            continue
        value = field.get("value")
        field_type = field.get("type")  # e.g. 'number', 'text'
        parsed = parse_field(value, field_type=field_type)
        # Cast to int for some known integer fields where parse_field returns numeric
        if db_name in {"replicates", "num_salt_concentrations", "num_ligand_concentrations"} and isinstance(
            parsed, (int, float)
        ):
            try:
                parsed = int(parsed)
            except Exception:
                pass
        metadata[db_name] = parsed
    return metadata


def list_folder_files(folder_path: Path) -> list[str]:
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id: int) -> dict:
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def build_results(elab_id: int) -> dict:
    """Build results JSONB structure from analysis outputs.

    Expects the analysis script to have written analysis_results_{elab_id}.json
    and associated CSV/plot files into ../results/.
    """
    results_folder = Path("../results")
    results: dict = {
        "analysis_status": "pending",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "analysis_results": None,
        "summary": {},
        "data_files": {},
        "plots": {},
    }

    if not results_folder.exists():
        return results

    # Load primary analysis_results JSON if present
    analysis_json_name = f"analysis_results_{elab_id}.json"
    analysis_json_path = results_folder / analysis_json_name
    if analysis_json_path.exists():
        try:
            with open(analysis_json_path, "r") as f:
                analysis = json.load(f)
            results["analysis_results"] = analysis
            status = analysis.get("status", "failed")
            results["analysis_status"] = "completed" if status == "success" else "failed"
        except Exception:
            results["analysis_status"] = "failed"
    else:
        # No dedicated analysis JSON found; just report files
        results["analysis_status"] = "pending"

    # Data files from known naming patterns
    data_files: dict = {}
    tecan_raw = results_folder / f"tecan_data_{elab_id}.xlsx"
    if tecan_raw.exists():
        data_files["tecan_raw_file"] = str(tecan_raw.resolve())
    per_well = results_folder / f"tecan_loading_isotherm_per_well_{elab_id}.csv"
    if per_well.exists():
        data_files["per_well_csv"] = str(per_well.resolve())
    aggregated = results_folder / f"tecan_loading_isotherm_aggregated_{elab_id}.csv"
    if aggregated.exists():
        data_files["aggregated_csv"] = str(aggregated.resolve())
    if analysis_json_path.exists():
        data_files["analysis_results_json"] = str(analysis_json_path.resolve())

    results["data_files"] = data_files

    # Plot files
    plots: dict = {}
    png = results_folder / f"loading_isotherms_{elab_id}.png"
    if png.exists():
        plots["isotherms_png"] = str(png.resolve())
    pdf = results_folder / f"loading_isotherms_{elab_id}.pdf"
    if pdf.exists():
        plots["isotherms_pdf"] = str(pdf.resolve())

    # If analysis_results JSON exists, prefer plot/file paths stored there as well
    if results.get("analysis_results"):
        ar = results["analysis_results"]
        ar_plots = ar.get("plots", {}) if isinstance(ar, dict) else {}
        ar_data_outputs = ar.get("data_outputs", {}) if isinstance(ar, dict) else {}
        # Merge, giving precedence to explicit keys above
        for k, v in ar_plots.items():
            plots.setdefault(k, v)
        for k, v in ar_data_outputs.items():
            data_files.setdefault(k, v)

    results["plots"] = plots

    # Build simple numeric summary from fit_results if present
    summary: dict = {}
    ar = results.get("analysis_results") or {}
    if isinstance(ar, dict):
        fit_results = ar.get("fit_results")
        metadata = ar.get("metadata", {})
        if isinstance(metadata, dict):
            num_lig = metadata.get("num_ligand_concentrations") or metadata.get("num_ligand_conc")
            if isinstance(num_lig, (int, float)):
                summary["num_ligand_conditions"] = int(num_lig)
        if isinstance(fit_results, list) and fit_results:
            import math

            q_max_vals = []
            K_vals = []
            r2_vals = []
            for fr in fit_results:
                if not isinstance(fr, dict):
                    continue
                q_max = fr.get("q_max")
                K = fr.get("K")
                r2 = fr.get("R2")
                if isinstance(q_max, (int, float)) and isinstance(K, (int, float)) and isinstance(r2, (int, float)):
                    q_max_vals.append(float(q_max))
                    K_vals.append(float(K))
                    r2_vals.append(float(r2))
            num_success = len(q_max_vals)
            num_total = len(fit_results)
            summary["num_salt_conditions"] = num_total
            summary["num_fit_success"] = num_success
            summary["num_fit_failed"] = max(0, num_total - num_success)

            def _mean_std(values: list[float]) -> tuple[float | None, float | None]:
                if not values:
                    return None, None
                m = sum(values) / len(values)
                if len(values) > 1:
                    var = sum((x - m) ** 2 for x in values) / (len(values) - 1)
                    s = math.sqrt(var)
                else:
                    s = 0.0
                return m, s

            q_mean, q_std = _mean_std(q_max_vals)
            k_mean, k_std = _mean_std(K_vals)
            r2_mean, r2_std = _mean_std(r2_vals)
            if q_mean is not None:
                summary["q_max_mean"] = q_mean
                summary["q_max_std"] = q_std
            if k_mean is not None:
                summary["K_mean"] = k_mean
                summary["K_std"] = k_std
            if r2_mean is not None:
                summary["r2_mean"] = r2_mean
                summary["r2_std"] = r2_std

    results["summary"] = summary

    return results


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id: int, data: dict) -> int:
    """Insert or update experiment execution."""
    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    row = cursor.fetchone()
    return int(row[0])


def main() -> int:
    parser = argparse.ArgumentParser(
        description=f"Commit {PROCESS_NAME} to database"
    )
    parser.add_argument("elab_id", type=int, help="eLabFTW experiment ID")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})")

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get("extra_fields", {})
        workflow_json, lab_id = load_workflow()

        # Build data structures
        metadata = extract_metadata(extra_fields)
        raw_data = build_raw_data(args.elab_id)
        results = build_results(args.elab_id)

        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": "completed" if results.get("analysis_status") == "completed" else "failed",
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": metadata,
            "raw_data": raw_data,
            "results": results,
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})")
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if "conn" in locals():
            conn.rollback()
        return 1
    finally:
        if "conn" in locals():
            conn.close()


if __name__ == "__main__":
    sys.exit(main())