#!/usr/bin/env python3
"""
Database commit script for Loading Isotherm Resin (automated)
Auto-generated by SDL Schema Generator

Usage:
    python commit_to_db.py ELAB_ID [--dry-run] [--init-schema-only]
"""

import os
import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone
import pg8000.dbapi

# ============================================================================
# CONFIGURATION
# ============================================================================

PROCESS_ID = 15
PROCESS_NAME = "Loading Isotherm Resin (automated)"
PROCESS_VERSION = "1.0"

FIELD_MAPPING = {
    "Buffer": "buffer_name",
    "Salt Name": "salt_name",
    "Process ID": "process_run_id",
    "Pump Speed": "pump_speed",
    "Replicates": "replicates",
    "Resin Mass": "resin_mass_mg",
    "Ligand Name": "ligand_name",
    "Total volume": "total_volume_uL",
    "Venting time": "venting_time_s",
    "Pump Duration": "pump_duration_s",
    "Incubation Time": "incubation_time_min",
    "Salt concentrations": "salt_concentrations",
    "Equilibration Cycles": "equilibration_cycles",
    "Equilibration Volume": "equilibration_volume_uL",
    "Ligand concentrations": "ligand_concentrations",
    "Incubation Temperature": "incubation_temperature_c",
    "Measurement Wavelength": "measurement_wavelength_nm",
    "Calibration Curve Slope": "calibration_curve_slope",
    "Salt concentration unit": "salt_concentration_unit",
    "Shaker Speed Incubation": "shaker_speed_incubation_rpm",
    "Salt Stock Concentration": "salt_stock_concentration",
    "Ligand concentration unit": "ligand_concentration_unit",
    "Ligand Stock Concentration": "ligand_stock_concentration",
    "Calibration Curve Intercept": "calibration_curve_intercept",
    "Equilibration Cycle Duration": "equilibration_cycle_duration_s",
    "Number of salt concentrations": "number_of_salt_concentrations",
    "Number of ligand concentrations": "number_of_ligand_concentrations",
}

METADATA_SCHEMA = {
    "type": "object",
    "properties": {
        "buffer_name": {
            "type": "string",
            "description": "Buffer solution used during loading and equilibration",
        },
        "salt_name": {
            "type": "string",
            "description": "Name or identity of the salt used",
        },
        "process_run_id": {
            "type": "string",
            "description": "Identifier of the automated process run (as stored in eLabFTW)",
        },
        "pump_speed": {
            "type": ["number", "array", "string"],
            "description": "Pump speed setting during loading (instrument units)",
            "unit": "arb.",
        },
        "replicates": {
            "type": ["integer", "array", "string"],
            "description": "Number of replicate wells per condition on the plate",
        },
        "resin_mass_mg": {
            "type": ["number", "array", "string"],
            "description": "Mass of resin used per well",
            "unit": "mg",
        },
        "ligand_name": {
            "type": "string",
            "description": "Name or identity of the ligand being loaded onto the resin",
        },
        "total_volume_uL": {
            "type": ["number", "array", "string"],
            "description": "Total liquid volume per well used for loading",
            "unit": "uL",
        },
        "venting_time_s": {
            "type": ["number", "array", "string"],
            "description": "Venting time during loading step",
            "unit": "s",
        },
        "pump_duration_s": {
            "type": ["number", "array", "string"],
            "description": "Duration of pump operation during loading",
            "unit": "s",
        },
        "incubation_time_min": {
            "type": ["number", "array", "string"],
            "description": "Incubation time for resin-ligand equilibration",
            "unit": "min",
        },
        "salt_concentrations": {
            "type": ["array", "string"],
            "description": "List of salt concentrations used across columns",
            "items": {"type": "number"},
            "unit": "see salt_concentration_unit",
        },
        "equilibration_cycles": {
            "type": ["integer", "array", "string"],
            "description": "Number of equilibration cycles performed before loading",
        },
        "equilibration_volume_uL": {
            "type": ["number", "array", "string"],
            "description": "Volume used for each equilibration cycle",
            "unit": "uL",
        },
        "ligand_concentrations": {
            "type": ["array", "string"],
            "description": "List of initial ligand concentrations used across rows",
            "items": {"type": "number"},
            "unit": "see ligand_concentration_unit",
        },
        "incubation_temperature_c": {
            "type": ["number", "array", "string"],
            "description": "Incubation temperature during equilibration",
            "unit": "degC",
        },
        "measurement_wavelength_nm": {
            "type": ["number", "array", "string"],
            "description": "Measurement wavelength used on the Tecan plate reader",
            "unit": "nm",
        },
        "calibration_curve_slope": {
            "type": ["number", "array", "string"],
            "description": "Slope of the calibration curve relating absorbance to concentration",
        },
        "salt_concentration_unit": {
            "type": "string",
            "description": "Unit for salt concentrations, e.g. mM or M",
        },
        "shaker_speed_incubation_rpm": {
            "type": ["number", "array", "string"],
            "description": "Shaker speed during incubation",
            "unit": "rpm",
        },
        "salt_stock_concentration": {
            "type": ["number", "array", "string"],
            "description": "Concentration of the salt stock solution",
            "unit": "see salt_concentration_unit",
        },
        "ligand_concentration_unit": {
            "type": "string",
            "description": "Unit for ligand concentrations, e.g. uM or mM",
        },
        "ligand_stock_concentration": {
            "type": ["number", "array", "string"],
            "description": "Concentration of the ligand stock solution",
            "unit": "see ligand_concentration_unit",
        },
        "calibration_curve_intercept": {
            "type": ["number", "array", "string"],
            "description": "Intercept of the calibration curve relating absorbance to concentration",
        },
        "equilibration_cycle_duration_s": {
            "type": ["number", "array", "string"],
            "description": "Duration of each equilibration cycle",
            "unit": "s",
        },
        "number_of_salt_concentrations": {
            "type": ["integer", "array", "string"],
            "description": "Number of distinct salt concentrations on the plate",
        },
        "number_of_ligand_concentrations": {
            "type": ["integer", "array", "string"],
            "description": "Number of distinct ligand concentrations on the plate",
        },
    },
}

RESULTS_SCHEMA = {
    "type": "object",
    "properties": {
        "analysis_status": {
            "type": "string",
            "enum": ["pending", "success", "failed"],
            "description": "Status of the loading isotherm analysis as reported by the analysis script",
        },
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Time when results were committed to the database (UTC)",
        },
        "summary": {
            "type": "object",
            "description": "Key metrics extracted from the analysis script output",
            "properties": {
                "num_ligand_concentrations": {
                    "type": "integer",
                    "description": "Number of ligand concentrations as used for analysis",
                },
                "num_salt_concentrations": {
                    "type": "integer",
                    "description": "Number of salt concentrations as used for analysis",
                },
                "replicates": {
                    "type": "integer",
                    "description": "Number of replicates per condition used in analysis",
                },
                "resin_mass_mg": {
                    "type": "number",
                    "description": "Resin mass used per well, as interpreted by the analysis script",
                    "unit": "mg",
                },
                "total_volume_uL": {
                    "type": "number",
                    "description": "Total liquid volume per well, as interpreted by the analysis script",
                    "unit": "uL",
                },
                "ligand_concentration_unit": {
                    "type": "string",
                    "description": "Ligand concentration unit used in fits",
                },
                "salt_concentration_unit": {
                    "type": "string",
                    "description": "Salt concentration unit used in fits",
                },
                "n_salt_conditions_with_fit": {
                    "type": "integer",
                    "description": "Number of salt conditions for which Langmuir fits were successfully obtained",
                },
                "fit_results": {
                    "type": "array",
                    "description": "Per-salt Langmuir fit parameters extracted from the analysis JSON",
                    "items": {
                        "type": "object",
                        "properties": {
                            "salt_conc": {
                                "type": ["number", "null"],
                                "description": "Salt concentration for this fit",
                            },
                            "salt_unit": {
                                "type": ["string", "null"],
                                "description": "Unit of salt concentration",
                            },
                            "qmax": {
                                "type": ["number", "null"],
                                "description": "Fitted maximum loading capacity qmax",
                            },
                            "K": {
                                "type": ["number", "null"],
                                "description": "Fitted Langmuir affinity constant K",
                            },
                            "R2": {
                                "type": ["number", "null"],
                                "description": "Coefficient of determination for the fit",
                            },
                            "n_points": {
                                "type": ["integer", "null"],
                                "description": "Number of data points used for the fit",
                            },
                        },
                    },
                },
            },
        },
        "data_files": {
            "type": "object",
            "description": "Structured listing of analysis data output files",
            "properties": {
                "tecan_raw_excel": {
                    "type": ["string", "null"],
                    "description": "Path to raw Tecan Excel file used in analysis",
                },
                "aggregated_isotherm_csv": {
                    "type": ["string", "null"],
                    "description": "Path to aggregated isotherm CSV",
                },
                "detailed_well_csv": {
                    "type": ["string", "null"],
                    "description": "Path to detailed per-well CSV",
                },
                "analysis_results_json": {
                    "type": ["string", "null"],
                    "description": "Path to full analysis results JSON file",
                },
            },
        },
        "plots": {
            "type": "object",
            "description": "Plot files produced by the analysis script",
            "properties": {
                "loading_isotherms_png": {
                    "type": ["string", "null"],
                    "description": "PNG plot of loading isotherms",
                },
                "loading_isotherms_pdf": {
                    "type": ["string", "null"],
                    "description": "PDF plot of loading isotherms",
                },
            },
        },
        "raw_analysis_output": {
            "type": "object",
            "description": "Raw JSON structure saved by the analysis script (for debugging and provenance)",
        },
        "all_result_files": {
            "type": "array",
            "description": "Flat list of all files present in the results folder at commit time",
            "items": {"type": "string"},
        },
    },
}

EXPECTED_FILES = {
    "data": [
        "tecan_data_{elab_id}.xlsx",
        "aggregated_isotherm_{elab_id}.csv",
        "detailed_well_data_{elab_id}.csv",
        "analysis_results_{elab_id}.json",
    ],
    "plots": [
        "loading_isotherms_{elab_id}.png",
        "loading_isotherms_{elab_id}.pdf",
    ],
}

# ============================================================================
# DATABASE CONNECTION
# ============================================================================


def get_db_connection():
    return pg8000.dbapi.connect(
        host=os.environ.get("EXPERIMENT_DB_HOST", "sdl-experiment-db"),
        port=int(os.environ.get("EXPERIMENT_DB_INTERNAL_PORT", 5432)),
        database=os.environ.get("EXPERIMENT_DB_NAME", "sdl_experiments"),
        user=os.environ.get("EXPERIMENT_DB_USER", "sdl_admin"),
        password=os.environ.get("EXPERIMENT_DB_PASSWORD", "sdl_secure_2025"),
    )


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================


def parse_numeric(value: str):
    """Extract a numeric value from a string like '25 °C' or '100 mM'.

    Call this ONLY for a single-valued field eLabFTW types as a number. On a text field
    it is destructive - '20 mM NaAc' becomes 20.0 and the buffer identity is gone - and
    on a delimited list it keeps only the first element. When in doubt, store the
    original string unchanged.
    """

    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    text = str(value).strip()
    if text == "":
        return None

    # Extract first floating-point number from the string
    import re

    match = re.search(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", text.replace(",", "."))
    if match:
        try:
            return float(match.group(0))
        except ValueError:
            return None
    return None


def parse_field(value, field_type=None):
    """Route an eLabFTW value by what it IS, not by which parameter it came from.

    Any field may arrive as a delimited list, so the delimiter check comes first.
    """
    if value is None or value == "":
        return None
    if isinstance(value, (list, int, float)):
        return value
    text = str(value).strip()
    # a list if a delimiter separates more than one token; "1,5" (decimal comma) is one
    for sep in (";", ","):
        parts = [p.strip() for p in text.split(sep) if p.strip()]
        if len(parts) > 1:
            # Try to interpret as all-numeric; if that fails, keep as strings
            try:
                return [float(p.replace(",", ".")) for p in parts]
            except ValueError:
                return parts
    if field_type == "number":
        num = parse_numeric(text)
        return num if num is not None else text
    return text  # text stays text


def find_experiment_json(elab_id):
    """Find experiment JSON file."""
    paths = [
        Path(f"../experiment_{elab_id}.json"),
        Path(f"../data/experiment_{elab_id}.json"),
    ]
    for p in paths:
        if p.exists():
            return p
    raise FileNotFoundError(f"Experiment JSON not found for {elab_id}")


def load_workflow():
    """Load workflow.json and extract lab_id."""
    workflow_path = Path("../workflow.json")
    if workflow_path.exists():
        with open(workflow_path) as f:
            data = json.load(f)
            return data, data.get("lab_id") or data.get("labId")
    return None, None


def extract_metadata(extra_fields):
    """Extract and map metadata from eLabFTW extra fields."""
    metadata = {}
    for elab_name, db_name in FIELD_MAPPING.items():
        if elab_name in extra_fields:
            field = extra_fields[elab_name]
            value = field.get("value")
            field_type = field.get("type")
            parsed_value = parse_field(value, field_type=field_type)
            metadata[db_name] = parsed_value
    return metadata


def list_folder_files(folder_path):
    """List files in a folder."""
    folder = Path(folder_path)
    if folder.exists():
        return [f.name for f in folder.iterdir() if f.is_file()]
    return []


def build_raw_data(elab_id):
    """Build raw_data JSONB structure."""
    data_folder = Path("../data")
    return {
        "folder_path": str(data_folder.resolve()),
        "files": list_folder_files(data_folder),
    }


def load_analysis_results(elab_id):
    """Load analysis_results_{elab_id}.json if available."""
    results_folder = Path("../results")
    analysis_json = results_folder / f"analysis_results_{elab_id}.json"
    if analysis_json.exists():
        try:
            with open(analysis_json, "r") as f:
                return json.load(f)
        except Exception:
            return None
    return None


def build_results(elab_id):
    """Build results JSONB structure from analysis outputs and files."""
    results_folder = Path("../results")
    analysis_data = load_analysis_results(elab_id)

    # Determine analysis status
    if analysis_data is None:
        analysis_status = "pending"
        raw_output = None
    else:
        status = analysis_data.get("status")
        if status in ("success", "failed"):
            analysis_status = status
        else:
            analysis_status = "pending"
        raw_output = analysis_data

    # Summary extraction from analysis JSON if available
    summary = {}
    if analysis_data is not None:
        md = analysis_data.get("metadata", {}) or {}
        fit_results = md.get("fit_results")
        if isinstance(fit_results, list):
            n_fit = sum(
                1
                for fr in fit_results
                if fr and fr.get("qmax") is not None and fr.get("K") is not None
            )
        else:
            n_fit = 0

        def _safe_int(x):
            try:
                return int(x)
            except Exception:
                return None

        def _safe_float(x):
            try:
                return float(x)
            except Exception:
                return None

        summary = {
            "num_ligand_concentrations": _safe_int(
                md.get("num_ligand_concentrations")
            ),
            "num_salt_concentrations": _safe_int(md.get("num_salt_concentrations")),
            "replicates": _safe_int(md.get("replicates")),
            "resin_mass_mg": _safe_float(md.get("resin_mass_mg")),
            "total_volume_uL": _safe_float(md.get("total_volume_uL")),
            "ligand_concentration_unit": md.get("ligand_concentration_unit"),
            "salt_concentration_unit": md.get("salt_concentration_unit"),
            "n_salt_conditions_with_fit": n_fit,
            "fit_results": fit_results,
        }

    # Data files mapping
    data_files = {
        "tecan_raw_excel": None,
        "aggregated_isotherm_csv": None,
        "detailed_well_csv": None,
        "analysis_results_json": None,
    }

    if analysis_data is not None:
        data_outputs = analysis_data.get("data_outputs", {}) or {}
        for key in data_files.keys():
            val = data_outputs.get(key)
            if isinstance(val, str):
                data_files[key] = val

    # Plots mapping
    plots = {
        "loading_isotherms_png": None,
        "loading_isotherms_pdf": None,
    }

    if analysis_data is not None:
        plot_outputs = analysis_data.get("plots", {}) or {}
        for key in plots.keys():
            val = plot_outputs.get(key)
            if isinstance(val, str):
                plots[key] = val

    # Also list any other result files in the folder for completeness
    all_result_files = list_folder_files(results_folder)

    return {
        "analysis_status": analysis_status,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "summary": summary,
        "data_files": data_files,
        "plots": plots,
        "raw_analysis_output": raw_output,
        "all_result_files": all_result_files,
    }


# ============================================================================
# MAIN FUNCTIONS
# ============================================================================


def upsert_process_schema(cursor):
    """Insert or update process schema."""
    cursor.execute(
        """
        INSERT INTO process_schemas (
            process_id, process_name, version,
            metadata_schema, results_schema, field_mapping, expected_files
        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (process_id) DO UPDATE SET
            process_name = EXCLUDED.process_name,
            metadata_schema = EXCLUDED.metadata_schema,
            results_schema = EXCLUDED.results_schema,
            field_mapping = EXCLUDED.field_mapping,
            expected_files = EXCLUDED.expected_files,
            updated_at = NOW()
    """,
        (
            PROCESS_ID,
            PROCESS_NAME,
            PROCESS_VERSION,
            json.dumps(METADATA_SCHEMA),
            json.dumps(RESULTS_SCHEMA),
            json.dumps(FIELD_MAPPING),
            json.dumps(EXPECTED_FILES),
        ),
    )


def upsert_experiment(cursor, elab_id, data):
    """Insert or update experiment execution."""
    cursor.execute(
        """
        INSERT INTO experiment_executions (
            elab_id, elab_title, process_id, process_name, lab_id,
            status, "user", workflow_json, metadata, raw_data, results
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (elab_id) DO UPDATE SET
            elab_title = EXCLUDED.elab_title,
            status = EXCLUDED.status,
            metadata = EXCLUDED.metadata,
            raw_data = EXCLUDED.raw_data,
            results = EXCLUDED.results,
            workflow_json = EXCLUDED.workflow_json,
            updated_at = NOW()
        RETURNING id
    """,
        (
            elab_id,
            data["title"],
            PROCESS_ID,
            PROCESS_NAME,
            data["lab_id"],
            data["status"],
            data["user"],
            json.dumps(data["workflow_json"]) if data["workflow_json"] else None,
            json.dumps(data["metadata"]),
            json.dumps(data["raw_data"]),
            json.dumps(data["results"]),
        ),
    )
    return cursor.fetchone()[0]


def main():
    parser = argparse.ArgumentParser(
        description=f"Commit {PROCESS_NAME} to database"
    )
    parser.add_argument(
        "elab_id", type=int, help="eLabFTW experiment ID"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't commit, just show what would be done",
    )
    parser.add_argument(
        "--init-schema-only",
        action="store_true",
        help="Only initialize process schema",
    )
    args = parser.parse_args()

    try:
        conn = get_db_connection()
        cursor = conn.cursor()

        # Always upsert schema
        upsert_process_schema(cursor)
        print(
            f"Process schema updated: {PROCESS_NAME} (ID: {PROCESS_ID})"
        )

        if args.init_schema_only:
            conn.commit()
            print("Schema-only mode, skipping experiment data.")
            return 0

        # Load experiment data
        exp_json_path = find_experiment_json(args.elab_id)
        with open(exp_json_path) as f:
            exp_data = json.load(f)

        # Extract fields
        extra_fields = exp_data.get("metadata_decoded", {}).get(
            "extra_fields", {}
        )
        workflow_json, lab_id = load_workflow()

        # Build data structures
        data = {
            "title": exp_data.get("title", ""),
            "lab_id": lab_id,
            "status": "completed",
            "user": exp_data.get("userid_human", ""),
            "workflow_json": workflow_json,
            "metadata": extract_metadata(extra_fields),
            "raw_data": build_raw_data(args.elab_id),
            "results": build_results(args.elab_id),
        }

        if args.dry_run:
            print("DRY RUN - Would insert:")
            print(json.dumps(data, indent=2, default=str))
            conn.rollback()
            return 0

        # Commit to database
        exp_db_id = upsert_experiment(cursor, args.elab_id, data)
        conn.commit()

        print(
            f"Experiment {args.elab_id} committed successfully (DB ID: {exp_db_id})"
        )
        return 0

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if "conn" in locals():
            conn.rollback()
        return 1
    finally:
        if "conn" in locals():
            conn.close()


if __name__ == "__main__":
    sys.exit(main())